<script type="text/javascript" src="<?php echo $this->getJsUrl()?>jquery-latest.js"></script>
<script type="text/javascript">
jQuery.noConflict();

function loadProduct(cid){
	form_key = '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>';
	url= '<?php echo Mage::getBaseUrl();?>carpet/index/loadproduct';
	if(cid > 0){
		
		jQuery('#loader').css('display','block');
		jQuery.ajax({
			url:url,
			data: { form_key: form_key, catId: cid },  
			success:function(result){
				jQuery('#loader').css('display','none');
				jQuery('#mainProduct').html(result);
			}
		});
	}else{
		alert('Please select a valid category');
	}
}

function load_three_way_Product(cid){
	form_key = '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>';
	url= '<?php echo Mage::getBaseUrl();?>carpet/index/loadproducthome';
	if(cid > 0){
		
		jQuery('#loaderp2').css('display','block');
		jQuery.ajax({
			url:url,
			data: { form_key: form_key, catId: cid },  
			success:function(result){
				jQuery('#loaderp2').css('display','none');
				jQuery('#mainProduct2').html(result);
			}
		});
	}else{
		alert('Please select a valid category');
	}
}

function loadProductDetails(pid){
	//alert("pid::"+pid);
	pidar = pid.split(':');
	form_key = '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>';
	url= '<?php echo Mage::getBaseUrl();?>carpet/index/loadproductdetails';
	
	//url= '<?php echo Mage::getBaseUrl();?>customoptions/index/index/id/'+pidar[1]+'/';
	//url= '<?php echo Mage::getBaseUrl();?>catalog/product/view/id/610/';
	
	if(pid != ''){
		jQuery('#loader').css('display','block');
		jQuery.ajax({
			url:url,
			data: { form_key: form_key, pId: pid },  
			success:function(result){
						ret = result.split('##');
				jQuery('#loader').css('display','none');
				jQuery('#total_display').html(ret[0]);
				jQuery('#total_display_1').html(ret[0]);
				jQuery('#cusopt').html(ret[1]);
				
				
			}
		});
		
	}else{
		alert('Please select a valid product');
	}
	
}

function loadProductDetailsPop(pid){
	//alert("pid::"+pid);
	pidar = pid.split(':');
	form_key = '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>';
	url= '<?php echo Mage::getBaseUrl();?>carpet/index/loadproductdetailspop';
	var param="pId="+pid+"&form_key="+form_key;
	if(pid != ''){
		jQuery('#loader').css('display','block');
		jQuery.ajax({
			url:url,
			data: param,  
			success:function(result){
				//alert(result);
				//return false;
				ret = result.split('##');
				//alert(ret[0]);
				//jQuery('#loader').css('display','none');
				//jQuery('#total_display').html(ret[0]);
				//jQuery('#total_display_1').html(ret[0]);
				//jQuery('#cusopt').html(ret[1]);
				jQuery('#cusopt_pop').html(ret[1]);
				//jQuery('#artworkreturn').show();
				
			}
		});
		
	}else{
		alert('Please select a valid product');
	}
	
}





function getchildren(optid,optval){
	//alert(optid);
	//alert(optval);
	form_key = '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>';
	url= '<?php echo Mage::getBaseUrl();?>carpet/index/getchildopt';
	if(optval != 0){
		jQuery.ajax({
			url:url,
			data: { form_key: form_key, optId: optid, optvalId :optval  },  
			success:function(result){
				jQuery('#cusopt_1').html(result);
				
			}
		});
		
		
		
	}else{
		alert('Please select a valid product');
	}
}

function getchildrenpop(optid,optval){
	form_key = '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>';
	url= '<?php echo Mage::getBaseUrl();?>carpet/index/getchildoptpop';
	var param="form_key="+form_key+"&optId="+optid+"&optvalId="+optval;
	//alert(param);
	if(optval != 0){
		jQuery.ajax({
			url:url,
			data: param,  
			success:function(result){
				//alert(result);
				jQuery('#cusopt_pop_1').html(result);
				}
		});
	}
	else{
		alert('Please select a valid product');
	}
}



</script>



<?php
	$storeId=Mage::app()->getStore()->getId();
	$rootCategoryId = Mage::app()->getStore($storeId)->getRootCategoryId();
	$categories = Mage::getModel('catalog/category')->getCategories($rootCategoryId);
?>



<div class="formInfo">
	<div id="instantBox" class="clearfix">
		<div class="lable"></div>
		<div class="lable lable2"></div>
		<div class="instantBox-body clearfix">
			<!---------Left Starts ---------->
			<div class="instantPrice float-L">
				<dl class="clearfix">
				<dt>Category</dt>
				<dd id="mainCategories">   
					<select name="category" class="textfield" id="category" onchange="loadProduct(this.value)">
					    <option value="0">--Please select--</option>
					    <?php foreach($categories as $_category){ ?>
					    <option value="<?php echo $_category->getId();?>"><?php echo $_category->getName();?></option>
					    <?php } ?>
					</select> 
				</dd>
				</dl>
				
				<dl class="clearfix">
				<dt>Product</dt>
				<dd>
					<div id="mainProduct">
					  <select class="textfield" id="product_sel">
					  <option value="0">--Please select--</option>
					  </select>
					</div>
					<div id="loader" style="display:none; margin-left:100px;">
					<img src="<?php echo $this->getSkinUrl();?>images/loading.gif" alt="loading"/>
					</div>                     
				</dd>
				</dl>
				
				<div class="option" id="cusopt"></div>
				<div class="option" id="cusopt_1"></div>
				
				
				<dl class="clearfix">
				<dt>Price</dt>
				<dd class="price">
				  <div id="total_display" class="float-L">$0.00</div>
				  
				</dd>
			        </dl>
				
				
				<div class="pricebottom">
					<span class="prcbutn" style="height:0px">
						<input type="button" style="color:transparent;" value="start order" class="startOrder-btn" title="Start Order" name="getprice">
					</span>
					<dl class="totalprice blue-clr">
						<div class="pricetopbg"></div>
						<span id="grandtotaldisplay"> TOTAL PRICE : <span id="total_display_1">$0.00 </span></span>
						<div class="pricebtmbg"></div>
					</dl>
				</div>
			</div>
			<!------------Left Ends------- -->
			<div class="instant-separator float-L">
				<div class="ortext"></div>
		        </div>
			
			<!--Right Starts -->
			<div class="quickStart-Order float-L">
				<div class="quickStart-Order float-L">
					<div class="title blue-clr">3 Easy ways to order</div>
					<div class="align-C">Category:
						<select name="threeway_category" class="textfield dropdown" style="width:215px;" id="threeway_category" onchange="load_three_way_Product(this.value)">
							<option value="0">--Please select--</option>
							<?php foreach($categories as $_category){ ?>
							<option value="<?php echo $_category->getId();?>"><?php echo $_category->getName();?></option>
							<?php } ?>
						</select>
					</div>
					
					<div id="mainProduct2">                
						Product:
						<select class="textfield" name="threeway_product" id="threeway_product" style="width:215px; margin-left:8px;">
							<option value="0">--Please select--</option>
						</select>                  
					</div>               
					<div id="loaderp2" style="display:none; margin-left:100px;">
					<img src="<?php echo $this->getSkinUrl();?>images/loading.gif" alt="loading"/>
					</div>
					
					<div class="StartorderButtons">
						<input name="submit-prt-ready" type="button" value="print ready" title="Submit Print Ready Design" class="buttons" id="printreadybtn" style="color:transparent;" onclick="uploadArtWork();" />
						<input name="order-form" value="design tool" type="button" title="Design Your Own Banner" class="buttons designYour-banner" id="prdbtn" style="color:transparent;" />
						<input name="product-details" type="button" value="letusdesign" title="Let us Design Your Banner" class="buttons letus-design-banner" id="letusbtn"  style="color:transparent;" />
					</div>
					
				</div>
			
					
			</div>
			<!--Right Ends -->
		</div>
	</div>
</div>

<!---------------------------------------------------------------------------------------------------------------------------------------->


<script type="text/javascript">

function uploadArtWork()
{
	
	var pid="";
	var cid="";
	
	pid=document.getElementById("threeway_product").value;
	cid=document.getElementById("threeway_category").value;
	
	arr_pro_devider=Array();
	
	arr_pro_devider=pid.split(":");
	
	if (arr_pro_devider.length>1)
	{
		pid=arr_pro_devider[1];
	}
	else
	{
		pid="";
	}
	
	if (pid!="" && cid!="0")
	{
		getartWorkgc(pid,cid);
	}
	else
	{
		alert("Please select category and product before uploading an artwork");
	}
	
	
	
}


function getartWorkgc(pid,cid){
    form_key = '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>';
    url= '<?php echo Mage::getBaseUrl();?>carpet/index/getartwork';
    
    if(pid != ''){
        jQuery("#ajaxloader").css('display','block');
        jQuery.ajax({
            url:url,
            data: { form_key: form_key, prodId: pid, catId: cid},  
            success:function(result){
                ret = result.split('##');
                jQuery("#instantPriceId").html('');
                jQuery("#ajaxloader").css('display','none');
                jQuery("#uploadArtWorkPopup").css('display','block');
                jQuery("#artworkreturn_1").html(ret[0]);
                jQuery("#artworkreturn_2").html(ret[1]);
                jQuery("#artworkreturn_3").html(ret[2]);
								jQuery('.arrowbtm').trigger('click');
								jQuery('.arrowtop').trigger('click');
								loadProductDetailsPop(pid);
            }
	});
        
        
    }
}
function changLimit(valu){
    lgth = valu.length;
    allgth = 255-lgth;
    jQuery("#tWords").html(allgth);
    
}
function addToCartGc(pid){
	//alert(pid);
    
    url= '<?php echo Mage::getBaseUrl();?>carpet/index/addcartartwork';
    var selArray = new Array();
    var optArray = new Array();
    var selStr = '';
    var optStr = '';
    var notes = jQuery('#description_pr').val();
    
    
    price = jQuery('#productcustomprice').val();
    jQuery('#artworkreturn .option select').each(function() {
        selid = this.id.split('_');
        optVal = jQuery( "#"+this.id+" option:selected" ).val();
        //opId = selid[1];
        
        if(selid[1] != "" && optVal !=""){
            selArray.push(selid[1]);
            optArray.push(optVal);
            
            selStr +=selid[1]+"##";
            optStr +=optVal+"##";
            
        }
        
       
        
    });
   
    seloptstr = selStr+"**"+optStr;
    //jQuery('#cusprice').val(price);
    jQuery('#optarr').val(seloptstr);
    jQuery('#cusnote').val(notes);
    
    var form = new FormData(jQuery('#form-validate')[0]);
    if(optArray.length > 0){
        
        jQuery.ajax({
            type:'POST',
            xhrFields: {
                withCredentials: true
            },
            async: true,
            cache: true,
            contentType: false,
            processData: false,
            url:url,
            data:form ,
            //data: { form_key: form_key, prodId: pid, optarr: seloptstr, cusprice: price, file: artfile},  
            success:function(result){
							//alert(result);
							//return false;
                jQuery('#subret').css('display','block');
                jQuery('#subret').html(result);
                //jQuery("#subret").fadeOut(5000);
            }
	});
        
    }else{
        
        alert("Please select product options");
    }
   
    
}



jQuery(document).ready(function(e) {
    jQuery('#close_button').click(function(){
        
        var htmlv = jQuery('<div>').append(jQuery("#artworkreturn").clone()).html();
        jQuery("#instantPriceId").html(htmlv);
        jQuery('#uploadArtWorkPopup').hide();
        window.location.reload(true);
        
    });
});
function getSizeVal(size,classtype){
			var sizeid=size;
			var Sizearr=size.split('_');
			var name=Sizearr[1];
			var size=jQuery("#"+size).val();
			if(classtype=="arrowTop"){
				size++;
				jQuery('#'+sizeid).val(size);
				var pid=jQuery('#product_id').val();
				url= '<?php echo Mage::getBaseUrl();?>carpet/index/gettireunitprice';
				qty=jQuery('#room_width').val() * jQuery('#room_length').val();
				var cur_price=jQuery('#price_get').val();
				var opt_price=jQuery('#opt_price').val();
				var param="pId="+pid+"&qty="+qty+"&old_price="+cur_price+"&opt_price="+opt_price;
				if(pid != ''){
					jQuery('#loader').css('display','block');
					jQuery.ajax({
						url:url,
						data: param,  
						success:function(result){
							jQuery('#cusprice').val(result);
							jQuery('#price-to-change').html('AU$'+result);
						}
					});
					
				}
			}
			if(classtype=="arrowbtm"){
				if(size > 1){	
				size--;
				jQuery('#'+sizeid).val(size);
				var pid=jQuery('#product_id').val();
				url= '<?php echo Mage::getBaseUrl();?>carpet/index/gettireunitprice';
				qty=jQuery('#room_width').val() * jQuery('#room_length').val();
				var cur_price=jQuery('#price_get').val();
				var param="pId="+pid+"&qty="+qty+"&old_price="+cur_price;
				if(pid != ''){
					jQuery('#loader').css('display','block');
					jQuery.ajax({
						url:url,
						data: param,  
						success:function(result){
							jQuery('#cusprice').val(result);
							jQuery('#price-to-change').html('AU$'+result);
						}
					});
					
				}
				}
			}
}
function getconversion(unit){
	var prev_unit=jQuery('#cnvunit').val();
	var cur_unit=unit;
	if(prev_unit=='m' && cur_unit=="cm"){
		var room_width=jQuery('#room_width').val()*100;
		var room_length=jQuery('#room_length').val()*100;
		jQuery('#room_width').val(room_width);
		jQuery('#room_length').val(room_length);
		jQuery('#cnvunit').val(cur_unit);
	}
	if(prev_unit=='m' && cur_unit=="mm"){
		var room_width=jQuery('#room_width').val()*1000;
		var room_length=jQuery('#room_length').val()*1000;
		jQuery('#room_width').val(room_width);
		jQuery('#room_length').val(room_length);
		jQuery('#cnvunit').val(cur_unit);
	}
	if(prev_unit=='cm' && cur_unit=="m"){
		var room_width=jQuery('#room_width').val()/100;
		var room_length=jQuery('#room_length').val()/100;
		jQuery('#room_width').val(room_width);
		jQuery('#room_length').val(room_length);
		jQuery('#cnvunit').val(cur_unit);
	}
	if(prev_unit=='cm' && cur_unit=="mm"){
		var room_width=jQuery('#room_width').val()*10;
		var room_length=jQuery('#room_length').val()*10;
		jQuery('#room_width').val(room_width);
		jQuery('#room_length').val(room_length);
		jQuery('#cnvunit').val(cur_unit);
	}
	if(prev_unit=='mm' && cur_unit=="m"){
		var room_width=jQuery('#room_width').val()/1000;
		var room_length=jQuery('#room_length').val()/1000;
		jQuery('#room_width').val(room_width);
		jQuery('#room_length').val(room_length);
		jQuery('#cnvunit').val(cur_unit);
	}
	if(prev_unit=='mm' && cur_unit=="cm"){
		var room_width=jQuery('#room_width').val()/10;
		var room_length=jQuery('#room_length').val()/10;
		jQuery('#room_width').val(room_width);
		jQuery('#room_length').val(room_length);
		jQuery('#cnvunit').val(cur_unit);
	}
	
}

jQuery('.textfield').live('change',function () {
	var select_id=jQuery(this).attr('id');
  var select_val=jQuery("#"+select_id+" option:selected").text();
	var n = select_val.indexOf("+");
	if(n > 0){
	var select_val_arr=select_val.split('+');
	var priceStr=select_val_arr[1];
	var price=priceStr.replace("$","");
	var price=parseFloat(price);
	//var opt_price=jQuery('#opt_price').val();
	jQuery('#opt_price').val(price);
	var pricePro=parseFloat(jQuery('#price_get').val());
	var changedPrice=price+pricePro;
	jQuery('#price-to-change').html('AU$'+changedPrice);
	jQuery('#cusprice').val(changedPrice);
	}
	
	});

</script>
<?php
if(Mage::getModel('catalog/layer')->getCurrentCategory()){
    $catId = Mage::getModel('catalog/layer')->getCurrentCategory()->getId();   
}else{
    $catId=0;
}
?>
<?php //$productId = $this->getProduct()->getId(); ?>
<div class="ajaxloader" id="ajaxloader" style="display: none">LOADER</div>
<?php/*
<div class="formInfo">
	<div id="instantBox" class="clearfix">
		<div class="lable"></div>
		<div class="lable lable2"></div>
		<div class="instantBox-body clearfix">
			<!---------Left Starts ---------->
			<div class="instantPrice float-L" id="instantPriceId">
				
			    <?php echo $this->getChildHtml('', true, true);?>
                                
			</div>
			<!------------Left Ends------- -->
			<div class="instant-separator float-L">
			    <div class="ortext"></div>
		        </div>
			
			
			<!--Right Starts -->
			<div class="quickStart-Order float-L">
				<div class="quickStart-Order float-L">
			                   
					<div id="loaderp2" style="display:none; margin-left:100px;">
					    <img src="<?php echo $this->getSkinUrl();?>images/loading.gif" alt="loading"/>
					</div>
					
					<div class="StartorderButtons">
                                            <input name="submit-prt-ready" type="button" value="print ready" title="Submit Print Ready Design" class="buttons" id="printreadybtn" onclick="getartWorkgc(<?php echo $productId ?>,<?php echo $catId ?>)" style="color:transparent;" />
                                            <input name="order-form" value="design tool" type="button" title="Design Your Own Banner" class="buttons designYour-banner" id="prdbtn" style="color:transparent;" />
                                            <input name="product-details" type="button" value="letusdesign" title="Let us Design Your Banner" class="buttons letus-design-banner" id="letusbtn"  style="color:transparent;" />
					</div>
				</div>
			</div>
			
			<!--Right Ends -->		
		</div>
	</div>
</div>
<?php */?>
<?php /*
<div class="product-options" id="product-options-wrapper">
    <?php //echo $this->getChildHtml('', true, true);?>
    <?php if ($this->hasRequiredOptions()):?>
        <!--<p class="required"><?php //echo $this->__('* Required Fields') ?></p>-->
    <?php endif;?>
</div>
*/ ?>
<script type="text/javascript">decorateGeneric($$('#product-options-wrapper dl'), ['last']);</script>
<?php
//$calc_block = new BS_Carpet_Block_Catalog_Product_View;
//$arr = $calc_block->getBoSuaCarpetJsonConfig();



?>
<div id="uploadArtWorkPopup" style="display: none">
    <div id="uploadArtWork">
        
        <div class="txtHeading"></div>
        <div id="close_button" title="Click to close" >X</div>
        <div id="liveFormData">
            <div class="liveFormData_1">
            <div id="artworkreturn_1"></div>
            
            <div id="artworkreturn">
                <div class="option" id="cusopt_pop"></div>
							  <div class="option" id="cusopt_pop_1"></div>
								<div class="calculator-wrapper">
													<div class="block block-calculator">
															<?php /*
															<div class="block-title">
																	<strong><span><?php echo $this->__('Calculator')?></span></strong>
															</div>
															*/ ?>
															<div class="block-content">
																 
														<dl style="" id="unitBox" class="clearfix">
																			<dt>Unit</dt>
																			<dd>
															<input type="hidden" name="cnvunit" id="cnvunit" value="m"/>
															<select class="textfield dropdown-s" id="major" name="major" onchange="getconversion(this.value);">
																	<option value="m">m.</option>
																	<option value="cm">cm.</option>
																	<option value="mm">mm.</option>
																					</select> 
																			</dd>
																	</dl>
														
														<dl style="" id="sizeBox" class="clearfix">
																<dt>Size (m)</dt>
																
																<dd id="main_size">
																<div class="sizes-block">
																	<input type="text" size="5" value="1" name="room_width" id="room_width" >
																	<div class="float-L">
																<a onclick=" getSizeVal('room_width','arrowTop');" class="arrowTop" href="javascript:void(0);">I</a>
																<a onclick="getSizeVal('room_width','arrowbtm');" class="arrowbtm" href="javascript:void(0);">D</a>
																	</div>
																	<span>width</span>
																</div>		  
																
																<div class="sizes-block last">
																	<input type="text" size="5" value="1" name="room_length" id="room_length" >
																	<div class="float-L">
																<a onclick=" getSizeVal('room_length','arrowTop');" class="arrowTop" href="javascript:void(0);">I</a>
																<a onclick=" getSizeVal('room_length','arrowbtm');"  class="arrowbtm" href="javascript:void(0);">D</a>
																	</div>
																	<span>height</span> 
																</div>
																								
																
																</dd>
													
																
														</dl>
														
													
														
																	<?php /* 
																	 <div class="inneri">
																			<div class="inputi">
																				<p class="inputi-f"><?php echo $this->__('Width (m)')?></p>
																				<p class="inputi-f-s">&nbsp;</p>
																				<p class="inputi-f"><?php echo $this->__('Length (m)')?></p>
																			</div>
																			<div class="inputi">
																				<p class="inputi-f"><input type="text" size="5" value="1" name="room_width" id="room_width" onkeyup="ca.numberOnly(this,false);"></p>
																				<p class="inputi-f-s">X</p>
																				<p class="inputi-f"><input type="text" size="5" value="1" name="room_length" id="room_length" onkeyup="ca.numberOnly(this,false);"></p>
																			</div>
																			<?php  ?>
																			<div class="buttoni">
																				<button type="button"  onclick="ca.calcRoom();" class="button"><span><span><?php echo $this->__('Calculate')?></span> </span> </button>
																			</div>
																			<?php  ?>
																	 </div> 
																	 */ ?>
																		
																 <?php /*   */ ?>
															</div>
															
													</div>


													<div class="block block-calculator" style="display: none">
															<div class="block-title">
																	<strong><span><?php echo $this->__('Conversion')?></span></strong>
															</div>
															<div class="block-content">
																	<p><?php echo $this->__('Convert feet and/or inches into meters:')?></p>
																	<div class="inneri">
																		<div class="inputi">
																			<div class="inputi-f"><?php echo $this->__('Feet')?></div>
																			<div class="inputi-f-s">&nbsp;</div>
																			<div class="inputi-f"><?php echo $this->__('Inches')?></div>
																		</div>
																		<div class="inputi">
																			<div class="inputi-f"><input type="text" size="5" value="1" name="feet" id="calc_feet" ></div>
																			<div class="inputi-f-s">&nbsp;</div>
																			<div class="inputi-f"><input type="text" size="5" value="1" name="inches" id="calc_inches"></div>
																		</div>
																		<div class="buttoni">
																			<button type="button"  class="button"><span><span><?php echo $this->__('Convert')?></span> </span> </button>
																		</div>
																	</div>
																	<div class="inneri">
																		<div class="texti">
																	<p><b><?php echo $this->__('Result:')?></b> <br>
																	<font color="#FF0066"><span id="calc_metres">0</span> <?php echo $this->__('meters')?></font>
																	</p>
															</div>
																	</div>
																	
															</div>
													</div>
</div>

            </div>
            <div id="artworkreturn_2"></div>
            </div>
        </div>
        <div id="artworkreturn_3"></div>
    </div>
    
</div>
<?php




?>