<script type="text/javascript">
    if(typeof(jQueryIWD) == "undefined"){if(typeof(jQuery) != "undefined") {jQueryIWD = jQuery;}} $ji = jQueryIWD;
    $ji(document).ready(function () {
        IWD.OrderManager.Grid.iwdViewOrderedItems = "<?php echo Mage::helper('adminhtml')->getUrl('*/sales_orderr/orderedItems'); ?>?isAjax=true";
        IWD.OrderManager.Grid.iwdViewProductItems = "<?php echo Mage::helper('adminhtml')->getUrl('*/sales_orderr/productItems'); ?>?isAjax=true";
        IWD.OrderManager.Grid.isFixGridHeader = <?php echo Mage::getModel('iwd_ordermanager/order_grid')->isFixGridHeader(); ?>;
        IWD.OrderManager.Grid.statusColors = "<?php echo Mage::getModel('iwd_ordermanager/order_grid')->getStatusColors(); ?>";
        IWD.OrderManager.Grid.init();
    });
</script>