<?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('top_menu_slider')->toHtml() ?>
<!--<div class="contact_info"><img src="<?php //echo $this->getSkinUrl('images/phone_info.png');?>" alt="contact info"/></div>-->
<?php  $catName = Mage::getSingleton('catalog/layer')->getCurrentCategory()->getName(); ?>
<?php  $curCatId = Mage::getSingleton('catalog/layer')->getCurrentCategory()->getId(); ?>
<?php    $_productCollection=$this->getLoadedProductCollection();    $_helper = $this->helper('catalog/output');?>
<div class="cate_listing"> <img src="<?php echo $this->getSkinUrl()?>images/stand_kits_heading.png" style="margin-left:10px;" />
  <p style="color:#fff; padding:10px; line-height:25px;"> Exhibitions and marketing camaigns are the perfect opportunity to introduce your company to the public & we want to help you with your company's image. We have a huge selection of tradeshow exhibits, press media wall, tradeshow fabric banner stands, pop up booths, portable exhibits & presentation boards. Make an impression with our advertising & promotional marketing display products. Vivid Ads (Advertising & Display Solutions) is Australia's choice to buy in-stock exhibit stands, fabric mural media backdrop walls, expo booth displays, road show displays, trade fair booths (exhibit / expo) equipments and outdoor advertsing mesh signs and banners. </p>
</div>
<?php  $imageUrl = Mage::getSingleton('catalog/layer')->getCurrentCategory()->getImageUrl();?>
<?php if(!$_productCollection->count()): ?>
<?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('external-block')->toHtml() ?>
<!--<p class="note-msg"><?php //echo $this->__('There are no products matching the selection.') ?></p>-->
<?php else: ?>
<div class="cate_listing">
  <?php // List mode ?>
  <?php $_iterator = 0; ?>
  <?php foreach ($_productCollection as $_product): ?>
  <?php  $imageName =  $_product->getData('small_image');?>
  <?php //echo '<pre>'; print_r($_product); echo '</pre>';?>
  <?php  $imageUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'catalog/product' . $imageName; 	?>
  <?php //echo $imageUrl = Mage::getModel('catalog/product_media_config')->getMediaUrl($_product>getThumbnail()); ?>
  <div class="pro_left wide">
    <div class="banner" style="width:99%;"> <a style="width:100%;" href="<?php //echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"> <img style="width:100%; height:399px !important" src="<?php echo $imageUrl; ?>"  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> </a> </div>
  </div>
  <?php // Product Image ?>
  <?php // Product description ?>
  <?php endforeach; ?>
  <script type="text/javascript">decorateList('products-list', 'none-recursive')</script> </div>
<?php endif; ?>
