<?php
/**
 * Delivery Date
 *
 * @category:    AdjustWare
 * @package:     AdjustWare_Deliverydate
 * @version      1.1.7
 * @license:     5aaeipF7ooGEnIcLG9rWordPqCAsU9nCJvGBjy56tC
 * @copyright:   Copyright (c) 2014 AITOC, Inc. (http://www.aitoc.com)
 */
?>
<script type="text/javascript">
    
    var aitDeliverydateInitialization = Class.create(
    {
        initialize: function() 
        {
            this.validatorUrl = '<?php echo $this->getValidationUrl(); ?>';
            this.fields = <?php echo Mage::helper('core')->jsonEncode($this->getFormIds()); ?>;
            this.initFields();
        },
        
        initFields: function()
        {
            var fields = $A(this.fields);
            fields.each(this.setFieldObserver.bind(this));
            
        },
        
        setFieldObserver: function(fieldName)
        {
            var aitDdValidator = new aitDeliverydateValidator(this.validatorUrl , fieldName);
            $(fieldName).observe('change', aitDdValidator.validate.bind(aitDdValidator));
        }

    });
    
    new aitDeliverydateInitialization();
    
    <?php if(Mage::getStoreConfig('checkout/adjdeliverydate/show_calendar_by_click_on_date_field')): ?>
    <?php foreach($this->getFormIds() as $formId): ?>
	Event.observe($('<?php echo $formId; ?>'), 'click', 
		function () { $('<?php echo $formId; ?>_trig').simulate('click'); return false; }
	);
	<?php endforeach; ?>
    <?php endif; ?>

</script>