

<?php /*?><?php 

    $layer = Mage::getSingleton('catalog/layer');

    $_category = $layer->getCurrentCategory();

    $currentCategoryId = $_category->getId();

    if($currentCategoryId != 48){

        $children = Mage::getModel('catalog/category')->getCategories($currentCategoryId);

        ?>

        <div class="block block-currency">

            <div class="block-title">

                <strong><span style='font-size:12px;'><?php echo $_category->getName();?></span></strong>

            </div>

            <div class="block-content menu">

                <ul id="menu">

                    <?php

                    foreach ($children as $category)

                    {

                        echo '<li><a href="'.$this->getCategoryUrl($category).'">'.$category->getName()."</a></li>\n";

                          //echo $category->getName(); // will return category name 

                          //echo $category->getRequestPath(); // will return category URL

                    }?>

                </ul>

            </div>

        </div>

    <?php                

    }    

    ?><?php */?>

<div class="block block-currency">

    <div class="block-title">

        <strong><span>Categories</span></strong>

    </div>

    <div class="block-content menu">

        <ul id="menu">

            <?php

            $obj = new Mage_Catalog_Block_Navigation();

            $store_cats = $obj->getStoreCategories();

            $current_cat    = $obj->getCurrentCategory();

            $current_cat    = (is_object($current_cat) ? $current_cat->getName() : '');



            foreach ($store_cats as $cat) {

                if ($cat->getName() == $current_cat) {

                    echo '<li class="current"><a href="'.$this->getCategoryUrl($cat).'">'.$cat->getName()."</a>\n\n";

                } else {

                    echo '<li><a href="'.$this->getCategoryUrl($cat).'">'.$cat->getName()."</a></li>\n";

                }

            }

            ?>

        </ul>

    </div>

</div>
