<?php
$url = Mage::helper("adminhtml")->getUrl("timeline/adminhtml_timeline/savetime");
$url2 = Mage::helper("adminhtml")->getUrl("timeline/adminhtml_timeline/savetasknumber");

$connectionRead = Mage::getSingleton('core/resource')->getConnection('core_read');
$connectionWrite = Mage::getSingleton('core/resource')->getConnection('core_write');

$temptableTimeline=Mage::getSingleton('core/resource')->getTableName('product_timeline');
//$sqlTimeline="SELECT * FROM ".$temptableTimeline." WHERE product_id = '0' ";
$sqlTimeline = $connectionRead->select()
			->from($temptableTimeline, array('*'))
			->where('product_id=?',0); 
$chkTimeline = $connectionRead->fetchAll($sqlTimeline);

$temptableTask=Mage::getSingleton('core/resource')->getTableName('subadmin_task_number');
//$sqlTask="SELECT * FROM ".$temptableTask." WHERE entity_id = '1' ";
$sqlTask = $connectionRead->select()
			->from($temptableTask, array('*'))
			->where('entity_id=?',1);
$chkTask = $connectionRead->fetchAll($sqlTask);
	
?>

<div class="maintimeline">
    <form enctype="multipart/form-data" name="form_planning" id="form_planning" method="POST" action="<?php echo $url?>">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>">
    <table class="timelinetab">
        <tr>
            <td class="timecap">Artwork delay time</td>
            <td><input type="text" name="artwork" value="<?php echo $chkTimeline[0]['artwork_day']?>" /></td>
            <td><input type="checkbox" name="sunday_artwork" value="1" <?php if($chkTimeline[0]['sunday_artwork'] == 1)echo 'checked';?>/> Exclude Sunday</td>
            <td><input type="checkbox" name="holiday_artwork" value="1" <?php if($chkTimeline[0]['holiday_artwork'] == 1)echo 'checked';?>/> Exclude Holiday</td>
        </tr>
        <tr>
            <td class="timecap">Proof approval delay time111</td>
            <td><input type="text" name="proof" value="<?php echo $chkTimeline[0]['proof_day']?>" /></td>
            <td><input type="checkbox" name="sunday_proof" value="1" <?php if($chkTimeline[0]['sunday_proof'] == 1)echo 'checked';?>/> Exclude Sunday</td>
            <td><input type="checkbox" name="holiday_proof" value="1" <?php if($chkTimeline[0]['holiday_proof'] == 1)echo 'checked';?>/> Exclude Holiday</td>
        </tr>
        <tr>
            <td class="timecap">Production Start delay time</td>
            <td><input type="text" name="production" value="<?php echo $chkTimeline[0]['production_day']?>" /></td>
            <td><input type="checkbox" name="sunday_production" value="1" <?php if($chkTimeline[0]['sunday_production'] == 1)echo 'checked';?>/> Exclude Sunday</td>
            <td><input type="checkbox" name="holiday_production" value="1" <?php if($chkTimeline[0]['holiday_production'] == 1)echo 'checked';?>/> Exclude Holiday</td>
        </tr>
        <tr>
            <td class="timecap">Delivary delay time</td>
            <td><input type="text" name="delivary" value="<?php echo $chkTimeline[0]['delivary_day']?>" /></td>
            <td><input type="checkbox" name="sunday_delivary" value="1" <?php if($chkTimeline[0]['sunday_delivary'] == 1)echo 'checked';?>/> Exclude Sunday</td>
            <td><input type="checkbox" name="holiday_delivary" value="1" <?php if($chkTimeline[0]['holiday_delivary'] == 1)echo 'checked';?>/> Exclude Holiday</td>
        </tr>
        <tr>
            <td class="timecap">Shipping delay time</td>
            <td><input type="text" name="shipping" value="<?php echo $chkTimeline[0]['shipping_day']?>" /></td>
            <td><input type="checkbox" name="sunday_shipping" value="1" <?php if($chkTimeline[0]['sunday_shipping'] == 1)echo 'checked';?>/> Exclude Sunday</td>
            <td><input type="checkbox" name="holiday_shipping" value="1" <?php if($chkTimeline[0]['holiday_shipping'] == 1)echo 'checked';?>/> Exclude Holiday</td>
        </tr>
        <tr>
            <td colspan="4"><button type="submit" name="submit">Save</button></td>
        </tr>
    </table>
    </form>
</div>
<div class="commontask">
    <form enctype="multipart/form-data" name="form_planning" id="form_planning" method="POST" action="<?php echo $url2?>">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>">
        <table class="tabnum">
            <tr>
                <td class="timecap">Number of Task for Each Sub-Admin per Day</td>
                <td><input type="text" name="task_number" value="<?php echo $chkTask[0]['task_number']?>"  /></td>
                <td style="width:500px;"></td>
                <td><button type="submit" name="submit">Save</button></td>
            </tr>
        </table>
    </form>
</div>
