rm -fr skin/frontend/default/default/devel
rm -fr skin/frontend/default/default/devel/images
rm -fr skin/frontend/default/default/devel/css
rm -fr app/design/frontend/default/default/layout/devel
rm -fr app/design/frontend/default/default/template/devel
rm -fr app/design/frontend/default/default/template/devel/page
rm -fr app/design/frontend/default/default/template/devel/help
rm -fr app/design/frontend/default/default/template/devel/help/panels
rm -fr app/design/frontend/default/default/template/devel/help/panels/block
rm -fr app/design/frontend/default/default/template/devel/help/panels/editor
rm -fr app/design/frontend/default/default/template/devel/help/layouts
rm -fr app/design/frontend/default/default/template/devel/help/theme
rm -fr app/design/frontend/default/default/template/devel/help/blocks
rm -fr app/design/frontend/default/default/template/devel/filesystem
rm -fr app/design/frontend/default/default/template/devel/frontend
rm -fr shell/devel
rm -fr shell/devel/devel
rm -fr shell/devel/git
rm -fr js/devel
rm -fr js/devel/varien
