<?php
/**
 * Template index.phtml
 *
 * @author Aptoplex
 * @copyright 2015 Aptoplex
 *
 * @var $this Aptoplex_EasyUploader_Block_Index
 */

$order_id = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$my_order = Mage::getModel('sales/order')->loadByIncrementId($order_id);
$email = $my_order->getCustomerEmail();

$flashRuntimeUrl = $this->getSkinUrl("lib/aptoplex_easyuploader/plupload/js/Moxie.swf");
$silverlightRuntimeUrl = $this->getSkinUrl("lib/aptoplex_easyuploader/plupload/js/Moxie.xap");

?>

<div id="uploader">
    <div>
        <?php
        if (Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_PAGE_TITLE, null)) { ?>
        <div class="page-title">
            <h1><?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_PAGE_TITLE, null); ?></h1>
        </div>
        <?php
        } ?>
        <?php
        if (Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_INTRO_HTML, null)) { ?>
        <div id="intro">
            <?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_INTRO_HTML, null); ?>
        </div>
        <?php
        } ?>
        <div>
            <form id="file-upload-form" action="POST">
                <div class="col2-set">
                    <div class="col-1">
                        <div class="content">
                            <fieldset>
                                <ul class="form-list">
                                    <li class="fields">
                                        <label for="order-number" class="required"><em>*</em></em><?php echo $this->__('Order Number:') ?></label>
                                        <div class="input-box">
                                            <?php
                                            if (Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_NON_STANDARD_ORDER_NUMBER_FORMAT, null)) { ?>
                                                <input id="order-number" type="text" name="order-number" class="input-text required-entry" value="<?php echo $order_id; ?>" tabindex="1"/>
                                            <?php
                                            }
                                            else { ?>
                                                <input id="order-number" type="text" name="order-number" class="input-text required-entry validate-number" value="<?php echo $order_id; ?>" tabindex="1"/>
                                            <?php
                                            } ?>
                                            <p class="uploader-field-desc"><?php echo $this->__("Enter your order number you received from us when you placed your order. You can find this in either the e-mail confirmation we will have sent to you or in your"); ?> <a href="<?php echo Mage::getBaseUrl() . 'customer/account'; ?>" target="_blank"><?php echo $this->__("Account area."); ?></a></p>
                                        </div>
                                    </li>
                                </ul>
                            </fieldset>
                        </div>
                    </div>
                    <div class="col-2">
                        <div class="content">
                            <fieldset>
                                <ul class="form-list">
                                    <li class="fields">
                                        <label for="email-address" class="required"><em>*</em><?php echo $this->__('E-mail Address:') ?></label>
                                        <div class="input-box">
                                            <input id="email-address" type="text" name="email-address" class="input-text required-entry validate-email" value="<?php echo $email; ?>" tabindex="2"/>
                                            <p class="uploader-field-desc"><?php echo $this->__("Enter the e-mail address you used when you placed your order."); ?></p>
                                        </div>
                                    </li>
                                </ul>
                            </fieldset>
                        </div>
                    </div>
                </div>
                <div class="col1-layout">
                    <div class="content">
                        <fieldset>
                            <ul class="form-list">
                                <li class="fields">
                                    <label for="additional-comments"><?php echo $this->__('Additional Comments:') ?></label>
                                    <div class="input-box">
                                        <textarea id="additional-comments" name="additional-comments" class="input-text" tabindex="3"></textarea>
                                        <p class="uploader-field-desc"><?php echo $this->__("(Optional) Enter any other information relating to the file(s) you are uploading."); ?></p>
                                    </div>
                                </li>
                                <?php
                                if (Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_TERMS_AND_CONDITIONS_ACCEPTANCE, null)) { ?>
                                    <li class="fields" id="terms-and-conditions">
                                        <label class="required"><em>*</em></em><?php echo $this->__('Terms and Conditions:') ?></label>
                                        <?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_TERMS_AND_CONDITIONS_HTML, null); ?>
                                        <div class="input-box">
                                            <input id="terms-and-conditions-checkbox" type="checkbox" name="terms-and-conditions" class="checkbox required-entry" tabindex="4"/>
                                            <label class="normal" for="terms-and-conditions-checkbox"><?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_TERMS_AND_CONDITIONS_CHECKBOX_LABEL, null); ?></label>
                                        </div>
                                    </li>
                                <?php
                                } ?>
                                <li><p class="required">* <?php echo $this->__("Required fields"); ?></p></li>
                                <li class="fields">
                                    <label for="file-chooser" class="required"><em>*</em><?php echo $this->__('File Upload Queue:') ?></label>
                                    <div id="file-chooser" name="file-chooser">
                                        <div>
                                            <div id="file-upload-queue-header">
                                                <?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_FILE_UPLOAD_QUEUE_HEADER_HTML, null); ?>
                                            </div>
                                            <div id="fileuploader">
                                                <?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_UPLOADER_INIT_FAILURE_HTML, null); ?>
                                            </div>
                                            <div id="file-upload-queue-footer">
                                                <?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_FILE_UPLOAD_QUEUE_FOOTER_HTML, null); ?>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="fields">
                                    <div>
                                        <button class="<?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_UPLOAD_BTN_CSS_CLASS_NAME, null); ?>" onclick="checkDetails()" title="<?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_UPLOAD_BTN_TITLE, null); ?>" type="button" tabindex="6"><span><?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_UPLOAD_BTN_TITLE, null); ?></span></button>
                                    </div>
                                </li>
                            </ul>
                        </fieldset>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    // <![CDATA[

    var theForm = new VarienForm('file-upload-form', true);
    var pendingFilesQueued = 0;

    var chunkSize = '<?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_FILE_CHUNK_SIZE, null); ?>' + 'kb';
    var uploader = jQuery("#fileuploader").pluploadQueue({
        url : '<?php echo $this->getUrl("easyuploader/index/upload") ?>',
        chunk_size : chunkSize,
        filters : {
            <?php /*
            mime_types: [
                { title : "Supported files", extensions : '<?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_ALLOWED_FILE_EXTENSIONS, null); ?>' }
            ]
            */ ?>
            mime_types: [
                { title : "Image files", extensions : '<?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_ALLOWED_FILE_EXTENSIONS, null); ?>' }
            ]
        },
        max_file_size : '<?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_MAX_FILE_SIZE, null); ?>' + 'kb',
        multi_selection : true,
        runtimes : '<?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_RUNTIME_FALLBACK_ORDER, null); ?>',
        flash_swf_url : '<?php echo $flashRuntimeUrl; ?>',
        silverlight_xap_url : '<?php echo $silverlightRuntimeUrl; ?>',
        multipart_params : {},
        multiple_queues : true,
        init : {
            BeforeUpload : function(uploader, file) {
                setInputsState(false);
                checkDetails();
            },
            UploadComplete : function(uploader, files) {
                setInputsState(true);
                var message =   "<?php echo $this->__("SUCCESS: Uploading complete.") ?>" + "\n\n";
                message +=      "<?php echo $this->__("Please check the status of each file to ensure they uploaded successfully.") ?>" + "\n\n";
                message +=      "<?php echo $this->__("TIP: You can add more files to the upload queue and continue uploading if you wish.") ?>";
                alert(message);

                <?php
                if (Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_EMAIL_ENABLE, null)) { ?>
                    jQuery.ajax({
                        'url' : '<?php echo $this->getUrl("easyuploader/index/uploadqueuedidcomplete") ?>',
                        'data' : {
                            'order-number' : jQuery('#order-number').val(),
                            'email-address' : jQuery('#email-address').val()
                        },
                        'type' : 'POST'
                    });
                <?php
                } ?>
            },
            Error : function(uploader, error) {
                var msg;
                switch (error.code) {
                    case -602: // FILE_DUPLICATE_ERROR
                        msg =   "<?php echo $this->__("ERROR:") ?> " + error.message + "\n\n";
                        msg +=  "<?php echo $this->__("Whoops, it looks like you've added the file") ?>";
                        msg +=  " \"" + error.file.name + "\" ";
                        msg +=  "<?php echo $this->__("to the queue already.") ?>";
                        alert(msg);
                        break;
                    default:
                        break;
                }
            },
            FilesAdded : function(uploader, filteredFiles) {
                ++pendingFilesQueued;
            },
            FilesRemoved : function(uploader, filteredFiles) {
                --pendingFilesQueued;
                if (pendingFilesQueued < 0) pendingFilesQueued = 0;
            },
            FileUploaded : function(uploader, file) {
                --pendingFilesQueued;
                if (pendingFilesQueued < 0) pendingFilesQueued = 0;
            }
        }
    });

    function checkDetails() {
        if (theForm.validator.validate()) {
            jQuery.ajax({
                'url' : '<?php echo $this->getUrl("easyuploader/index/checkorder") ?>',
                'data' : {
                    'order-number' : jQuery('#order-number').val(),
                    'email-address' : jQuery('#email-address').val()
                },
                'success' : function(data, textStatus, jqXHR) {
                    var response = JSON.parse(data);
                    switch (response.code) {
                        case <?php echo Aptoplex_EasyUploader_Helper_Data::OK ?>:
                            if (pendingFilesQueued) {
                                //alert(response.message);
                                doUpload();
                            }
                            break;
                        case <?php echo Aptoplex_EasyUploader_Helper_Data::ORDER_NOT_FOUND ?>:
                        case <?php echo Aptoplex_EasyUploader_Helper_Data::UPLOAD_NOT_PERMITTED ?>:
                        case <?php echo Aptoplex_EasyUploader_Helper_Data::UNKNOWN_ERROR ?>:
                            alert(response.message);
                            break;
                        default:
                            break;
                    }
                },
                'type' : 'POST'
            });
        }
    }

    function setInputsState(state) {
        jQuery('#order-number').prop("disabled", !state);
        jQuery('#email-address').prop("disabled", !state);
        jQuery('#additional-comments').prop("disabled", !state);
        jQuery('#file-upload').prop("disabled", !state);
    }

    function doUpload() {
        var queue =  jQuery("#fileuploader").pluploadQueue();
        queue.settings.multipart_params["order-number"] = jQuery('#order-number').val();
        queue.settings.multipart_params["email-address"] = jQuery('#email-address').val();
        queue.settings.multipart_params["additional-comments"] = jQuery('#additional-comments').val();
        queue.start();
    }

    jQuery(function() {

    });

    // ]]>
</script>