<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php $productid=Mage::registry('product')->getId();?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div class="product-view">

	<span itemscope itemtype="http://schema.org/Product">
		<div class="product-essential">
			<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
			<div class="no-display">
				<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
				<input type="hidden" name="related_product" id="related-products-field" value="" />
			</div>
	
			<div class="product-shop">
				<div class="product-name">
						<h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
					
				</div>
				<div class="product_name_custom">
						<h2><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h2>
					<h3><?php $sku = Mage::getModel('catalog/product')->load($_product->getId())->getSku(); echo "Product Model # :"."<span>".$sku."</span>"; ?></h3>
				</div>
				 <?php /*?>   
				<?php if ($this->canEmailToFriend()): ?>
					<p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
				<?php endif; ?>
				
	
				<?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
				<?php */?>
				<?php echo $this->getChildHtml('alert_urls') ?>

				<?php if (Mage::getStoreConfig('grafischdirectrichsnippets/product/price')) : ?>
					<div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
						<meta itemprop="priceCurrency" content="<?php echo $currency_code = Mage::app()->getStore()->getCurrentCurrencyCode(); ?>"/>
						<?php echo $this->getChildHtml('product_type_data') ?>
						<?php echo $this->getTierPriceHtml() ?>
					</div>
				<?php else: ?>
					<?php echo $this->getChildHtml('product_type_data') ?>
					<?php echo $this->getTierPriceHtml() ?>
				<?php endif;?>

				<?php echo $this->getChildHtml('extrahint') ?>
	
				<?php /* if (!$this->hasOptions()):?>
					<div class="add-to-box">
						<?php if($_product->isSaleable()): ?>
							<?php echo $this->getChildHtml('addtocart') ?>
							<?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
								<span class="or"><?php echo $this->__('OR') ?></span>
							<?php endif; ?>
						<?php endif; ?>
						<?php echo $this->getChildHtml('addto') ?>
					</div>
					<?php echo $this->getChildHtml('extra_buttons') ?>
				<?php elseif (!$_product->isSaleable()): ?>
					<div class="add-to-box">
						<?php echo $this->getChildHtml('addto') ?>
					</div>
				<?php endif; */?>

				<?php /*?>
				<?php if (Mage::getStoreConfig('grafischdirectrichsnippets/product/description')) : ?>
					<?php if ($_product->getShortDescription()):?>
						<div class="short-description">
							<h2><?php echo $this->__('Quick Overview') ?></h2>
							<div class="std" itemprop="description">
								<?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
							</div>
						</div>
					<?php endif;?>
				<?php else: ?>
					<?php if ($_product->getShortDescription()):?>
						<div class="short-description">
							<h2><?php echo $this->__('Quick Overview') ?></h2>
							<div class="std">
								<?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
							</div>
						</div>
					<?php endif;?>
				<?php endif;?>
				<?php*/?>

				<?php echo $this->getChildHtml('other');?>
	
				<?php if ($_product->isSaleable() && $this->hasOptions()):?>
					<?php echo $this->getChildChildHtml('container1', '', true, true) ?>
				<?php endif;?>
	
			
	
			<div class="product-img-box">
				<?php echo $this->getChildHtml('media') ?>
			</div>
			     <?php if($_product->getWire_frame() !='')
		{
		   $filePath=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."blfa_files/".$_product->getWire_frame()
	 ?>
            <div class="image-sketch" > <img src="<?php echo $filePath;?>" /> </div>
            <?php } ?>
            <div class="thumbnail_img">
              <ul>
                <?php
              $product = Mage::getModel('catalog/product')->load($productId);//product id here
              foreach ($product->getMediaGalleryImages() as $image) {
              if($image->getPosition()>100 && $image->getPosition()<200)  {
              echo '<li class="'.$image->getPosition().'"><img src="'.$image->getUrl().'" alt =""/></li>';
              //echo $image->getPosition();
              //	var_dump($image);
                }   }     ?>
              </ul>
            </div>
			<?php if (!$this->hasOptions()):?>
				<div class="add-to-box">
					<?php // if($_product->isSaleable()): ?>
						<?php echo $this->getChildHtml('addtocart') ?>
						<?php /*if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
							<span class="or"><?php echo $this->__('OR') ?></span>
						<?php endif; */?>
					<?php //endif; ?>
					<?php //echo $this->getChildHtml('addto') ?>
				</div>
				<?php echo $this->getChildHtml('extra_buttons') ?>
			<?php elseif (!$_product->isSaleable()): ?>
				<div class="add-to-box">
					<?php echo $this->getChildHtml('addto') ?>
				</div>
			<?php endif; ?>
	</div>
			<div class="clearer"></div>

			<?php if ($_product->isSaleable() && $this->hasOptions()):?>
				<?php echo $this->getChildChildHtml('container2', '', true, true) ?>
			<?php endif;?>
			</form>
			<script type="text/javascript">
			//<![CDATA[
				var productAddToCartForm = new VarienForm('product_addtocart_form');
				productAddToCartForm.submit = function(button, url) {
					if (this.validator.validate()) {
						var form = this.form;
						var oldUrl = form.action;
		
						if (url) {
						   form.action = url;
						}
						var e = null;
						try {
							this.form.submit();
						} catch (e) {
						}
						this.form.action = oldUrl;
						if (e) {
							throw e;
						}
		
						if (button && button != 'undefined') {
							button.disabled = true;
						}
					}
				}.bind(productAddToCartForm);
		
				productAddToCartForm.submitLight = function(button, url){
					if(this.validator) {
						var nv = Validation.methods;
						delete Validation.methods['required-entry'];
						delete Validation.methods['validate-one-required'];
						delete Validation.methods['validate-one-required-by-name'];
						// Remove custom datetime validators
						for (var methodName in Validation.methods) {
							if (methodName.match(/^validate-datetime-.*/i)) {
								delete Validation.methods[methodName];
							}
						}
		
						if (this.validator.validate()) {
							if (url) {
								this.form.action = url;
							}
							this.form.submit();
						}
						Object.extend(Validation.methods, nv);
					}
				}.bind(productAddToCartForm);
			//]]>
			</script>
		</div>
		<?php /*?>
		<div class="product-collateral">
			<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
				<div class="box-collateral <?php echo "box-{$alias}"?>">
					<?php if ($title = $this->getChildData($alias, 'title')):?>
					<h2><?php echo $this->escapeHtml($title); ?></h2>
					<?php endif;?>
					<?php echo $html; ?>
				</div>
			<?php endforeach;?>
			<?php */?>
	</span>
			
			<?php echo $this->getChildHtml('product_additional_data') ?>
			<?php echo $this->getChildHtml('upsell_products') ?>
		</div>
		

</div>