<style type="text/css">

.dialog {
    display: block;
    position: absolute;
    width: 1062px !important;
}
</style>

<div id="top_quote_window" class="dialog popup-window">
<div onclick="Windows.close(&quot;top_quote_window&quot;, event)" class="magento_close"></div>
<table class="top table_window" id="top_quote_window_row1">
    <tbody>
        <tr>
            <td class="magento_nw top_draggable"></td>
            <td class="magento_n">
                <div class="magento_title title_window top_draggable" id="top_quote_window_top">Top Quote Window</div>
            </td>
            <td class="magento_ne top_draggable"></td>
        </tr>
    </tbody>
</table>

<table class="mid table_window" id="top_quote_window_row2">
    <tbody>
        <tr>
            <td class="magento_w"></td>
            <td valign="top" class="magento_content" id="top_quote_window_table_content">
                <div class="magento_content" id="top_quote_window_content">
                    <div class="magento_message" id="modal_dialog_message">
<iframe id="iframe" style="margin: 0px !important; background-color: transparent; overflow-y: hidden !important; overflow-x: hidden !important; height:1350px" src="http://tablethrows.com.au/index.php/externalform/?store_id=5" frameborder="0" width="1024" ></iframe>
</div>
</div>
</td>
<td class="magento_e"></td>
</tr>
</tbody>
</table>

<table class="bot table_window" id="top_quote_window_row3">        <tbody><tr>          <td class="magento_sw bottom_draggable"></td>            <td class="magento_s bottom_draggable"><div class="status_bar" id="top_quote_window_bottom"><span style="float:left; width:1px; height:1px"></span></div></td>            <td class="magento_se bottom_draggable"></td>        </tr>      </tbody></table> 

</div>
