<script>
	    jQuery(document).ready(function(){
		//alert("welcome");
		jQuery(".offucial-fac").hide();
	    });
</script><div class="test-image1">
        <ul class="tab-info">
           <li class="tab-li1"><img src="<?php echo $this->getSkinUrl()?>images/step1-quarterprogress.gif" alt="" title="" /></li>
           <li class="tab-li2"><img src="<?php echo $this->getSkinUrl()?>images/step2-none.gif" alt="" title="" /></li>
           <li class="tab-li3"><img src="<?php echo $this->getSkinUrl()?>images/step3-none.gif" alt="" title="" /></li>
           <li class="tab-li4"> <span class="date-info"><?php echo date('F Y'); ?></span><span class="img-cls1"><img src="<?php echo $this->getSkinUrl()?>images/disc5.gif" alt="" title="" /></span></li>
        </ul>   
</div>
<div class="vedio">
	<video height="338" width="600" poster="http://www.durabanners.com.au/qsi/videos/howtocreateartwork-preview.jpg" controls="" title="How To Create Artwork Using The Easy Template Maker for Banners Signs &amp; Flags">
					<source src="http://www.durabanners.com.au/qsi/videos/DBAU-1024x576.mp4" type="video/mp4"></source>
					<source src="http://www.durabanners.com.au/qsi/videos/DBAU-1024x576.ogv" type="video/ogg"></source>
					<source src="http://www.durabanners.com.au/qsi/videos/DBAU-1024x576.webm" type="video/webm"></source>
				</video>
</div>
<div class="artwork-info">
<div class="artwork-cls info-cls">       
        <h1>How To Create Artwork</h1>
        <p class="padcontent"><font color="#1077DD"><b>Step 1.</b></font> Use the <b><a href="#">Easy Template Maker</a></b>.</p>
        <p class="padcontent"><font color="#1077DD"><b>Step 2.</b></font> Design using the Red Line and Blue Line</p>
        <p class="padcontent"><font color="#1077DD"><b>Step 3.</b></font> Flatten your design and upload.</p>
</div>
<div class="artwork-cls1 info-cls">
        <p><b><u>A</u>ll orders have a 'Hem'.</b> </p>
        <p>The Hem is folded over and sewn. To do this, we use large material, print it, cut it and sew it.</p>
        <p>This is called MATERIAL OVER SIZE = <font color="#C40000">M</font>aterial
        <font color="#C40000">O</font>ver <font color="#C40000">S</font>ize</p>
        <p>The MOS is folded under to create your sewn hem. MOS = Material Over Size. This 'over size' is folded and hemmed.</p>
        <p class="img-art"><img border="0" width="600" height="338" alt="Diagram of MOS Material Over Size. A term used when sign companies make banners and flags" src="<?php echo $this->getSkinUrl()?>images/mos-banner-size-guide-MOS.jpg"><br>&nbsp;</p>
</div>
<div class="artwork-cls2 info-cls">						
	<p>The Red Line is your MOS. The Material Over Size will be cut with scissors and folded over. </p>
	<p>The Blue Line is your Finished Order Size. Keep all important elements inside this Blue Line.</p>
	<p class="img-art"><img border="0" width="600" height="338" alt="A design template showing the Red line (outer perimeter of banner material that will be cut withscissors) and the Blue Line of the banne sign" src="<?php echo $this->getSkinUrl()?>images/redbluelines.jpg"></p>
</div>
<div class="artwork-cls3 info-cls">
    <p>Hems, Pole Pockets and Sleeves can all have graphic printing, but these will be folded over. The distance between the Red Line and Blue Line is your hem. Hems may vary in size if a: Pole 
       Pocket size, b: Fitting size or other. Keep in mind that hems 
       can be graphic printing, but they will be folded over.</p>
    <p class="img-art"><img border="0" width="600" height="338" alt="Arrows showing the banner sign material before being folded over" src="<?php echo $this->getSkinUrl()?>images/arrowwraps.jpg"></p>
</div>
<div class="artwork-cls4 info-cls">
    <p>Keep all important elements inside the Blue Line.</p>
    <p>Keep a 'safety area' inside your Blue Line allowing for threading.</p>
    <p class="img-art"><img border="0" width="600" height="338" alt="Illustrative diagram of the banner sign with bottom right page curl showing the hem color and graphics" src="<?php echo $this->getSkinUrl()?>images/bannerwrapcorner.jpg"></p>
</div>
<div class="artwork-cls5 info-cls">
    <p><b>Do not</b> put Crop Marks, Trim Lines, Color Bars or any other information around your MOS. It will print, fold and sew incorrectly. <b><font color="#008000">We do all trim and color controls for you free</font></b>.</p>
    <p class="img-art"><b>Do not</b> put any marks inside or around your file. It 
						will adversely affect our automation and finishing. If you add 
						marks or other stuff, your file may not be successful. Please 
						remember, we do it for you automatically free.</p>
</div>						
<div class="artwork-cls6 info-cls">
        <h3 align="center" class="brown"><i>"<b>Do not</b> use bleed or trim like traditional paper products".</i></h3>				
        <p class="img-art"><img border="0" width="600" height="338" alt="X = Wrong. Do not put any additional marks, colors or information INSIDE OR OUTSIDE your banner design file." src="<?php echo $this->getSkinUrl()?>images/businesscardX.jpg"></p>
</div>
<div class="artwork-cls7 info-cls">
    <p><b>Do not </b>add any Cutting Marks, Further Instructions, Color Bars or any information outside the Red Line.</p>
    <p><br><b>Do not</b> add any Cutting Marks, Further Instructions, Color Bars or any information inside the Red Line.</p>
    <p class="img-art"><img border="0" width="600" height="338" alt="Do not put any marks on the banner design. Work within the Red Line, The Blue line is your finish size of the banner or flag" src="<?php echo $this->getSkinUrl()?>images/canvasX2.jpg"></p>
</div>						
						<p><b>Do not</b> extend the canvas size in any way. Extending 
						the canvas will alter your order size and may print/cut 
						disproportionally.</p>
						
						<p class="img-art">
						<img border="0" width="600" height="338" alt="Crop the canvas to correct MOS size. Do not extend the artistic canvas in any way." src="<?php echo $this->getSkinUrl()?>images/canvasX.jpg"></p>
						
						<p>Crop your files to the correct MOS size. Turn off your Easy 
						Template layer so that you only see your design.</p>
						
						<p class="img-art">
						<img border="0" width="600" height="338" alt="When finished. Turn off the Easy Template Layer so you only see your design." src="<?php echo $this->getSkinUrl()?>images/correctarrow.jpg"></p>
						
						<p>Then, convert-resolve any vector elements, smart layers or 
						font information so that you have a finished file less than 
						150mb at 72dpi.</p>
						
						<p class="img-art">
						<img border="0" width="600" height="338" alt="Flatten your design and upload." src="<?php echo $this->getSkinUrl()?>images/thenflattenY.jpg"></p>
						
						<p>Then, Flatten your design file in CMYK or RGB color mode and 
						upload using the ORDER HERE page on <a href="<?php echo $this->getUrl()?>">
						http://mesh-banners.com.au/</a></p>
						
						<p align="center" class="upperimg"><img alt="Dura Banners" src="<?php echo $this->getSkinUrl()?>images/col-logo.png"></p>
						<p><b>Terms we use...<br>&nbsp;</b></p>
						<p><font color="#0033CC">
						<img align="left" border="0" width="32" height="32" src="<?php echo $this->getSkinUrl()?>images/scissors.png">When we make banner signs for you, 
						we print larger material and trim to size using scissors. 
						This is called MOS.<br>
						&nbsp;</font></p>
						<p><font color="#0033CC">We do not use bleed like traditional 
						paper products. Please do not put crop marks, color bars or any 
						information on your file. Upload the exact MOS size.</font></p>
						<p>&nbsp;</p>
						<p><font color="#0033CC">Do not extend the canvas in anyway. 
						Your files are automatically placed into the printing queue so 
						if you add dimension marks or any additional information it may 
						print disproportionally or misprint.</font></p>
						
						<p><b><font color="#C40000">MOS</font></b> = 
						<font color="#C40000">M</font>aterial <font color="#C40000">O</font>ver 
						<font color="#C40000">S</font>ize = +25 mm is added to all edges. 
						This 'over size' is hemmed.</p>
						<p><b>HEM</b> = Folded &amp; Sewn edges. Like a Shirt, edges are 
						tucked under &amp; sewn.</p>
						<p><b>Pole Pocket</b> = Hang with a pole or rod.<b><br>
						Finished Order Size</b> = The <u>F</u>ront <u>S</u>ide 
						dimensions of the banner ordered.</p>
						<p><b>Safety Area</b> = Keep all critical graphics and text 
						away from hem edges.<br>
						<b>Bleed</b> = Color to the edge of MOS</p>
						<p><b>DPI</b> = Dots per inch = 72dpi at FULL SIZE</p>
						<p><b>FULL SIZE</b> = Design your files at <i> <u>One</u> to <u>One</u> 
						size.</i> eg. 15000 x 800 mm @72dpi = 15m x .8m</p>
						<p><b>Save As</b> =&nbsp; .pdf</p>
						<p><b>Color Mode</b> = RGB <u>o</u>r CMYK</p>
						
						
						
						
						<p align="center" class="bottom">
							<img alt="Dura Banners" src="<?php echo $this->getSkinUrl()?>images/col-logo.png"><br>
						</p>
						<p>Ready to order? Please proceed here.</p>
						<h2 class="top-links"><a href="<?php echo $this->getUrl()?>calculators">Order Here</a></h2>
                                                
</div>                                                
					    