<div class="test-image"><img src="<?php echo $this->getSkinUrl()?>images/tab.jpg" alt="" title="" /></div>
<div class="home-body">
    <div class="banner-img">
        <img border="0" width="620" height="360" alt="The official factory DuraBanners Website Image Banner spread around the factory drying making signage" src="<?php echo $this->getSkinUrl()?>images/durabanners-1.jpg">
    </div>
   <div class="banner-content">
        <h1>Banner Signs Ordering For Wholesalers and Designers</h1>
        <p>
        We supply sign companies, printers, advertising agencies, 
        marketing managers, event management companies and trade 
        printing wholesale mesh banner signs direct around the world 
        twice everyday. <b>If you want to know where that big event signage or banner down the street comes from...</b><span class="brown"> it's probably from us.</span> Trade &amp; Wholesale clients are kept confidential to benefit their business.</p>
   </div>
    <div class="banner-img">
   <img border="0" width="620" height="360" alt="Two factory women banner signs" src="<?php echo $this->getSkinUrl()?>images/durabanners-2.jpg"></p>
    </div>
    <div class="middle-home-menus-img">
    <ul>
	<li>
	    <a href="#" title="The fastest calculator in the world, you can quickly price all the options your banner signs here. Shows banner sign options, dimensions, shipping, discounts and large order discounts too."><img width="140" height="180" src="<?php echo $this->getSkinUrl()?>images/stage1.png"></a>
	    <span><a href="#">Prices and Options</a></span>
	</li>
	<li>
	    <a href="#" title="Terrific page helping customers make artwork ready to upload directly to the printing machine. Easy to use step by step and handy references"><img width="140" height="180" src="<?php echo $this->getSkinUrl()?>images/stage2.png"></a>
	<span><a href="#">Art &amp; Design Help</a></span></li>
	<li><a href="#" title="View your banner sign size dimensions in real time and make your previews and proofing easy. The MOS Live Template suits all options and generates your draft proofs quickly."><img width="140" height="180" src="<?php echo $this->getSkinUrl()?>images/stage3.png"></a>
	    <span><a href="#">Previews &amp; Proofing</a></span>
	</li>
	<li>
	    <a href="#" title="The fastest calculator in the world, you can quickly price all the options your banner signs here. Shows banner sign options, dimensions, shipping, discounts and large order discounts too."><img width="140" height="180" src="<?php echo $this->getSkinUrl()?>images/stage4.png"></a>
	    <span><a href="#">Factory Photos &amp; Examples</a></span>
	</li>
	<li>
	    <a href="#" title="The fastest calculator in the world, you can quickly price all the options your banner signs here. Shows banner sign options, dimensions, shipping, discounts and large order discounts too."><img width="140" height="180" src="<?php echo $this->getSkinUrl()?>images/stage5.png"></a>
	    <span><a href="#">Currencies &amp; Locations</a></span>
	</li>
	<li>
	    <a href="#" title="The fastest calculator in the world, you can quickly price all the options your banner signs here. Shows banner sign options, dimensions, shipping, discounts and large order discounts too."><img width="140" height="180" src="<?php echo $this->getSkinUrl()?>images/stage6.png"></a>
	    <span><a href="#">Shipping &amp; Tracking</a></span>
	</li>
    </ul>
    </div>
    
     <div class="bottom-home-content">
	<h2>Easy to order you can check every stage</h2><br>
                            <p>No login is required. Order your cheap banner signs online for any location in the world direct from our factory website.</p><p>Purchase your trade wholesale banners for any location. No account is required and you can follow all progress stages at anytime. We supply signwriters, sign painters graphic designers advertising agencies builders event managers event signage contractors and much more direct... now you can too!</p>
     </div>
   
	<div class="total-arrow">
	    <a class="left_arr_custom" href="javascript:window.history.back();"><img border="0" width="112" height="104" src="<?php echo $this->getSkinUrl()?>images/arrow-left.png"></a>
	    <a class="right_arr_custom" href="#"><img border="0" width="112" height="104" alt="Banner Sign Design help and information" src="<?php echo $this->getSkinUrl()?>images/arrow-right.png"></a>
	</div>
            
</div>
