<?php
$files=Mage::getModel('downloads/files')->getCollection()
   ->addFieldToFilter('store_ids',array('finset'=>'16'))->setOrder('category_id', 'DESC')->setOrder('name','ASC');

foreach($files as $file){

	$catid=$file->getCategoryId();
	if(!$catid) continue;
	if($precat != $catid){
		$catModel=Mage::getModel('downloads/categories')->load($catid);
		$catname=$catModel->getTitle();
		echo '<h1>'.$catname.'</h1>';

		if($precat != "")
                        echo '</table>';


			echo '<table width="100%" cellpadding="0" cellspacing="0" style="border: 0;
border-collapse: collapse;
border-spacing: 0;
empty-cells: show;
font-size: 100%;">';

	echo '<tr><td style="text-align: center; font-family: Arial, Helvetica, sans-serif; color: #464646; font-size: 10px;">
		ART WORK FILES
	</td></tr>';
	echo '<tr><td style="text-align: center; font-family: Arial, Helvetica, sans-serif; color: #464646; font-size: 10px;">
		<a title="'.$filename.'" href="/download/dl/file/id/'.($file->getFileId()).'/'.$file->getFilename().'" target="_blank">'.$file->getName().'</a>
	</td></tr>';

	$precat=$catid;
	
	}
}
echo '</table>';
