<div class="home-page-cms-content">
   <div class="page_detail">
      <div class="left_detail">
      <img src="<?php echo $this->getSkinUrl(); ?>images/we_accept.png" alt="We Accept Banner"  />
      <img style="margin-top:10px;" src="<?php echo $this->getSkinUrl(); ?>images/sale.png" alt="We Accept Banner"  />
      
      </div>
      <div class="right_detail">
      <div class="content">

                                <h1>Our History</h1>

                                <div class="para_txt">
                                <h3>Popup Stands, Popup Displays and Portable Display Stands</h3>

                                    <p>Popupstands.com specialise in supplying Popup stands and related exhibition equipment including roller banner / pullup stands. We are a large volume supplier of Popup displays and can therefore provide the most competitive prices for Popup displays in the exhibition and event industry. Our Popup stand quality standards are second to none and are backed by a 10 year warranty on our traditional Popup stands and a lifetime warranty on our Elite Cross Braced Popup stands.
 </p>

                        
                                <h3>Popup Stands Equipment</h3>
                                    <p>All exhibition stands including Popup stands, and exhibition accessories are produced by Ultima Displays and Abex Displays. Ultima Displays are the market leader in Popup stands and supply high quality exhibition display hardware backed up by a 10 year warranty. We can supply Popup stand printed graphics from a wide range of suppliers including Ultima Displays, Abex Displays, Nomadic, Nimlok, Eurostand, Expand Displays, Easy Stands plus many more. Why not ask us the question and I am sure we have a solution for your exhibition.
</p>

                                    
									<h3>Exhibition Stands Made Simple</h3>
                                    <p>All our Popup stands are a pre-set size, but can also be linked to form larger Popup displays with varying shapes. Simply complete our Popup order form, send us your stand artwork and we will do the rest.
</p>

<h3>Popup stands and exhibition stands can be erected in a matter of minutes with no tools, no exhibition contractor or huge transport or storage required.</h3>
                                    

                                     
                                      

                                </div>
                                
                        </div>
      </div>
   <div class="bottom_banner">
   <img src="<?php echo $this->getSkinUrl(); ?>images/banner_bottom.png" alt="We Accept Banner"  />
   </div>
   </div>
    

</div>