<div class="home-page-cms-content">
    <table width="100%" cellspacing="0" cellpadding="0" border="0">
        <tbody>
            <tr>
                <td width="321" class="home-page-left">
                   <div class="menu2">
                               <ul>
                                       <li><img src="<?php echo $this->getSkinUrl(); ?>images/icon-price.png" alt=""><span class="txt"><span class="find-heading">Low Price Guarantee</span><br>We are happy to beat the price of our competitors</span></li>
                                   <li><img src="<?php echo $this->getSkinUrl(); ?>images/icon-shipping.png" alt=""><span class="txt"><span class="find-heading">Reliable &amp; Fast Shipping</span><br>Make sure you get your product on time. We deliver Australia-Wide.</span></li>
                                   <li><img src="<?php echo $this->getSkinUrl(); ?>images/icon-setup.png" alt=""> <span class="txt"><span class="find-heading">Easy setup Process</span><br>We’re here to help with setup if you need it</span></li>
                                   <li><img src="<?php echo $this->getSkinUrl(); ?>images/icon-guarantee.png" alt=""><span class="txt"><span class="find-heading">Money Back Guarantee</span><br>We want our customers happy</span></li>
                               </ul>
                           </div> 
                    <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('bottom_left_content')->toHtml() ?>
                </td>
                <td class="home-page-right">
                                            <div class="content">
                                <h1>About Our Products</h1>
                                <div class="para_txt"> High impact, professional presentation: Mesh  Banners are the most widely used signs on construction sites, builder&rsquo;s  projects and event fencing.&nbsp; They are an ideal way to promote the business  in a cost effective manner. We are the manufacturers of Mesh Banners in Australia.  We supply Mesh Banners including Construction Mesh Banners, Builder Mesh  Banners and Fence Mesh Banners to hundreds of retailers, construction and  builders sites Australia Wide.<br>
                                  <br>
                                  Construction and Building Site fences are the perfect opportunity to  introduce your company to the public &amp; we want to help you with your image  design. We have a huge selection of Fence Mesh Signs, Events Mesh Signs and  Construction Builders Mesh Banners and Signs to get you up and running. Here is  everything you need to get noticed, creating successful sales opportunities.  Make an impression with an interchangeable graphic board or banner poles.                                  <br>
                                  <br>
                                  <a href="http://Mesh-Banners.com.au" target="_blank">Mesh-Banners.com.au</a> is  Australia's choice to buy custom made mesh banners and signs Factory Direct! We  also have an established banner graphic and design department to take care of  your graphic designing job in a professional manner. So call now to find out  how we can brand your site with vivid colors today! 
<p class="learn_more" style="display:none;">
                <button class="button" title="Learn More" type="submit" onClick="setLocation('about-us')"><span><span>Learn More</span></span></button>
                                     </p>
                                      
                                </div>
                        </div>

                    
                   <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('bottom_right_content')->toHtml() ?>
                </td>
            </tr>
        </tbody>
    </table>
</div>