<?php 
		/*auto complete change url*/
		
		
?>
<div style="min-height:385px; height:485px; width:220px; overflow:auto;">
<ul>

<?php 
 $i=0;

foreach ($items as $item): ?>
   
   <?php 
   		/*if item type is a Product  */		
		if($item['type']=='Product'){
			
			/*get product id*/
			$_product_id = explode('/',$item['id']);
			$_product_id =$_product_id[2];
			$_product = Mage::getModel('catalog/product')->load($_product_id);			
			$url_path = $_product->getUrl_path();
			
			$_category_ids = $_product->getCategoryIds();
			$_website_ids =$_product->getWebsiteIds() ;
			
			$_category = Mage::getModel('catalog/category')->load($_categories[$i]);
   			$url = $_category->getUrlPath().$_product->getUrlPath();
			
			
				
			
			if($_website_ids[$i]!=19 ){	
			
			$_website_obj =  Mage::app()->getWebsite($_website_ids[$i]);
			
			$_website_url = $_website_obj->getName();			
			
			 // echo $_website_ids[$i];
			//  echo $_website_url;
			 
			
			// $storeIds = Mage::getModel('core/website')->load($_website_ids[$i])
                           // ->getStoreIds(); 
			
			  $_store_ids = $_website_obj->getStoreIds();
			  $_store_id = implode($_store_ids);
			  
			 		 				
			//print_r($_website_obj->getName());
			if($_website_url!='Admin'){	
		?>	
			<!--<li id="<?php echo $_product_id ?>" url="<?php echo $item['url'] ?>">-->
			
			<li >
				<div style="height:140px; ">
        <a href="<?php echo $_website_url.'/'.$item['url_path'];?>" target="_blank">
		<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(40, 40);?>" width="40" height="40" style="border:1px solid #ccc; width:40px; height:40px; margin-right:3px;"  align="left"/>
		
        <strong><?php echo $this->htmlEscape($item['name']) ?></strong>	
		<div style="float:right; color:red; font-weight:bold;">[<?php echo $item['type'] ?>]</div>
         </a>
		 
		 <div class="leftLabel"><b>Price:</b> $ <?php echo round($_product->getPrice(),2,PHP_ROUND_HALF_DOWN);?>  <span><b>Special:</b> $ <?php echo round($_product->getSpecial_price(),2,PHP_ROUND_HALF_DOWN);?></span></div>
        <div class="leftLabel"><b>Stock:</b> <?php  echo round($_product->getQty(),0); ?> </div>
        <div class="leftLabel" style="font-size:9px;"> 
		<b>Model #:</b>
		<?php echo $this->htmlEscape($item['store']) ?>
		<?php echo $_store_id.'-'.$item['sku'];?>	</div>
        <hr/>
        </div>
    		</li>
		<?php	
			  }
			}
					$i++;
			
			}else{
    ?>
    <li id="<?php echo $item['id'] ?>" url="<?php echo $item['url'] ?>">
        <div style="float:right; color:red; font-weight:bold;">[<?php echo $item['type'] ?>]</div>
        <strong><?php echo $this->htmlEscape($item['name']) ?></strong><br/>
        <span class="informal"><?php echo $this->htmlEscape($item['email']) ?></span>
        <span class="informal"><?php echo $this->htmlEscape($item['store']) ?></span>

    </li>
   
    <?php 
			}
		
    ?>
<?php endforeach ?>
</ul>
<?php 

?>
</div>

	<style>
	<!--
	  .leftLabel{font-size:10px; padding-left:5px;}
	  .thumb{  }
	
	-->
	</style>