<?php
/**
 * Template uploaderlink.phtml
 *
 * @author Aptoplex
 * @copyright 2015 Aptoplex   
 *  
 * @var $this Aptoplex_EasyUploader_Block_UploaderLink
 */

$uploadButtonTitle = Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_CHECKOUT_SUCCESS_UPLOAD_BTN_TITLE);
if (!isset($uploadButtonTitle)) $uploadButtonTitle = 'Upload Your Files';

$uploadButtonClassName = Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_CHECKOUT_SUCCESS_UPLOAD_BTN_CSS_CLASS_NAME);
if (!isset($uploadButtonClassName)) $uploadButtonClassName = 'btn-upload';

$targetUrl = $this->getUrl() . Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_UPLOADER_URL, null);

?>

<style>
    #artwork-upload-section {
        margin-top: 40px;
    }

    #uploader-buttons {
        margin-top: 20px;
    }
</style>

<div id="artwork-upload-section">
    <?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_CHECKOUT_SUCCESS_MAIN_HTML); ?>
    <div id="uploader-buttons">
        <button class="<?php echo $uploadButtonClassName ?>" onclick="window.location='<?php echo $targetUrl ?>'" title="<?php echo $uploadButtonTitle ?>" type="button"><span><?php echo $uploadButtonTitle ?></span></button>
    </div>
</div>