<?php
/**
 * Checkout success template
 *
 * Replaces: app/design/frontend/base/default/template/checkout/success.phtml
 *
 * @author Aptoplex
 * @copyright 2015 Aptoplex
 *
 * @var $this Mage_Checkout_Block_Onepage_Success
 */
   
$uploadButtonTitle = Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_CHECKOUT_SUCCESS_UPLOAD_BTN_TITLE);
if (!isset($uploadButtonTitle)) $uploadButtonTitle = 'Upload Your Files';

$uploadButtonClassName = Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_CHECKOUT_SUCCESS_UPLOAD_BTN_CSS_CLASS_NAME);
if (!isset($uploadButtonClassName)) $uploadButtonClassName = 'btn-upload';

$targetUrl = $this->getUrl() . Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_UPLOADER_URL, null);

$form_key =  Mage::getSingleton('core/session')->getFormKey();
$targetUrl .='/index/index/order_id/'.$this->getOrderId().'/form_key/'.$form_key;

?>

<style>
    #artwork-upload-section { margin-top: 40px; }
    #uploader-buttons { margin-top: 20px; }
</style>

<div class="page-title">
    <h1><?php echo $this->__('Your order has been received.') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h2>

<?php if ($this->getOrderId()):?>
    <?php if ($this->getCanViewOrder()) :?>
        <p><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></p>
    <?php  else :?>
        <p><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?></p>
    <?php endif;?>
    <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
    <?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
        <p>
            <?php echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $this->getPrintUrl()) ?>
            <?php echo $this->getChildHtml() ?>
        </p>
    <?php endif;?>
<?php endif;?>

<?php if ($this->getAgreementRefId()): ?>
    <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
<?php endif;?>

<?php if ($profiles = $this->getRecurringProfiles()):?>
    <p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
    <ul class="disc">
        <?php foreach($profiles as $profile):?>
            <?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
            <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
        <?php endforeach;?>
    </ul>
<?php endif;?>

<div id="artwork-upload-section">
    <?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_CHECKOUT_SUCCESS_MAIN_HTML); ?>
    <div id="uploader-buttons">
        <button class="<?php echo $uploadButtonClassName ?>" onclick="window.location='<?php echo $targetUrl ?>'" title="<?php echo $uploadButtonTitle ?>" type="button"><span><?php echo $uploadButtonTitle ?></span></button>
    </div>
</div>

<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>
