<div class="home-page-cms-content">

    <table width="100%" cellspacing="0" cellpadding="0" border="0">

        <tbody>

            <tr>

                <td width="321" class="home-page-left">

                   <div class="menu2">

                               <ul>

                                       <li><img src="<?php echo $this->getSkinUrl(); ?>images/icon-price.png" alt=""><span class="txt"><span class="find-heading">Low Price Guarantee</span><br>We are happy to beat the price of our competitors</span></li>

                                   <li><img src="<?php echo $this->getSkinUrl(); ?>images/icon-shipping.png" alt=""><span class="txt"><span class="find-heading">Reliable &amp; Fast Shipping</span><br>Make sure you get your product on time. We deliver Australia-Wide.</span></li>

                                   <li><img src="<?php echo $this->getSkinUrl(); ?>images/icon-setup.png" alt=""> <span class="txt"><span class="find-heading">Easy setup Process</span><br>We’re here to help with setup if you need it</span></li>

                                   <li><img src="<?php echo $this->getSkinUrl(); ?>images/icon-guarantee.png" alt=""><span class="txt"><span class="find-heading">Money Back Guarantee</span><br>We want our customers happy</span></li>

                               </ul>

                           </div> 

                    <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('bottom_left_content')->toHtml() ?>

                </td>

                <td class="home-page-right">

                                            <div class="content">

                                <h1>About Our Products</h1>

                                <div class="para_txt">

                                    <p>High impact, professional presentation: With only a fleeting moment to attract the attention of a trade show attendee, your exhibit must appeal to your target audience's interests. Your display must effectively communicate who you are, what you do and how your company can help them. We can help you with our promotion, advertising and marketing displays &amp; equipments. We sell cheap and affordable high quality products directly to consumers. </p>

                        

                                    <p>Exhibitions and conventions are the perfect opportunity to introduce your company to the public &amp; we want to help you with your image design. We have a huge selection of Tradeshow Exhibits, Media Wall, Tradeshow Banner Stands, Accessories, Pop Up Booths,  Portable Exhibits &amp; presentation boards. Here is everything you need to get noticed, creating successful sales opportunities. Make an impression with an interchangeable graphic board or banner poles.</p>

                                    

                                    <p>Vivid Ads (Creative Advertising &amp; Display Solutions) is Australia's choice to buy In-Stock exhibit stands, fabric mural media backdrop walls, expo booth displays, road show displays, trade fair booths (exhibit / expo) equipments and interactive / interactivity display screens. We also have a established banner graphic and design department to compliment your display banner stands.</p>

                                    

                                     <p class="learn_more">

                                        <button class="button" title="Learn More" type="submit" onClick="setLocation('about-us')"><span><span>Learn More</span></span></button>

                                     </p>

                                      

                                </div>

                        </div>



                    

                   <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('bottom_right_content')->toHtml() ?>

                </td>

            </tr>

        </tbody>

    </table>

</div>
