<?php if(Mage::getStoreConfig('catalog/schema/enable')): ?>
	<?php if(Mage::getStoreConfig('catalog/schema/wrap')): ?>
		<div class="hide-rich-snippets" style="display:none;">
	<?php endif ?>
		<?php 
			$_product = $this->getProduct(); 				
		?>
  <div itemscope itemtype="http://schema.org/Product" style="display:none;">
  <span itemprop="name"><?php echo $_product->getName(); ?></span>
  <img src="<?php echo $this->getNonCachedImage($_product); ?>" alt="<?php echo $_product->getName(); ?>" />
  
  
     
  
  <div itemprop="aggregateRating"
    itemscope itemtype="http://schema.org/AggregateRating">
      <span itemprop="worstRating" >1</span>       
      <span itemprop="bestRating">10</span>stars
   Rated <span itemprop="ratingValue">10</span>/10
   based on <span itemprop="reviewCount">1568</span> customer reviews
  </div>
  <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
  <link itemprop="itemCondition" href="http://schema.org/NewCondition"/>Previously owned,
      in excellent condition 
  <link itemprop="availability" href="http://schema.org/InStock"/>In stock! Order now!
    <!--price is 1000, a number, with locale-specific thousands separator
    and decimal mark, and the $ character is marked up with the
    machine-readable code "USD" -->
    <span itemprop="priceCurrency" content="<?php echo $this->getCurrencyCode(); ?>"><?php echo $this->getCurrencyCode(); ?></span>
    <span itemprop="price" content="<?php echo $_product->getSpecial_price(); ?>">  <?php echo $_product->getSpecial_price(); ?></span>
    <link itemprop="availability" href="http://schema.org/InStock"/>In stock</div>
  Product description:
  <span itemprop="description"><?php echo $this->getProductDescription($_product); ?></span>
  Customer reviews:
  <div itemprop="review" itemscope itemtype="http://schema.org/Review">
    <span itemprop="name"><?php echo $_product->getName(); ?></span> -
    by <span itemprop="author"><?php echo 'Vividads Pty Australia'; ?></span>,
    <meta itemprop="datePublished" content="<?php echo $_product->getCreated_at();?>">April 1, 2011
    <div itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
      <meta itemprop="worstRating" content = "1">
      <span itemprop="ratingValue">10</span>/
      <span itemprop="bestRating">10</span>stars
    </div>
    <span itemprop="description"><?php echo $this->getProductDescription($_product); ?></span>
  </div>
  
 
</div>
		<div itemscope itemtype="http://schema.org/Product">        
       		<meta itemprop="name" content="<?php echo $_product->getName(); ?>" />
            <meta itemprop="sku" content="<?php echo $_product->getSku(); ?>" />
            <meta itemprop="image" content="<?php echo $this->getNonCachedImage($_product); ?>" />
            <meta itemprop="logo" content="<img src='<?php echo $this->getLogoSrc() ?>' alt='<?php echo $this->getLogoAlt(); ?>'" /> 
			<meta itemprop="description" content="<?php echo $this->getProductDescription($_product); ?>" />
            
		
			<div itemtype="http://schema.org/AggregateRating" itemscope itemprop="aggregateRating">
				<?php $review = $this->getReviewSummary(); ?>
				<meta itemprop="worstRating" content="1">
				<meta itemprop="bestRating" content="10">
				<meta itemprop="ratingValue" content="10/10<?php // echo $review->getRatingSummary()/10; ?>">
				<meta itemprop="reviewCount" content="1568<?php // echo $review->getReviewsCount(); ?>">
			</div>
		
			<div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
		        <meta itemprop="priceCurrency" content="<?php echo $this->getCurrencyCode(); ?>" />
		    	<meta itemprop="price" content="<?php echo $this->getProductPrice(); ?>" />
		    	<?php if($_product->isSaleable()): ?>
		    		<link itemprop="availability" href="http://schema.org/InStock" />
		    	<?php endif ?>
		  	</div>
		</div>
        
        
	<?php if(Mage::getStoreConfig('catalog/schema/wrap')): ?>
		</div>
        
		<style>
			.hide-rich-snippets {display:block;}
		</style>
	<?php endif ?>
<?php endif ?>