
<?php

$product = Mage::registry('current_product');
    
    // load an other block "AskQuestionForm"
    $url = $this->getUrl('CrmTicket/Front_Ticket/NewTicket', array('product_id' => $product->getId()));
    $productName = str_replace("'"," ",$product->getName());
    $productName = str_replace('"'," ",$product->getName());
    $onclick = "'".$url."','".$productName."'";
?>

&nbsp;<?php /*?><button type="button" title="<?php echo $this->__('Ask a question'); ?>" class="button" onclick="setLocation('<?php echo $this->getUrl('contact-us') ?>');"><span><span><?php echo $this->__('Ask a question'); ?></span></span></button><?php */?>
