<?php /*?><div class="home-page-cms-content">
    <table width="100%" cellspacing="0" cellpadding="0" border="0">
        <tbody>
            <tr>
                
                <td class="home-page-right">
                                            <div class="content">
                                <h1>Why Choose Us</h1>
                                <div class="para_txt">
                                    <p><strong style="font-size:14px;">The Expo Booth's Difference</strong></p><br />
                                    <p>Not every company can lay claim to extensive experience in the trade show product and preparation industry. Expo Booth's brings over ten years of experience and service since foundation to bear on the needs of each customer. Each representative employed by Expo Booth's is an experienced professional ready to work towards the customer’s success. <br /></p><br /><br />
                                    <p>The experience brought forward is more than just physical products and sales. Expo Booth's offers experience in trade show planning and logistics, design and production, as well as installation and dismantling.  Sales is but a small part of the entire offering that is available to a potential customer. Part of the Expo Booth's difference is working to be there for the customer every step of the way.</p>
                                    
                                     <p class="learn_more">
                                        <button class="button" title="Learn More" type="submit" onclick="setLocation('about-us')"><span><span>Read More</span></span></button>
                                     </p>
                                      
                                </div>
                        </div>

                    
                   <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('bottom_right_content')->toHtml() ?>
                </td>
            </tr>
        </tbody>
    </table>
</div><?php */?>
<div class="home-page-cms-content">
		<div class="home-page-right">
        	                      <div class="content">
                                <h1>Why Choose Us</h1>
                                <div class="para_txt">
                                    <p><strong style="font-size:14px;">The Expo Booth's Difference</strong></p><br />
                                    <p>Not every company can lay claim to extensive experience in the trade show product and preparation industry. Expo Booth's brings over ten years of experience and service since foundation to bear on the needs of each customer. Each representative employed by Expo Booth's is an experienced professional ready to work towards the customer’s success. </p>
                                    <p>The experience brought forward is more than just physical products and sales. Expo Booth's offers experience in trade show planning and logistics, design and production, as well as installation and dismantling.  Sales is but a small part of the entire offering that is available to a potential customer. Part of the Expo Booth's difference is working to be there for the customer every step of the way.</p>
                                    
                                     <p class="learn_more">
                                        <button class="button" title="Learn More" type="submit" onclick="setLocation('about-us')"><span><span>Read More</span></span></button>
                                     </p>
                                      
                                </div>
                        </div>
        
        </div>
	
		</div>
<div class="homepage-banners">
	<img src="<?php echo $this->getSkinUrl()?>images/buy_online.jpg" id="first" alt="Buy Online" />
	<img src="<?php echo $this->getSkinUrl()?>images/send_artwork.jpg" alt="Send us Your Artwork" />
</div>