<style>
<!--
.uploader_artwork {
	display: none;
}
.contacts_button {
	display: none;
}
#livechat-full {
	display: none;
}
.main-container {
	background: none repeat scroll 0 0 #fff;
}
.row {
	margin: 0 auto;
	width: 1040px;
}
.col1-layout .col-main {
	margin: 0 0 0 0px;
	width: 1000px;
}
.alphacube_buttons {
    text-align: center;
    width: 100%;
    display: none;
}
.alphacube_content {
    background: none repeat scroll 0 0 #fdfdfd;
    color: #000;
    font: 12px arial;
    overflow: auto;
    width: 1000px !important;
}
.addthis_toolbox {
	display: none;
}
-->
</style>
  <iframe src='http://usedbooths.com.au/index.php/externalform/?store_id=166' height='850' width='930'>

  </iframe>
