<?php
 $myStatus = Mage::getSingleton('customer/session')->isLoggedIn();
?>
<div class="cartrigt">
    
    <div class="acchding">
        <h1>Account</h1>
    </div>
    <ul class="accinfolnk">
        <?php
        if(!$myStatus)
        {
    ?>
        <li>
            <a href="<?php echo $this->getUrl();?>customer/account/login">Login / Register</a>
        </li>
        <li><a href="<?php echo $this->getUrl();?>customer/account/forgotpassword">Forgotten Password</a></li>
        <?php
        }
        else
        {
        ?>
        
        <li><a href="<?php echo $this->getUrl();?>customer/account">My Account</a></li>
        <li><a href="<?php echo $this->getUrl();?>customer/address">Address Books</a></li>
        <li><a href="<?php echo $this->getUrl();?>wishlist">Wish List</a></li>
        <li><a href="<?php echo $this->getUrl();?>sales/order/history">Order History</a></li>
        <li><a href="<?php echo $this->getUrl();?>downloadable/customer/products">Downloads</a></li>
        <li><a href="<?php echo $this->getUrl();?>ProductReturn/Front/List">Returns</a></li>
        <li><a href="">Transactions</a></li>
        <li><a href="<?php echo $this->getUrl();?>newsletter/manage">Newsletter</a></li>
        <?php
        }
        ?>
    </ul>
</div>