<?php

    $quote_id = $this->getRequest()->getParam('quote_id');
    $quote = Mage::getModel('Quotation/Quotation')->load($quote_id);

?>
   <div class="maindiv">
        <div class="tabletask">
            <form id="edit_form_task_" name="edit_form_task_">
    <input type="hidden" id="ot_id" name="ot_id" value="">
    <input type="hidden" id="ot_entity_type" name="ot_entity_type" value="quote">
    <input type="hidden" id="ot_created_date" name="ot_created_date" value="">
    <input type="hidden" id="ot_entity_id" name="ot_entity_id" value="<?php echo $quote_id;?>">
    <input type="hidden" id="ot_entity_description" name="ot_entity_description" value="<?php echo 'Quotation #'.$quote->getincrement_id()?>">
    <input type="hidden" id="ot_event" name="ot_event"  >
    <input id="form_key" name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    <div style="margin-left: 30px; margin-top: 66px;" "="" id="div_edit_task_">

        <fieldset id="my-fieldset">
            <table cellspacing="0" border="0">
                <tbody><tr>
                    <td class="label" width="18%">Entity</td>            	
                    <td class="input-ele" colspan="3">
                        <?php echo 'Quotation #'.$quote->getincrement_id()?>
                    </td>
                    <td>Created at  </td>
                    <!--<td colspan="3" align="right">
                            <button onclick="SubmitForm('', '1');" class="scalable save" type="button"><span>Save</span></button>
                        </td>-->
                    </tr>
                    <tr>
                        <td class="label" width="16%">Author</td>
                        <td class="input-ele" width="16%">
                        <select name="ot_author_user" id="ot_author_user">
                            <?php
                                $adminUserModel = Mage::getModel('admin/user');
                                $userCollection = $adminUserModel->getCollection()->load();
                                foreach($userCollection as $user)
                                {
                                    echo '<option value="'.$user->getId().'" '.$selected.'>'.$user->getUsername().'</option>';
                                }
                            ?>
                        </td>
                        <td class="label" width="16%">Notification Date</td>
                        <td class="input-ele" width="16%">
                            <input size="6" type="text" id="ot_notify_date" name="ot_notify_date" value="">
                            <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif');?>" class="v-middle" id="img_ot_notify_date">
                            <script type="text/javascript">
                                Calendar.setup({
                                    inputField : document.getElementById('edit_form_task_').elements['ot_notify_date'],
                                    ifFormat : '%Y-%m-%e',
                                    button : document.getElementById('edit_form_task_').elements['img_ot_notify_date'],
                                    align : 'Bl',
                                    singleClick : true
                                });
                            </script>
                        </td>
                        <td class="label" width="16%">Priority</td>
                        <td class="input-ele" width="16%" colspan="3"><select name="ot_priority" id="ot_priority"><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option></select></td>
                    </tr>
                    <tr>
                        <td class="label" width="16%">Target</td>
                        <td class="input-ele" width="16%">
                            <select name="ot_target_user" id="ot_target_user">
                                <option value=""></option>
                                 <?php
                                    $adminUserModel = Mage::getModel('admin/user');
                                    $userCollection = $adminUserModel->getCollection()->load();
                                    foreach($userCollection as $user)
                                    {
                                        echo '<option value="'.$user->getId().'" '.$selected.'>'.$user->getUsername().'</option>';
                                    }
                                ?>
                            </select>                                                        <input type="checkbox" value="1" name="notify_target" id="notify_target"> Notify                            </td>
                            <td class="label" width="16%">Dead line</td>
                            <td class="input-ele" width="16%">
                                <input size="6" type="text" id="ot_deadline" name="ot_deadline" value="">
                                <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif');?>" class="v-middle" id="img_ot_deadline">
                                <script type="text/javascript">
                                    Calendar.setup({
                                        inputField : document.getElementById('edit_form_task_').elements['ot_deadline'],
                                        ifFormat : '%Y-%m-%e',
                                        button : document.getElementById('edit_form_task_').elements['img_ot_deadline'],
                                        align : 'Bl',
                                        singleClick : true
                                    });
                                </script>
                            </td>
                            <td class="label" width="16%">Complete</td>
                            <td class="input-ele" width="16%"><input type="checkbox" value="1" id="ot_finished" name="ot_finished"></td>
                            <td class="label" width="16%"><?php echo $this->__('Task Type');?></td>
                            <td class="label" width="16%">
                                <select name="ot_type" id="ot_type">
                                    <option value="">Select Task Type</option>
                                    <option value="Chain" >Chain</option>
                                    <option value="Independent" >Independent</option>
                                </select>
                            </td>
                </tr>
                    <?php

                        $ItemCollection = $quote->getItems();
                   
                    ?>       
                <tr>
                    <td class="label" width="16%"><?php echo $this->__('Product'); ?></td>
                    <td class="input-ele" colspan="7">
                        <select name="ot_item" id="ot_item">
                            <option value="">Select Item</option>
                            <?php
                                foreach($ItemCollection as $items)
                                {
                                    $_newProduct = Mage::getModel('catalog/product')->load($items->getProductId());
                                    echo '<option value="'.$items->getProductId().'">'.$_newProduct->getName().'</option>';
                                }
                            ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="label" width="16%">Caption</td>
                    <td class="input-ele" colspan="7"><input type="text" name="ot_caption" id="ot_caption" value="" size="90"></td>
                </tr>
                <tr>
                    <td class="label" width="16%">Description</td>
                    <td class="input-ele" colspan="7"><textarea name="ot_description" id="ot_description" cols="120" rows="5"></textarea></td>
                    
                </tr>
                <tr>
                    <td class="label" width="16%"></td>
                    <td class="input-ele" colspan="7">
                            <button onclick="SubmitForm1('', '1');" class="scalable save" type="button"><span>Save</span></button>
                        </td></tr>
            </tbody></table>
        </fieldset>

    </div>


</form>
        </div>
        
        <?php

$gridBlock = $this->getLayout()
                ->createBlock('Organizer/Task_Grid')
                ->setEntityType('quote')
                ->setEntityId($quote_id)
                ->setShowTarget(false)
                ->setShowEntity(false)
                ->setTemplate('Organizer/Task/List.phtml');

$content = $gridBlock->toHtml();
echo $content;
?>