<div>

<div class="intro" >
<p style="width:99%;">
 Vivid Advertising has produced a wide variety of exhibition displays and media banners for a diverse range of satisfied customers – often working to tight deadlines without compromise on quality or service. Our products are commonly used for promotional marketing & advertising. Promotional items for exhibitions / events / product launches. Here are just a few companies, our valued customers...
 </p>
</div>
     
    <ul class="products-grid first odd">
        <?php
        $Media = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
        $objLogos = new Mconnect_Brandlogo_Model_Brandlogo();
        $logos = $objLogos->getAllLogos();
        $i = 1;
        foreach ($logos as $logo) {
            ?>    
            <li class='item <?php if ($i == 1) echo "first";if($i%4 == 0)echo "last"; ?> fadeIn animated' style="min-height: 100px; margin: 0 25px 10px 0;">
                <span class="product-image"><img src='<?php echo $Media ?>brandlogo<?php echo $logo['filename'] ?>' alt='<?php echo $logo['title'] ?>'  title='<?php echo $logo['title'] ?>' /></span>
            </li>    
            <?php
            $i++;
        }
        ?>
    </ul>    
</div>