<?php 
		/*auto complete change url*/
		
		
?>
<div style="min-height:385px; height:485px; width:220px; overflow:auto;">
<ul>

<?php foreach ($items as $item): ?>
   
   <?php 
   		/*if item type is a Product  */		
		if($item['type']=='Product'){
			
		$_products = explode('/',$item['id']);
		$_root_id = $_products[1]; 
		$_product_id = $_products[2];
		$_product_obj = Mage::getModel('catalog/product')->load($_product_id);
		$_product_url = $_product_obj->getUrl_path();
		/*categories Ids if product is multiple categories*/
		$_category_ids = $_product_obj->getCategoryIds();
		$_website_ids =$_product_obj->getWebsiteIds() ;
		$qtyStock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product_obj)->getQty();
		
		//print_r($_category_ids);
		
		/*check if that product is in multiple stores*/		
		foreach($_website_ids as $_website_id){
			//echo $_website_id;
			$_website_obj =  Mage::app()->getWebsite($_website_id);
			//print_r($_website_obj->getName());			
			/*check if product is in multiple categories in store*/
			foreach($_category_ids as $_category_id){
			//echo $_category_id;
			 $_category_url = Mage::getModel('catalog/category')->load($_category_id)->getUrl_key();
			/*get store info*/
			// $_store = Mage::getModel('core/store')->getCollection()
   			 //						   ->loadByCategoryIds($_category_id);
			// print_r($_store);
			/*Making URL*/
			
			$new_url = $_website_obj->getName().$_category_url.'/'.$_product_url;
			//echo $_category_url;
					
			?>
			
			<li onclick="window.open('<?php echo $new_url;?>','Vivid Advertising Page','');"  id="<?php echo $item['id'] ?>" url="<?php echo $new_url; //echo $item['url'] ?>">
        <div style="float:right; color:red; font-weight:bold; ">[<?php echo $item['type'] ?>]</div>
        <div style="height:140px; ">
        <img src="<?php echo $this->helper('catalog/image')->init($_product_obj, 'small_image')->resize(40, 40);?>" width="40" height="40" style="border:1px solid #ccc; width:40px; height:40px; margin-right:3px;"  align="left"/>
        <strong><?php echo $this->escapeHtml($item['name']) ?></strong>
         <div class="leftLabel"><b>Price:</b> $ <?php echo round($_product_obj->getPrice(),2,PHP_ROUND_HALF_DOWN);?>  <span><b>Special:</b> $ <?php echo round($_product_obj->getSpecial_price(),2,PHP_ROUND_HALF_DOWN);?></span></div>
        <div class="leftLabel"><b>Stock:</b> <?php   echo round($qtyStock,0); ?> </div>
          <div class="leftLabel" style="font-size:9px;"><?php echo $_website_obj->getName();?></div>
        <div class="leftLabel"  style="font-size:14px; margin-top:4px;"><b>SKU: <span style="color:#036;"><?php echo $_website_id.$_product_obj->getSku();?></span></b></div>
       
        
        </div>
        <!--<span class="informal"><?php echo $this->escapeHtml($item['description']) ?></span>-->
    </li>
			<?php
			}  //end of if product is in multiple categories 
			
			 } //end of foreach for websites
		
			
   ?>
        
    <?php 
		}else{
    ?>
    <li id="<?php echo $item['id'] ?>" url="<?php echo $item['url'] ?>">
        <div style="float:right; color:red; font-weight:bold;">[<?php echo $item['type'] ?>]</div>
        <strong><?php echo $this->htmlEscape($item['name']) ?></strong><br/>
        <span class="informal"><?php echo $this->htmlEscape($item['email']) ?></span>
        <span class="informal"><?php echo $this->htmlEscape($item['store']) ?></span>

    </li>
   
    <?php 
		}
		
    ?>
<?php endforeach ?>
</ul>
<?php 

?>
</div>
<style>
<!--
  .leftLabel{font-size:10px; padding-left:5px;}
  .thumb{  }

-->
</style>