<?php
$url = Mage::helper("adminhtml")->getUrl("timeline/adminhtml_timeline/savetime");
$url2 = Mage::helper("adminhtml")->getUrl("timeline/adminhtml_timeline/savetasknumber");

$connectionRead = Mage::getSingleton('core/resource')->getConnection('core_read');
$connectionWrite = Mage::getSingleton('core/resource')->getConnection('core_write');

$temptableTimeline=Mage::getSingleton('core/resource')->getTableName('product_timeline');
//$sqlTimeline="SELECT * FROM ".$temptableTimeline." WHERE product_id = '0' ";
$sqlTimeline = $connectionRead->select()
			->from($temptableTimeline, array('*'))
			->where('product_id=?',0); 
$chkTimeline = $connectionRead->fetchAll($sqlTimeline);

$temptableTask=Mage::getSingleton('core/resource')->getTableName('subadmin_task_number');
//$sqlTask="SELECT * FROM ".$temptableTask." WHERE entity_id = '1' ";
$sqlTask = $connectionRead->select()
			->from($temptableTask, array('*'))
			->where('entity_id=?',1);
$chkTask = $connectionRead->fetchAll($sqlTask);
	
?>
<?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); 
echo $this->getMessagesBlock()->getGroupedHtml(); ?> 
<div class="maintimeline">
    <form enctype="multipart/form-data" name="form_planning" id="form_planning" method="POST" action="<?php echo $url?>">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>">
    <table class="timelinetab">
        <tr>
            <td class="timecap">Artwork delay time</td>
            <td><input type="text" name="artwork" value="<?php echo $chkTimeline[0]['artwork_day']?>" /></td>
            <td><input type="checkbox" name="sunday_artwork" value="1" <?php if($chkTimeline[0]['sunday_artwork'] == 1)echo 'checked';?>/> Exclude Sunday</td>
            <td><input type="checkbox" name="holiday_artwork" value="1" <?php if($chkTimeline[0]['holiday_artwork'] == 1)echo 'checked';?>/> Exclude Holiday</td>
        </tr>
        <tr>
            <td class="timecap">Proof approval delay time</td>
            <td><input type="text" name="proof" value="<?php echo $chkTimeline[0]['proof_day']?>" /></td>
            <td><input type="checkbox" name="sunday_proof" value="1" <?php if($chkTimeline[0]['sunday_proof'] == 1)echo 'checked';?>/> Exclude Sunday</td>
            <td><input type="checkbox" name="holiday_proof" value="1" <?php if($chkTimeline[0]['holiday_proof'] == 1)echo 'checked';?>/> Exclude Holiday</td>
        </tr>
        <tr>
            <td class="timecap">Production Start delay time</td>
            <td><input type="text" name="production" value="<?php echo $chkTimeline[0]['production_day']?>" /></td>
            <td><input type="checkbox" name="sunday_production" value="1" <?php if($chkTimeline[0]['sunday_production'] == 1)echo 'checked';?>/> Exclude Sunday</td>
            <td><input type="checkbox" name="holiday_production" value="1" <?php if($chkTimeline[0]['holiday_production'] == 1)echo 'checked';?>/> Exclude Holiday</td>
        </tr>
        <tr>
            <td class="timecap">Delivary delay time</td>
            <td><input type="text" name="delivary" value="<?php echo $chkTimeline[0]['delivary_day']?>" /></td>
            <td><input type="checkbox" name="sunday_delivary" value="1" <?php if($chkTimeline[0]['sunday_delivary'] == 1)echo 'checked';?>/> Exclude Sunday</td>
            <td><input type="checkbox" name="holiday_delivary" value="1" <?php if($chkTimeline[0]['holiday_delivary'] == 1)echo 'checked';?>/> Exclude Holiday</td>
        </tr>
        <tr>
            <td class="timecap">Shipping delay time</td>
            <td><input type="text" name="shipping" value="<?php echo $chkTimeline[0]['shipping_day']?>" /></td>
            <td><input type="checkbox" name="sunday_shipping" value="1" <?php if($chkTimeline[0]['sunday_shipping'] == 1)echo 'checked';?>/> Exclude Sunday</td>
            <td><input type="checkbox" name="holiday_shipping" value="1" <?php if($chkTimeline[0]['holiday_shipping'] == 1)echo 'checked';?>/> Exclude Holiday</td>
        </tr>
        <tr>
            <td colspan="4"><button type="submit" name="submit">Save</button></td>
        </tr>
    </table>
    </form>
</div>
<?php
    
    $url3 = Mage::helper("adminhtml")->getUrl("vendor/adminhtml_vendor/printassign");
    
        $roles = Mage::getModel('admin/roles')->getCollection();
       foreach($roles as $role):
          //echo '<br/>Role : '.$role->getId()." | ".$role->getRoleName();
          if($role->getRoleName() == 'Vendor' )
          {
            $roleid = $role->getId();
          }
          
       endforeach;
       
        $temptableUser=Mage::getSingleton('core/resource')->getTableName('admin_role');
                
        
        //$sqlUser="SELECT * FROM  ".$temptableUser." WHERE  parent_id ='".$roleid."' ";
	$sqlUser = $connectionRead->select()
			->from($temptableUser, array('*'))
			->where('parent_id=?',$roleid);
        $chkUser = $connectionRead->fetchAll($sqlUser);
?>
<div class="commontask">
    <form enctype="multipart/form-data" name="form_planning" id="form_planning" method="POST" action="<?php echo $url2?>">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>">
        <table class="tabnum">
            <tr>
		<td>
		    <select name="subadmin" onchange="loaddetails(this.value)">
			<option value="">Assign Subadmin</option>
			<?php
			    foreach($chkUser as $user)
			    {
				$user = Mage::getModel('admin/user')->load($user['user_id']);
				
				$temptablePrint=Mage::getSingleton('core/resource')->getTableName('vendor_user_print');
				    
			    
				//$sqlPrint="SELECT * FROM  ".$temptablePrint." WHERE  user_id ='".$user->getId()."' ";
				$sqlPrint = $connectionRead->select()
					    ->from($temptablePrint, array('*'))
					    ->where('user_id=?',$user->getId());
				$chkPrint = $connectionRead->fetchAll($sqlPrint);
				?>
				       <option value="<?php echo $user->getId();?>" /><?php echo $user->getName();?></option
				    
				<?php
				
			    }
			   
			    
			?>
		    </select>
		</td>
		<td id="productallid">
		    <select name="product[]" multiple="multiple">
			<option value="">Product Sku</option>
			<?php
			    $collection = Mage::getModel('catalog/product')->getCollection()->addAttributeToSort('name', 'ASC');
			   // $collection->addAttributeToFilter('status',1);
			   
			    foreach($collection as $_product)
			    {
				$_newProduct = Mage::getModel('catalog/product')->load($_product->getId());
				if(trim($_newProduct->getName()) != '')
				{
				
				?>
				       <option value="<?php echo $_product->getId();?>" /><?php echo $_newProduct->getSku();?></option>
				    
				<?php
				}
				
			    }
			?>
		    </select>
		</td>
                <td class="timecap">Number of Task per Day :</td>
                <td><input type="text" name="task_number" id="task_number"  /></td>
                <td><button type="submit" name="submit">Save</button></td>
            </tr>
        </table>
    </form>
</div>

<script type="text/javascript">
    function loaddetails(userid)
    {
	document.getElementById('loading-mask').style.display = '';
        var xmlhttp;
        if (window.XMLHttpRequest)
          {// code for IE7+, Firefox, Chrome, Opera, Safari
          xmlhttp=new XMLHttpRequest();
          }
        else
          {// code for IE6, IE5
          xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
          }
        xmlhttp.onreadystatechange=function()
          {
          if (xmlhttp.readyState==4 && xmlhttp.status==200)
            {
                //document.getElementById("sc_cal_out").innerHTML=xmlhttp.responseText;
                //alert(xmlhttp.responseText);
		var valueall = xmlhttp.responseText.split('@@');
		document.getElementById('productallid').innerHTML = valueall[0];
		document.getElementById('task_number').value = valueall[1];
		document.getElementById('loading-mask').style.display = 'none';
                
                
               
            }
          }
          form_key = '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>';
        xmlhttp.open("POST","<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>index.php/timeline/adminhtml_timeline/loadtasknumber/?subadmin="+userid+"&form_key="+form_key+"&isAjax=true",true);
        //xmlhttp.open("GET","<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>ajax/remove_holi.php?holiid="+holiid,true);
        xmlhttp.send();
    }
</script>
