<?php
/**
 * Manufacturers extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   FME
 * @package    Manufacturers
 * @author     Kamran Rafiq Malik <kamran.malik@unitedsol.net>
 * @copyright  Copyright 2010 © free-magentoextensions.com All right reserved
 */
?>


<script src="<?php echo $this->getJsUrl() ?>faqs/jquery-1.4.2.min.js" type="text/javascript"></script> 
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/faqs/jquery.ui.widget.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/faqs/jquery.js"></script>
<script src="<?php echo $this->getJsUrl() ?>mage/adminhtml/loader.js" type="text/javascript"></script>  
<script type="text/javascript">
jQuery(function(jQuery) {	
	jQuery(".accordion2 h3").eq(2).addClass("active");
	jQuery(".accordion2 #content").eq(2).show();
	jQuery(".accordion2 h3").click(function(){
		jQuery(this).next("#content").slideToggle("slow")
		.siblings("#content:visible").slideUp("slow");
		jQuery(this).toggleClass("active");
		jQuery(this).siblings("h3").removeClass("active");
	});

});
jQuery.noConflict();
</script>

<script type="text/javascript">
jQuery(function(jQuery) {
	jQuery(".btn-slide").click(function(){
		jQuery("#panel").slideToggle("slow");
		jQuery(this).toggleClass("active");
		jQuery("#faqs_messages").html('');
		return false;
	});	 
});
jQuery.noConflict();
</script>

<?php $pid = $this->getProduct()->getId(); ?>
<?php

	$faqsTable = Mage::getSingleton('core/resource')->getTableName('faqs');
	$faqsTopicTable = Mage::getSingleton('core/resource')->getTableName('faqs_topics');
	$faqsStoreTable = Mage::getSingleton('core/resource')->getTableName('faqs_topics');

    $sqry = "select f.* from ".$faqsTable." f where (product_ids like '%$pid,%' or product_ids like '%$pid') and status = 1";
    $connection = Mage::getSingleton('core/resource')->getConnection('core_read');
    $select = $connection->query($sqry);
    $faqs = $select->fetchAll();
    
?>

<?php if (count($faqs)): ?>
<div class="box-collateral" style="margin-top:25px;">
    <h2><?php echo $this->__('Product FAQs') ?></h2> 
    <div id="faqs_messages"></div>
    <div id="panel">
    	<div id="loadingmask" style="display: none;"> 
            <div class="loader" id="loading-mask-loader"><img src="<?php echo str_replace("index.php/","",$this->getUrl()) ?>skin/adminhtml/default/default/images/ajax-loader-tr.gif" alt="<?php echo $this->__('Loading...') ?>"/><?php echo $this->__('Loading...') ?></div> 
            <div id="loading-mask"></div> 
		</div>
        <form method="post" id="faqformask" >
        <?
            $value = 2;
        ?>	   
                <input name="status" id="status" value="<?php echo $value; ?>" type="hidden"  />
                <input name="reply" id="reply" value="0" type="hidden"  />
                <input name="product_ids" id="product_ids" value="<?php echo $pid; ?>" type="hidden"  />
                <input name="type" id="type" value="Product Question" type="hidden"  />
                <input name="product_name" id="product_name" value="<?php echo $this->getProduct()->getName();?>" type="hidden"  />
                
                <div class="fieldset">
                <h2 class="legend"><?php echo Mage::helper('faqs')->__('Ask a Question') ?></h2>
                <ul class="faqs-form">
                	<li class="fields">
                        <div class="field">
                            <label for="contact_name"><?php echo Mage::helper('faqs')->__('Name') ?></label>
                            <div class="input-box">
                            <input name="contact_name" id="contact_name" title="<?php echo Mage::helper('faqs')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('faqs')->getUserName()) ?>" class="input-text" type="text" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="contact_email" class="required"><em>*</em><?php echo Mage::helper('faqs')->__('Email') ?></label>
                            <div class="input-box">
                                <input name="contact_email" id="contact_email" title="<?php echo Mage::helper('faqs')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('faqs')->getUserEmail()) ?>" class="input-text required-entry" type="text" />
                            </div>
                        </div>
                    </li>
                    <li class="wide">
                        <label for="faqs" class="required"><em>*</em><?php echo Mage::helper('faqs')->__('Question ?') ?></label>
                        <div class="input-box">
                            <textarea name="title" id="title" title="<?php echo Mage::helper('faqs')->__('Question ?') ?>" class="required-entry input-text" cols="5" rows="10"></textarea>
                        </div>
                        
                    </li>
                    <li class="wide">
                        <div id="captcha">
                            <input name="captacha_code" type="hidden" id="captacha_code" value="<?php echo $code=Mage::helper('faqs')->getNewrandCode(6)?>" />
                            <label for="image"><img src="<?php echo Mage::helper('faqs')->getSecureImageUrl() ?>CaptchaSecurityImages.php?width=180&height=40&code=<?php echo $code?>" /></label><br/>
                            <div class="input-box">
                            <label for="security_code" class="required"><em>*</em><b><?php echo Mage::helper('faqs')->__('Security Code Message:') ?></b></label><br />
                            <input id="security_code" name="security_code" type="text" /> <br />
                            <?php echo Mage::helper('faqs')->__('If you have difficulty in reading the image above then refresh your browser a few times until you see an image that is clear enough to copy.') ?>
                            </div> 
                        </div>
					</li>
                    	<button type="submit" title="<?php echo Mage::helper('faqs')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
                </ul>
                </div>           
        </form>
	</div>
	<p class="faqsaddslide"><a href="#" class="btn-slide"><?php echo Mage::helper('contacts')->__('Ask Question') ?></a></p>
        
    <div class="accordion2">
              <?php foreach ($faqs as $_faqs): ?>
                    <h3><?php echo $_faqs["title"]; ?></h3>
                    <div id="content"><?php echo Mage::helper('faqs')->getWysiwygFilter($_faqs["faq_answar"]); ?></div>
              <?php endforeach; ?> 
    </div>
</div>
<?php endif; ?>

<script type="text/javascript">
jQuery(function(jQuery) {
	jQuery("#faqformask").submit(function(){
		dataString = jQuery("#faqformask").serialize();
		Element.show('loadingmask'); 
		jQuery.ajax({
		type: "POST",
		url: "<?php echo $this->getUrl('faqs/index/add') ?>",
		data: dataString,
		dataType: "json",
		complete : function(data) {
				Element.hide('loadingmask'); 
				if(data.responseText == "Success") {
					refreshCaptcha();
					jQuery("#faqs_messages").html('<ul class="messages"><li class="success-msg"><ul><li><?php echo Mage::helper('contacts')->__('Your Question was submitted and will be responded to you as soon as possible. Thank you for contacting us.') ?></li></ul></li><ul>');
					jQuery('#contact_name').val('');
					jQuery('#contact_email').val('');
					jQuery('#title').val('');
					
					//Hide the Question Panel
					jQuery("#panel").slideToggle("slow");
					jQuery(this).toggleClass("active");
					
				} else {
					jQuery("#faqs_messages").html(data.responseText);
				}
		}
		});
		return false;            
	});
	
	function refreshCaptcha() { 
		jQuery.ajax({
		type: "GET",
		url: "<?php echo $this->getUrl('faqs/index/refresh') ?>",
		complete : function(data) {
				jQuery("#captcha").html(data.responseText);  
			}
		});
	}
	
});
jQuery.noConflict();
</script>
