<?php
/**
 * Template button.phtml
 *
 * @author Aptoplex
 * @copyright 2015 Aptoplex
 *
 * @var $this Aptoplex_EasyUploader_Block_Adminhtml_System_Config_Form_Button
 */

$helper = Mage::helper('aptoplex_easyuploader');

?>

<script type="text/javascript">
    //<![CDATA[
    function moveExistingUploads() {
        <?php
        if (!Aptoplex_EasyUploader_Helper_Data::RUN_IN_DEMO_MODE) { ?>
            var msg =   '<?php echo $this->__("Moving existing uploaded files..."); ?>';
            msg +=      '\n\n';
            msg +=      '<?php echo $this->__("Please dismiss this notification then wait a few minutes for the changes to take effect."); ?>';
            alert(msg);
        <?php
        }
        else { ?>
            alert('Sorry, not available in DEMO mode.');
        <?php
        } ?>

        var requesturl = '<?php echo $this->getAjaxMoveExistingUploadsUrl() ?>';
        console.log(requesturl);
        new Ajax.Request(requesturl, {
            method:     'get',
            onSuccess: function(transport){
                if (transport.responseText){

                }
            }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>