<?php $tmpl_drop_html = $this->getTemplateDropHtml() ?>
<div class="entry-edit custom-options product-custom-options">
    <div id="dynamic-price-warrning" style="display:none">
        <ul class="messages">
            <li class="error-msg">
                <ul>
                    <li><?php echo $this->__('Bundle with dynamic pricing cannot include custom defined options. Options will not be saved.') ?></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="entry-edit-head">
        <h4><?php echo Mage::helper('catalog')->__('Options Template') ?></h4>
    </div>	
    <div id="template_options_container" class="box">
		<div class="tmpl-box">
			<?php echo $tmpl_drop_html ?>
			<input type="hidden" name="curr-template-id" id="curr-template-id" value="" />
		</div>
		<div class="tmpl-box">
			<?php if($tmpl_drop_html) : ?>
				<span id="text-guide">
					<?php echo $this->__('Please select SAVE AND CONTINUE EDIT to apply options template')?>
				</span>
			<?php else :?>
				<span id="text-guide">
					<?php echo $this->__('Templates not found')?>
				</span>			
			<?php endif; ?>
		</div>		
		<div class="clear">&nbsp;</div>
	</div>		
    <div class="entry-edit-head">
        <h4><?php echo Mage::helper('catalog')->__('Custom Options') ?></h4>
        <div class="right"><?php echo $this->getAddButtonHtml() ?></div>
    </div>
    <div id="product_options_container" class="box">
        <div id="product_options_container_top"></div>
        <?php echo $this->getOptionsBoxHtml() ?>
    </div>
</div>
<script type="text/javascript">
// re-bind form elements onchange
varienWindowOnload(true);
//show error message
if ($('price_type')) {
    if ($('price_type').value == '0' && $('dynamic-price-warrning')) {
        $('dynamic-price-warrning').show();
    }
}

optionTemplate = new OptionTemplate('<?php echo $this->getUrl('imageoption/adminhtml_template/selecttemplate',array())?>');
</script>
