<div class="stretch-table">   
    <h1>Categories</h1>
</div>
<div class="clear">&nbsp;</div>
<ul class="products-grid first odd">
<?php
$_helper = $this->helper('catalog/output');
$_category = Mage::getModel('catalog/category')->load(48);
$_categories = $_category->getCollection()
->addAttributeToSelect(array('name', 'url', 'image', 'description'))
->addIdFilter($_category->getChildren());
$catCouner= 0;
foreach ($_categories as $_category):
    $catCouner++;
    ?>

    <li class="item <?php if($catCouner == 1){echo "first";}else if($catCouner%3==0)echo "last";?> fadeIn animated"> 
        <a class="product-image" href="<?php echo $_category->getUrl();?>">
            <img src="<?php echo getImageUrl($_category);?>" width="310" height="250">
        </a>
      <?php /*?>  <a id="fancybox<?php echo $_category->getId();?>" class="fancybox quick-view" title="<?php echo $_category->getName();?>" href="<?php echo $_category->getUrl();?>" tabindex="1">Click to view</a>
        <h2 class="product-name"> 
            <a href="<?php echo $_category->getUrl();?>"> <?php echo $_category->getName();?> </a> 
        </h2><?php */?>
        
    </li>
<?php
endforeach; 
function getImageUrl($category)
    {
        if ($category instanceof Mage_Catalog_Model_Category) {
            $url = $category->getImageUrl();
        } else {
            $url = Mage::getModel('catalog/category')
                ->setData($category->getData())
                ->getImageUrl();
        }
        return $url;
    }
?>
</ul>

<div class="clear">&nbsp;</div>