<?php

 function getProductOptions(&$item)

{

  $options = array();

  if ($optionIds = $item->getOptionByCode('option_ids')) {

      $options = array();

      foreach (explode(',', $optionIds->getValue()) as $optionId) {

          if ($option = $item->getProduct()->getOptionById($optionId)) {



              $quoteItemOption = $item->getOptionByCode('option_' . $option->getId());



              $group = $option->groupFactory($option->getType())

                  ->setOption($option)

                  ->setQuoteItemOption($quoteItemOption);



              $options[] = array(

                  'label' => $option->getTitle(),

                  'value' => $group->getFormattedOptionValue($quoteItemOption->getValue()),

                  'print_value' => $group->getPrintableOptionValue($quoteItemOption->getValue()),

                  'option_id' => $option->getId(),

                  'option_type' => $option->getType(),

                  'custom_view' => $group->isCustomizedView()

              );

          }

      }

  }

  if ($addOptions = $item->getOptionByCode('additional_options')) {

      $options = array_merge($options, unserialize($addOptions->getValue()));

  }

  return $options;

} 

/**

 * Magento

 *

 * NOTICE OF LICENSE

 *

 * This source file is subject to the Academic Free License (AFL 3.0)

 * that is bundled with this package in the file LICENSE_AFL.txt.

 * It is also available through the world-wide-web at this URL:

 * http://opensource.org/licenses/afl-3.0.php

 * If you did not receive a copy of the license and are unable to

 * obtain it through the world-wide-web, please send an email

 * to license@magentocommerce.com so we can send you a copy immediately.

 *

 * DISCLAIMER

 *

 * Do not edit or add to this file if you wish to upgrade Magento to newer

 * versions in the future. If you wish to customize Magento for your

 * needs please refer to http://www.magentocommerce.com for more information.

 *

 * @category    design

 * @package     base_default

 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)

 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)

 */



/**

 * Product view template

 *

 * @see Mage_Catalog_Block_Product_View

 * @see Mage_Review_Block_Product_View

 */

?>

<?php $_helper = $this->helper('catalog/output'); ?>

<?php $_product = $this->getProduct(); ?>

<script type="text/javascript">

    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);

</script>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div class="product-view">

    <div class="product-essential">

        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

            <div class="no-display">

                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />

                <input type="hidden" name="related_product" id="related-products-field" value="" />

            </div>



            <div class="product-shop">

                <div class="product-name">

                    <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>

                </div>

                <div class="row-detail-productsmodel">

                    <div class="pro-lable">Model No:</div>

                    <div class="pro-sku">

                        <?php $storeId = $this->helper('core')->getStoreId();?>

                        <?php echo $storeId."-".$_product->getSku() ?>

                    </div>

                </div> 

                <div class="product-img-box">

                    <?php echo $this->getChildHtml('media') ?>

                </div>

                 

                <div class="clearer"></div>

                <?php if ($_product->getShortDescription()):?>

                    <div class="short-description">

                        <h2><?php echo $this->__('Product Summary') ?></h2>

                        <div class="std">

						<?php //echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description') ?>

                        <?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description') ?>

                        </div>

                    </div>

                <?php endif;?>

                <div class="star-rating-box" style="display: none;">

                    <div class="review-section"><?php echo $this->getReviewsSummaryHtml($_product, false, true)?></div>                    

                </div>                

                <?php //echo $this->getChildHtml('alert_urls') 

                //if($_product->hasCustomOptions()){

                foreach ($_product->getOptions() as $_option) {

                    if($_option->getTitle() == "Price Table"){

                ?>                    

                        <div class="quantity-discount-box">

                            <h2>Quantity Discounts / Bulk Discounts[<?php echo $_option->getTitle();?>]</h2>

                            <div class="quantity-discount" >

                                <table cellspacing="0">

                                    <tbody>

                                        <tr class="columnheadings">

                                            <th width="40%">Quantity</th>

                                            <th width="60%">Reduced Prices(ex. GST)</th>

                                        </tr>                                                                                    

                                        <?php

                                            $values = $_option->getValues();

                                            foreach ($values as $v) {

                                                //echo $v->getTitle()." - ".$v->getPrice()."<br />";

                                                echo '<tr><td>'.$v->getTitle().':</td><td><font color="#4DB013"><b>'.$v->getPrice().'</b></font></td></tr>';

                                            }

                                        ?>

                                    </tbody>

                                </table>

                            </div>   

                        </div>

                <?php 

                    }

                }?>

                <div class="pricing-box product-detail" >                    

                    <div class="price-text">

                        <?php //echo $this->getPriceHtml($_product) ?>

                        <?php //echo $this->getTierPriceHtml() ?>

                    </div>

                </div>

                <div class="deliver-options" style="display:none;">

                    <div class="deliver-text" style="display: none;">Delivery: $10.95</div>

                    <div class="combine-and-save"><a class="fancybox" href="#inline1" title="Combine & Save">Combine & Save</a></div>

                </div>

                <?php echo $this->getChildHtml('product_type_data') ?>                

                <?php echo $this->getChildHtml('extrahint') ?>

                <?php if ($_product->isSaleable() && $this->hasOptions()){?>

                    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>

                <?php }else{;?>

                    <div class="add-to-box">

                        <?php if($_product->isSaleable()): ?>

                            <?php echo $this->getChildHtml('addtocart') ?>                            

                        <?php endif; ?>

                        <?php echo $this->getChildHtml('addto') ?>

                    </div>

                    <?php echo $this->getChildHtml('extra_buttons') ?>

                <?php }?>

                <?php echo $this->getChildHtml('other');?>

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>

                    <?php //echo $this->getChildChildHtml('container1', '', true, true) ?>

                <?php endif;?>

            </div>

            

            <div class="clearer"></div>

            

        </form>

        <script type="text/javascript">

        //<![CDATA[

            var productAddToCartForm = new VarienForm('product_addtocart_form');

            productAddToCartForm.submit = function(button, url) {

                if (this.validator.validate()) {

                    var form = this.form;

                    var oldUrl = form.action;



                    if (url) {

                       form.action = url;

                    }

                    var e = null;

                    try {

                        this.form.submit();

                    } catch (e) {

                    }

                    this.form.action = oldUrl;

                    if (e) {

                        throw e;

                    }



                    if (button && button != 'undefined') {

                        button.disabled = true;

                    }

                }

            }.bind(productAddToCartForm);



            productAddToCartForm.submitLight = function(button, url){

                if(this.validator) {

                    var nv = Validation.methods;

                    delete Validation.methods['required-entry'];

                    delete Validation.methods['validate-one-required'];

                    delete Validation.methods['validate-one-required-by-name'];

                    // Remove custom datetime validators

                    for (var methodName in Validation.methods) {

                        if (methodName.match(/^validate-datetime-.*/i)) {

                            delete Validation.methods[methodName];

                        }

                    }



                    if (this.validator.validate()) {

                        if (url) {

                            this.form.action = url;

                        }

                        this.form.submit();

                    }

                    Object.extend(Validation.methods, nv);

                }

            }.bind(productAddToCartForm);

        //]]>

        </script>

    </div>

    

    <div style="clear:both;"></div>

    <div class="related-products">

        <ul>

        <?php

        $related_prods = $_product->getRelatedProductIds();

        foreach($related_prods as $related){

            $_rel = Mage::getModel('catalog/product')->load($related);

            $_img = '<img src="'.$this->helper('catalog/image')->init($_rel, 'image')->resize(115, 90).'" alt="'.$this->htmlEscape($_rel->getImageLabel()).'" title="'.$this->htmlEscape($_rel->getImageLabel()).'" />';

            

            ?>

            <li>                

                <a href="<?php echo $_rel->getProductUrl()?>" title="<?php echo $_rel->getName()?>"><?php echo $_helper->productAttribute($_product, $_img, 'image');?></a>

                <h2 class="product-title"><a href="<?php echo $_rel->getProductUrl()?>" title="<?php echo $_rel->getName()?>"><?php echo $_rel->getName()?></a></h2>

            </li>

        <?php

        }

        ?>

        </ul>

    </div>

    <div style="clear:both;"></div>

    <div class="product-collateral" style="display:none;">

        <?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>

        <div class="box-collateral <?php echo "box-{$alias}"?>">

            <?php if ($title = $this->getChildData($alias, 'title')):?>

            <h2><?php echo $this->escapeHtml($title); ?></h2>

            <?php endif;?>

            <?php echo $html; ?>

        </div>

        <?php endforeach;?>

        <?php echo $this->getChildHtml('upsell_products') ?>        

        <?php echo $this->getChildHtml('product_additional_data') ?>

    </div>

</div>

<?php echo $this->getChildHtml('info_tabs') ?>

<div id="inline1" style="width:400px;display: none;">    

    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('combine-and-save')->toHtml() ?>

</div>