<div class="display-list">

<div class="display-list-top">

    <div class="find-item">

                       <img src="<?php echo $this->getSkinUrl();?>images/icon-magnifier.png" alt=""/><span class="find-heading">Find Your Perfect Display</span>

    </div>

</div>

<div class="display-list-content">

    

</div>

<!--<div class="display-list-bottom"></div>-->

</div>

<div class="display-list-top" style="display:none;">

    <div class="find-item">

                       <span class="find-heading">Our Products</span>     </div>

</div>

                        <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('allproducts_13expo')->toHtml() ?>