 


<div class="product_detail">
             <div class="orderNow">
              <a href="<?php echo $this->getUrl('order-step1');?>"> <img src="<?php echo $this->getSkinUrl()?>images/btnordernow.png" alt=""></a>
              </div>
             <div class="breaker"></div>  
             <div class="priceChart">
             <h2>Price Chart</h2>
             <img src="<?php echo $this->getSkinUrl()?>images/priceChart.png" alt="Price Chart">
             <h2>Price Include</h2>
             <img src="<?php echo $this->getSkinUrl()?>images/choiceImg.png" alt="Price Chart">
              <a href="<?php echo $this->getUrl('contact-us');?>">
             <img src="<?php echo $this->getSkinUrl()?>images/btnrequestQuote.png" alt="Price Chart">
             </a>
             <div class="breaker"></div>  
               <img src="<?php echo $this->getSkinUrl()?>images/styles.png" alt="Price Chart">
             </div>
               <div class="breaker"></div>  
                <div class="priceChart">
                <h2>Our Work</h2>
               <div class="product_detail">
              <img class="thm" src="<?php echo $this->getSkinUrl();?>images/teardrop-banners-17.jpg"  />
              <img class="thm" src="<?php echo $this->getSkinUrl();?>images/teardrop-banners-18.jpg"  />
              <img class="thm" src="<?php echo $this->getSkinUrl();?>images/teardrop-banners-19.jpg"  />
              <img class="thm" src="<?php echo $this->getSkinUrl();?>images/teardrop-banners-20.jpg"  />
              <img class="thm" src="<?php echo $this->getSkinUrl();?>images/teardrop-banners-21.jpg"  />
              <img class="thm" src="<?php echo $this->getSkinUrl();?>images/teardrop-banners-22.jpg"  />
              <img class="thm" src="<?php echo $this->getSkinUrl();?>images/teardrop-banners-23.jpg"  />
              <img class="thm" src="<?php echo $this->getSkinUrl();?>images/teardrop-banners-24.jpg"  />
              <img class="thm" src="<?php echo $this->getSkinUrl();?>images/teardrop-banners-25.jpg"  />
              <img class="thm" src="<?php echo $this->getSkinUrl();?>images/teardrop-banners-26.jpg"  />
              <img class="thm" src="<?php echo $this->getSkinUrl();?>images/teardrop-banners-27.jpg"  />
              <img class="thm" src="<?php echo $this->getSkinUrl();?>images/teardrop-banners-28.jpg"  />
              <img class="thm" src="<?php echo $this->getSkinUrl();?>images/teardrop-banners-29.jpg"  />
              <img class="thm" src="<?php echo $this->getSkinUrl();?>images/teardrop-banners-30.jpg"  />
              <img class="thm" src="<?php echo $this->getSkinUrl();?>images/teardrop-banners-31.jpg"  />
              <img class="thm" src="<?php echo $this->getSkinUrl();?>images/teardrop-banners-1.jpg"  />
                  
                  
              
               
               
             </div>
                </div> 
             </div>
