<?php if($this->hasMethods()): ?>

<?php 
		$current_url = Mage::helper('core/url')->getCurrentUrl();
		$order_edit   =  strpos($current_url,'sales_order_edit');		
?>
<table>
          <tr>
            <td class="lebelall">Amount</td>
            <td><input type="text" name="amount" id="received_amount" value="<?php echo Mage::getSingleton('core/session')->getBillamount();?>" <?php if(!$order_edit){?> class="required-entry" <?php } ?> /></td>
          </tr>
           <tr>
            <td class="lebelall"><?php echo Mage::helper('contacts')->__('Date') ?></td>
            <td>
            <input name="date" value="<?php echo Mage::getSingleton('core/session')->getBilldate();?>" id="date"  type="text" <?php if(!$order_edit){?> class="required-entry" <?php } ?>>
             <input name="order_id" id="order_id"  type="hidden">
        <img title="Select date" id="_dob_trig" src="<?php echo str_replace('index.php','',$this->getBaseUrl());?>skin/adminhtml/default/default/images/grid-cal.gif" class="v-middle"></td>
          </tr>
</table>
<div id="order-billing_method_form">
    
    <dl class="payment-methods">
    <?php
        $_methods       = $this->getMethods();
        $_methodsCount  = count($_methods);
        $_counter = 0;
        
        $all_permission = Mage::getSingleton('core/session')->getAllpermission();
        
		//var_dump($_methodsCount);
		//var_dump(Mage::getSingleton('core/session'));
		 
		
		$allmethos = array('anz_egate' => 33,'purchaseorder'=>34,'ccsave'=>35,'checkmo'=>36,'directdeposit_au'=>37);
        //print_r($all_permission);
    if($this->getSelectedMethodCode() == '')
      {
          $i =1;
          foreach ($_methods as $_method): $_code = $_method->getCode(); $_counter++; ?>
        <dt>
        <?php if($_method->getCode() != 'free')
        {
                 //   if(in_array($allmethos[$_method->getCode()],$all_permission))
                 //   {
                              
                              if ($_methodsCount > 1): ?>
                                  <input <?php if($i == 1){?>checked="checked"<?php }?> id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')" <?php if ($_counter == $_methodsCount) : ?>class="validate-one-required-by-name"<?php endif;?>/>
                              <?php else :?>
                                  <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" /></span>
                              <?php endif;?>
                      
                                  <label for="p_method_<?php echo $_code ?>"><?php echo $_method->getTitle() ?></label>
                              </dt>
                              <dd>
                                  <?php echo $this->getChildHtml('payment.method.'.$_code) ?>
                              </dd>
          <?php
                      //    }
              }
              $i++;
          endforeach;
      }
      else{
    ?>
    <?php foreach ($_methods as $_method): $_code = $_method->getCode(); $_counter++; ?>
        <dt>
        <?php if($_method->getCode() != 'free')
        {
                   // if(in_array($allmethos[$_method->getCode()],$all_permission))
                  //  {
                              
                              if ($_methodsCount > 1): ?>
                                  <input  id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> <?php if ($_counter == $_methodsCount) : ?>class="validate-one-required-by-name"<?php endif;?>/>
                              <?php else :?>
                                  <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" /></span>
                              <?php endif;?>
                      
                                  <label for="p_method_<?php echo $_code ?>"><?php echo $_method->getTitle() ?></label>
                              </dt>
                              <dd>
                                  <?php echo $this->getChildHtml('payment.method.'.$_code) ?>
                              </dd>
    <?php
                  //  }
        }
    endforeach;
    
      } ?>
    </dl>
</div>
<script type="text/javascript">order.setPaymentMethod('<?php echo $this->getSelectedMethodCode() ?>')</script>
<?php else: ?>
    <div><?php echo Mage::helper('sales')->__('No Payment Methods') ?></div>
<?php endif; ?>

<script type="text/javascript">
    //<![CDATA[
 Calendar.setup({
        inputField : 'date',
        ifFormat : '%Y-%m-%d',
        button : '_dob_trig',
       // align : 'Bl',
        singleClick : true
    });
 //start 07_03_2014
 if(document.getElementById('delivery_date'))
 {
  Calendar.setup({
        inputField : 'delivery_date',
        ifFormat : '%m/%d/%Y',
        button : 'delivery_date',
       // align : 'Bl',
        singleClick : true
    });
 }
 //End 07_03_2014
//]]>
</script>
