<?php 
		
       // $order_id = '32134293216';
?>


<?php
/**
 * Template index.phtml
 *
 * @author Aptoplex
 * @copyright 2015 Aptoplex
 *
 * @var $this Aptoplex_EasyUploader_Block_Index
 */
 	$postvars = $this->getOrderVars();
	$order_id = $postvars['order_id'];
	$email    = $postvars['email'];
	
	$flashRuntimeUrl = $this->getSkinUrl("lib/aptoplex_easyuploader/plupload/js/Moxie.swf");
	$silverlightRuntimeUrl = $this->getSkinUrl("lib/aptoplex_easyuploader/plupload/js/Moxie.xap");

?>
<style>
<!--
h3{ color:#666 !important; }
-->
</style>
<div id="uploader">
    <div style="clear:both; width:917px;">
        <?php
        if (Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_PAGE_TITLE, null)) { ?>
            <div class="page-title" style="color:#C60">
                <h1 style="color:#888;"><?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_PAGE_TITLE, null); ?> &nbsp;&nbsp;&nbsp;<span style="color:#F00; font-weight:bold;">Your Order id: <?php echo $order_id;?></span></h1>
            </div>
        <?php
        } ?>
        <?php
        if (Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_INTRO_HTML, null)) { ?>
            <div id="intro" style="color:#888">
                <?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_INTRO_HTML, null); ?>
            </div>
        <?php
        } ?>
        <?php $form_key =  Mage::getSingleton('core/session')->getFormKey(); ?>
        <div class="proofs_link" style="float:right; border:1px solid ;"><a style="font-size:18px" href="<?php echo Mage::getBaseUrl().'upload/index/fetchOrder/ref_id/'.$order_id.'/form_key/'.$form_key;?>">&nbsp;&nbsp;Proofs against this order&nbsp;&nbsp; </a></div>
        <div class="alreadyuploaded">
        <h1  style="color:#888; font-weight:bold; color:#930">Already Uplaoded Files</h1>       
        <ul>
		<?php 
			//already uploaded files 
				$uploaded_files = Mage::getModel('aptoplex_easyuploader/upload')
											->getCollection()
											->addFieldToFilter('order_id',$order_id)
											;				
			//	Zend_debug::dump($this->getRequest());				
				
				if(count($uploaded_files) > 0){
				foreach($uploaded_files as $file){		
				   // var_dump($file->getData());
				?>
          			 <li style="float:left; padding-right:5px; padding-left:5px;">
                      <a href="<?php echo Mage::getBaseUrl().'easyuploader/index/download/entity_id/'.$file->getEntity_id();?>" title="click to download this file <?php echo $file->getNew_filename();?>">
                      <img src="<?php echo $this->getFileType($file->getNew_filename()); ?>" height="70" alt="<?php echo $file->getNew_filename();?>"   title="<?php echo $file->getNew_filename();?>" />
                        <br/> 
                        <b><span style="color:#063"><?php echo $file->getData('new_filename');?></span></b>
                        <br/>Download File</a> 
                     </li>  
                     <?php 
						}
					 ?>   
           <?php  }else{ ?>
           			<li style="float:left; padding-right:5px; padding-left:5px;"> No Artwork uploaded yet.</li>
           <?php 
		   }
		   ?>
           </ul>
        
        </div>
        <div style="clear:both"></div>
        
        <div>
            <form id="file-upload-form" action="POST">
                <div class="col2-set" style="display:none;" >
                    <div class="col-1">
                        <div class="content">
                            <fieldset>
                                <ul class="form-list">
                                    <li class="fields" >
                                        <label for="order-number" class="required"><em>*</em></em><?php echo $this->__('Order Number:') ?></label>
                                        <div class="input-box">
                                            <?php
                                            if (Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_NON_STANDARD_ORDER_NUMBER_FORMAT, null)) { ?>
                                                <input id="order-number" type="text" name="order-number" class="input-text required-entry" value="<?php echo $order_id; ?>" tabindex="1"/>
                                            <?php
                                            }else { ?>
                                                <input id="order-number" type="text" name="order-number" class="input-text required-entry validate-number" value="<?php echo $order_id; ?>" tabindex="1"/>
                                            <?php
                                            } ?>
                                            <p class="uploader-field-desc"><?php echo $this->__("Enter your order number you received from us when you placed your order. You can find this in either the e-mail confirmation we will have sent to you or in your"); ?> <a href="<?php echo Mage::getBaseUrl() . 'customer/account'; ?>" target="_blank"><?php echo $this->__("Account area."); ?></a></p>
                                        </div>
                                    </li>
                                </ul>
                            </fieldset>
                        </div>
                    </div>
                    <div class="col-2" style="display:none;">
                        <div class="content">
                            <fieldset>
                                <ul class="form-list">
                                    <li class="fields" >
                                        <label for="email-address" class="required"><em>*</em><?php echo $this->__('E-mail Address:') ?></label>
                                        <div class="input-box">
                                            <input id="email-address" type="text" name="email-address" class="input-text required-entry validate-email" value="<?php echo $email; ?>" tabindex="2"/>
                                            <p class="uploader-field-desc"><?php echo $this->__("Enter the e-mail address you used when you placed your order."); ?></p>
                                        </div>
                                    </li>
                                </ul>
                            </fieldset>
                        </div>
                    </div>
                </div>
               
                <div class="col1-layout">
                    <div class="content">
                        <fieldset>
                            <ul class="form-list" >
                                <li class="fields" style="display:none;">
                                    <label for="additional-comments"><?php echo $this->__('Additional Comments:') ?></label>
                                    <div class="input-box">
                                        <textarea id="additional-comments" name="additional-comments" class="input-text" tabindex="3"></textarea>
                                        <p class="uploader-field-desc"><?php echo $this->__("(Optional) Enter any other information relating to the file(s) you are uploading."); ?></p>
                                    </div>
                                </li>
                               
                                <?php
                                if (Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_TERMS_AND_CONDITIONS_ACCEPTANCE, null)) { ?>
                                    <li class="fields" id="terms-and-conditions" style="display:none;" >
                                        <label class="required"><em>*</em></em><?php echo $this->__('Terms and Conditions:') ?></label>
                                        <?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_TERMS_AND_CONDITIONS_HTML, null); ?>
                                        <div class="input-box">
                                            <input id="terms-and-conditions-checkbox" type="checkbox" name="terms-and-conditions" class="checkbox required-entry"  checked tabindex="4"/>
                                            <label class="normal" for="terms-and-conditions-checkbox"><?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_TERMS_AND_CONDITIONS_CHECKBOX_LABEL, null); ?></label>
                                        </div>
                                    </li>
                                <?php
                                } ?>
                                <li><p class="required" style="display:none;">* <?php echo $this->__("Required fields"); ?></p></li>
                                <li class="fields">
                                    <label for="file-chooser" class="required"><em>*</em><?php echo $this->__('File Upload Queue:') ?></label>
                                    <div id="file-chooser" name="file-chooser">
                                        <div>
                                            <div id="file-upload-queue-header">
                                                <?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_FILE_UPLOAD_QUEUE_HEADER_HTML, null); ?>
                                            </div>
                                            <div id="fileuploader">
                                                <?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_UPLOADER_INIT_FAILURE_HTML, null); ?>
                                            </div>
                                            <div id="file-upload-queue-footer">
                                                <?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_FILE_UPLOAD_QUEUE_FOOTER_HTML, null); ?>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="fields">
                                    <div>
                                        <button class="<?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_UPLOAD_BTN_CSS_CLASS_NAME, null); ?>" onclick="checkDetails()" title="<?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_UPLOAD_BTN_TITLE, null); ?>" type="button" tabindex="6"><span><?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_UPLOAD_BTN_TITLE, null); ?></span></button>
                                    </div>
                                </li>
                            </ul>
                        </fieldset>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    // <![CDATA[
	jQuery.noConflict();
    var theForm = new VarienForm('file-upload-form', true);
    var pendingFilesQueued = 0;

    var chunkSize = '<?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_FILE_CHUNK_SIZE, null); ?>' + 'kb';
    var uploader = jQuery("#fileuploader").pluploadQueue({
        url : '<?php echo $this->getUrl("easyuploader/index/upload") ?>',
        chunk_size : chunkSize,
        filters : {
            <?php /*
            mime_types: [
                { title : "Supported files", extensions : '<?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_ALLOWED_FILE_EXTENSIONS, null); ?>' }
            ]
            */ ?>
            mime_types: [
                { title : "Image files", extensions : '<?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_ALLOWED_FILE_EXTENSIONS, null); ?>' }
            ]
        },
        max_file_size : '<?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_MAX_FILE_SIZE, null); ?>' + 'kb',
        multi_selection : true,
        runtimes : '<?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_RUNTIME_FALLBACK_ORDER, null); ?>',
        flash_swf_url : '<?php echo $flashRuntimeUrl; ?>',
        silverlight_xap_url : '<?php echo $silverlightRuntimeUrl; ?>',
        multipart_params : {},
        multiple_queues : true,
        init : {
            BeforeUpload : function(uploader, file) {
                setInputsState(false);
                checkDetails();
            },
            UploadComplete : function(uploader, files) {
                setInputsState(true);
                var message =   "<?php echo $this->__("SUCCESS: Uploading complete.") ?>" + "\n\n";
                message +=      "<?php echo $this->__("Please check the status of each file to ensure they uploaded successfully.") ?>" + "\n\n";
                message +=      "<?php echo $this->__("TIP: You can add more files to the upload queue and continue uploading if you wish.") ?>";
                alert(message);

                <?php
                if (Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_EMAIL_ENABLE, null)) { ?>
                    jQuery.ajax({
                        'url' : '<?php echo $this->getUrl("easyuploader/index/uploadqueuedidcomplete") ?>',
                        'data' : {
                            'order-number' : jQuery('#order-number').val(),
                            'email-address' : jQuery('#email-address').val()
                        },
                        'type' : 'POST'
                    });
                <?php
                } ?>
            },
            Error : function(uploader, error) {
                var msg;
                switch (error.code) {
                    case -602: // FILE_DUPLICATE_ERROR
                        msg =   "<?php echo $this->__("ERROR:") ?> " + error.message + "\n\n";
                        msg +=  "<?php echo $this->__("Whoops, it looks like you've added the file") ?>";
                        msg +=  " \"" + error.file.name + "\" ";
                        msg +=  "<?php echo $this->__("to the queue already.") ?>";
                        alert(msg);
                        break;
                    default:
                        break;
                }
            },
            FilesAdded : function(uploader, filteredFiles) {
                ++pendingFilesQueued;
            },
            FilesRemoved : function(uploader, filteredFiles) {
                --pendingFilesQueued;
                if (pendingFilesQueued < 0) pendingFilesQueued = 0;
            },
            FileUploaded : function(uploader, file) {
                --pendingFilesQueued;
                if (pendingFilesQueued < 0) pendingFilesQueued = 0;
            }
        }
    });

    function checkDetails() {
        if (theForm.validator.validate()) {
            jQuery.ajax({
                'url' : '<?php echo $this->getUrl("easyuploader/index/checkorder") ?>',
                'data' : {
                    'order-number' : jQuery('#order-number').val(),
                    'email-address' : jQuery('#email-address').val()
                },
                'success' : function(data, textStatus, jqXHR) {
                    var response = JSON.parse(data);
                    switch (response.code) {
                        case <?php echo Aptoplex_EasyUploader_Helper_Data::OK ?>:
                            if (pendingFilesQueued) {
                                //alert(response.message);
                                doUpload();
                            }
                            break;
                        case <?php echo Aptoplex_EasyUploader_Helper_Data::ORDER_NOT_FOUND ?>:
                        case <?php echo Aptoplex_EasyUploader_Helper_Data::UPLOAD_NOT_PERMITTED ?>:
                        case <?php echo Aptoplex_EasyUploader_Helper_Data::UNKNOWN_ERROR ?>:
                            alert(response.message);
                            break;
                        default:
                            break;
                    }
                },
                'type' : 'POST'
            });
        }
    }

    function setInputsState(state) {
        jQuery('#order-number').prop("disabled", !state);
        jQuery('#email-address').prop("disabled", !state);
        jQuery('#additional-comments').prop("disabled", !state);
        jQuery('#file-upload').prop("disabled", !state);
    }

    function doUpload() {
        var queue =  jQuery("#fileuploader").pluploadQueue();
        queue.settings.multipart_params["order-number"] = jQuery('#order-number').val();
        queue.settings.multipart_params["email-address"] = jQuery('#email-address').val();
        queue.settings.multipart_params["additional-comments"] = jQuery('#additional-comments').val();
        queue.start();
    }

    jQuery(function() {

    });

    // ]]>
</script>

