<div class="display-list">

<div class="display-list-top">

    <div class="products">
		<h2>New Arrivals</h2>
    </div>

</div>



<!--<div class="display-list-bottom"></div>-->

</div>
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('crowd_products')->toHtml() ?>
						
<div class="display-list">

<div class="display-list-top">

    <div class="products">
		<h2>Best Sellers Of The Month</h2>
    </div>

</div>



<!--<div class="display-list-bottom"></div>-->

</div>                        

                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('crowd_products1')->toHtml() ?>
						
<div class="product_right">
	    <h2>About Us</h2>
        <div class="about_detail">
         <p>
         High impact, professional presentation: With only a fleeting moment to attract the attention of a trade show attendee, your exhibit must appeal to your target audience's interests. Your display must effectively communicate who you are, what you do and how your company can help them. We can help you with our promotion, advertising and marketing displays &amp; equipments. We sell cheap and affordable high quality products directly to consumers.
         </p>
       
         <p>
         Exhibitions and conventions are the perfect opportunity to introduce your company to the public &amp; we want to help you with your image design. We have a huge selection of Tradeshow Exhibits, Media Wall, Tradeshow Banner Stands, Accessories, Pop Up Booths, Portable Exhibits &amp; presentation boards. Here is everything you need to get noticed, creating successful sales opportunities. Make an impression with an interchangeable graphic board or banner poles.
         </p>
       
         <p>
         Vivid Ads (Creative Advertising &amp; Display Solutions) is Australia's choice to buy In-Stock exhibit stands, fabric mural media backdrop walls, expo booth displays, road show displays, trade fair booths (exhibit / expo) equipments and interactive / interactivity display screens. We also have a established banner graphic and design department to compliment your display banner stands.
         </p>
        
         <p>
         Vivid Ads (Creative Advertising &amp; Display Solutions) is Australia's choice to buy In-Stock exhibit stands, fabric mural media backdrop walls, expo booth displays, road show displays, trade fair booths (exhibit / expo) equipments and interactive / interactivity display screens.
         </p>
         <div class="btn_readmore">
          <a href="http://banners-direct.com.au/about-us">
          Read More
          </a>
         </div>
        </div>
    
    </div>                        