<script src="//code.jquery.com/jquery-1.9.1.js"></script>

<link rel="stylesheet" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/externalform/css/lightbox/lightbox.css" type="text/css" media="screen" />

<script type="text/javascript" src="<?php echo Mage::getBaseUrl(); ?>externalform/js/prototype.lite.js"></script>

<script type="text/javascript" src="<?php echo Mage::getBaseUrl(); ?>externalform/js/moo.fx.js"></script>

<script type="text/javascript" src="<?php echo Mage::getBaseUrl(); ?>externalform/js/litebox-1.0.js"></script>

 <style>

<!--

#quoteLoader .main-container .col-main{
    background: none repeat scroll 0 0 #ef781e !important;
}
.verti {
     width: 96% !important;
}

.uploader_artwork {

display: none;

}

.contacts_button {

display: none;

}

#livechat-full {

display: none;

}

.main-container {

background: none repeat scroll 0 0 #ef781e;

}

.row {

margin: 0 auto;

background-color:#ef781e;

width: 1040px;

}

.col1-layout .col-main {

margin: 0 0 0 0px;

width: 100%;

background-color:#ef781e;

}

.addthis_toolbox {

display: none;

}
.externalform-index-index .col2-left-layout .col-main {
    background: url("../images/index_288.jpg") repeat-x scroll center 5px #ef781e;
    float: right;
    width: 940px;
}
.externalform-index-index .col2-left-layout .col-main {

width: 930px;

}



.externalform-index-index .main {

float: left;

margin-top: 0;

width: 940px !important;

margin-left: 0px !important;

}

.externalform-index-index .top_menu {

margin-bottom: 5px;

float: right;

display: none !important;

}

.externalform-index-index .youama-slider-block{

display:none !important;}

.externalform-index-index .contact_info {

float: right;

display: none !important;

}

.externalform-index-index .Bread-Crumbs {

background: #ef781e;

border:none 0px;

/* float: left; */

/* margin: 0px 0 0; */

/* width: 940px; */

/* border-bottom: 1px solid #f6d6be; */

}

.factory {

margin: 0;

position: relative;

top: 0;

display:none;

width: 1200px;

}

.error_labels{

	color:#fff;

	left: 15px;

    position: relative;

    text-shadow: 1px 2px 1px #5d5c5c;

    top: 11px;

    background-color: #F00;

    line-height: 20px;

    padding: 3px;

	display:none;

	}

.externalform-index-index .col2-left-layout .col-main {

    background: /*url("../images/index_288.jpg") repeat-x scroll center 540px*/ #ef781e;

    float: right;

    width: 940px;

}

-->

</style>

<div class="banner quote">

  <?php

  ///getting store and store id

 

	 

	 $_store_id = $this->getRequest()->getParam('store_id');		 

	 $_store = Mage::getSingleton('core/store')->load($_store_id);	 

	 $_store_group = $_store->getGroup()->getData();

	 $_root_category = $_store_group['root_category_id'];

	  

	 $_category = Mage::getModel('catalog/category')->load($_root_category);

	 $_subcategories = $_category->getChildrenCategories();

    //echo "sdgsdfg".Mage::getSingleton("core/session",array('name' => 'frontend'))->getCaptcha();

	//var_dump($_subcategories);

	//exit;

    //exit;

     Mage::getSingleton("core/session")->setCaptcha("");	

?>

  <!-- Show success page when order is placed-->

  <h2>Request a Quote /Invoice ( Get a free Quote/Invoice in 2 minutes)</h2>

  <div class="thank_u" id="thank_u" style="display:none;">  </div>

  <div class="Success" id="Success" style="display:none"></div>

  

  

  <form id="cus_ordfrm" name="cus_ordfrm" method="post" >

    <input type="hidden" id="store_id" name="store_id" value="<?php echo $_store_id; ?>"/>

    <div class="req-head"></div>

    <div class="comp-head">

      <div class="nam1">Company:</div>

    </div>

    <div class="comp-data">

      <span><input type="text" id="comp_val" name="comp_val" class="bil-nput" onKeyPress="resetField(this)"   /> </span> 

      <span class="error_labels" id="comp_lbl">Please enter proper company name </span>     

    </div>

    

    <div class="name-head">

      <div class="nam1">First Name:<span class="fontRed">*</span></div>

      <div class="nam1">Last Name:<span class="fontRed">*</span></div>

    </div>

    <div class="name-data"><span class="nput1">

      <input type="text" id="fnamebill" name="fnamebill"  onKeyPress="resetField(this)"  />

      <span class="error_labels" id="fname_lbl">Please enter proper firsname. </span>

      </span>

      <span class="nput2">

      <input type="text" id="lnamebill" name="lnamebill"  onKeyPress="resetField(this)"  />      

      <span class="error_labels" id="lname_lbl">Please enter proper lastname. </span>

      

      </span></div>

    <div class="ph-head">

      <div class="nam1">Phone:<span class="fontRed">*</span></div>

    </div>

    <div class="ph-data">

      <input type="text" id="phonebill" name="phonebill"  onKeyPress="resetField(this)"  />

      <span class="error_labels" id="phone_lbl">Please enter proper phone.  </span>

    </div>

    <div class="email-head">

      <div class="nam1">E-mail:<span class="fontRed">*</span></div>

    </div>

    <div class="email-data">

      <input type="text" id="emailbill" name="emailbill"  onKeyPress="resetField(this)"  />

      <span class="error_labels" id="email_lbl">Please enter proper email e.g 'John@gmail.com' </span>

    </div>

    <div class="email-head">

      <div class="nam1">Confirm E-mail:<span class="fontRed">*</span></div>

    </div>

    <div class="email-data">

      <input type="text" id="conemailbill" name="conemailbill"  onKeyPress="resetField(this)"  />

      <span class="error_labels" id="conemail_lbl">Please enter confirm email e.g 'John@gmail.com'  </span>

    </div>

    <div class="bill-head">

      <div class="nam1">Billing Address:<!--<span class="fontRed">*</span>--></div>

    </div>

    <div class="bill-data">

      <input type="text" id="add1bill" name="add1bill" class="bil-nput"   onKeyPress="resetField(this)" />

      <span class="error_labels" id="add1_lbl">Please enter proper Address </span>

      

      <!-- Thank you for your interest, We will get back to you shortly-->

      

      <!--<input type="text" id="add2bill" name="add2bill" class="bil-nput">-->

      

    </div>

    

    <div class="bill-head">

      <div class="nam1">Country:<!--<span class="fontRed">*</span>--></div>

    </div>

     <div class="bill-data">

      <select name="countrybill" id="countrybill" class="contenta" onChange="resetField(this)">

        <option value="AUS" selected="">Australia</option>

        </select>

      <span class="error_labels" id="country_lbl">Select Country like 'Australia' </span> 

      

    </div>

    

    <div class="loc-head">

      <div class="nam1">City:<!--<span class="fontRed">*</span>--></div>

      <div class="nam2">Which state goods are being delivered to ?:<!--<span class="fontRed">*</span>--></div>

    </div>

    

    <div class="loc-data"><span class="nput1">

      <input type="text" id="citybill" name="citybill"   onKeyPress="resetField(this)"  />

      <span class="error_labels" id="city_lbl">Please enter city name </span>

      </span><span class="nput2">

      <?php

       $store1 = Mage::getModel('core/store')->load($_store_id);

	   Mage::app($store1->getCode());

       $countrycode = Mage::getStoreConfig('general/country/default',$store1);

       $statearray = Mage::getModel('directory/region')->getResourceCollection()

	                 ->addCountryFilter(trim($countrycode,' '))->load();

       $vvl="";

       foreach ($statearray as $_state) {

       $vvl=trim($_state->getCode());

       break;

       }

       if($vvl!="")

       {

		?>

      <select name="statebill" style="margin-top:0px;" id="statebill" class="contenta" onChange="resetField(this)">

        <option value="" selected="">Choose State</option>

        <?php

							    /***************** start 28_01_2014 **********************/

							     //$countrycode = 'AU';

        $store1 = Mage::getModel('core/store')->load($_store_id);

        Mage::app($store1->getCode());

        $countrycode = Mage::getStoreConfig('general/country/default',$store1);

        $statearray = Mage::getModel('directory/region')->getResourceCollection()

		              ->addCountryFilter(trim($countrycode,' '))->load();

        foreach ($statearray as $_state) {

		 echo "<option value='" . $_state->getCode() . "'>" .  $_state->getDefaultName() . "</option>";

	     }

							 /***************** end 28_01_2014 **********************/

	    ?>

      </select>

      <?php	}else{  ?>

      <input type="text" id="statebill" name="statebill" value=""   onKeyPress="resetField(this)"  />

      <?php }	?>

      <span class="error_labels" id="state_lbl">Please enter proper state </span>

      

      </span>

      

      </div>

    <div class="coun-head">

      <div class="nam1">Postcode :<!--<span class="fontRed">*</span>--></div>

      

      <!--<div class="nam1">Country:<span class="fontRed">*</span></div>-->

      

    </div>

    <div class="coun-data"><span class="nput1">

      <input type="text" id="zipbill" name="zipbill"   onKeyPress="resetField(this)"  />

      <span class="error_labels" id="zip_lbl">Please enter postcode </span>

      </span></div>
      
      
    
    <div class="ph-head">

      <div class="nam1">When do you need the goods by? : <!--<span class="fontRed">*</span>--></div>

    </div>

    <div class="ph-data">

      <input type="text" onKeyPress="resetField(this)" id="del_date" onClick="ds_sh(this); resetField(this)" name="del_date" style="width:20%; " />

      <span class="error_labels" id="del_lbl">Please provide valid date </span>

      

      <?php

					/*

                                                  <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" alt="" class="v-middle" id="calendar-deldate_trig" title="<?php echo $this->__('Date selector') ?>" />

                                                  <script type="text/javascript">

                                                  Calendar.setup({

                                                  inputField : "del_date",

                                                  ifFormat: "%Y-%m-%d",

                                                  button : "calendar-deldate_trig",

                                                  //align : "Bl",

                                                  singleClick : true

                                                  });

                                                  </script>

					*/

					?>

    </div>
  
    <div class="req-head" style="margin-top:40px;">

        <h3 class="required_headings"><?php echo __('Question(s) related to this enquiry');?></h3>

        <div class="ph-data">

          <textarea type="text" id="comment" name="comment" 

    style=" background: none repeat scroll 0 0 #fff !important; border: 1px solid #ccc !important; font-size: 16px; margin-left:83px; margin-top: -40px;"></textarea>

        </div>

      </div> 
          <?php 

			$words  = "abcdefghijlmnopqrstvwyz";

                                    $vocals = "aeiou";                                

                                    $text  = "";

                                    $vocal = rand(0, 1);

                                    $length = rand(3, 3);

                                    for ($i=0; $i<$length; $i++) {

                                        if ($vocal) {

                                            $text .= substr($vocals, mt_rand(0, 3), 1);

                                        } else {

                                            $text .= substr($words, mt_rand(0, 3), 1);

                                        }

                                        $vocal = !$vocal;                        

						            }

					//	echo $text;			

                        

						 Mage::getSingleton("core/session",array('name' => 'frontend'))->setCaptcha($text);

	?>

      
    <div class="captcha_area" style="margin-top:5px;">

        

        

        

        <div class="captcha_img"><img src="<?php echo Mage::getBaseUrl(); ?>externalform/captcha.php?ts=<?php echo time(); ?>&text=<?php echo $text; ?>" id="captcha" />

        <input type="hidden" id="captcha_value" name="captcha_value" value="<?php echo $text; ?>" />        

        </div>        

        <div class="refresh_captcha" style="float:left; width:100%;margin:10px 0; ">

        <a href="javascript:void(0);" onClick="updateCaptcha()" id="change-image" style="float:left;">

        

        <img src="<?php echo $this->getSkinUrl()?>externalform/images/refresh_code.png"  onMouseOver="this.src='<?php echo $this->getSkinUrl()?>externalform/images/refresh_code_hover.png'" onMouseOut="this.src='<?php echo $this->getSkinUrl()?>externalform/images/refresh_code.png'"/>

        

        </a>

        <img id="captcha_loader" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/default/default/externalform/images/loading2.gif" style="display: none; float: left; position: relative;left: 10px;top: 3px;" />

        </div>

        <div class="captcha_text"><?php echo 'Please enter above words below'?></div>

        <div class="captcha_input">

          <input type="text" name="captcha" onKeyPress="resetField(this)"  id="captcha-form" autocomplete="off" class="captcha_txt" />

          <span class="error_labels" id="captcha_lbl">You have entered an incorrect captcha code. Try again </span>

        </div>

        <!--<div class="req-head">Note: Field with <span class="fontRed">*</span> are mandatory and required to fill the form and post the quotatoin.</div>-->

      </div>   
      
      
      

    <h2 class="verti">Choose product(s) and quantity</h2>

    <div id="all_pro_con">

      <div class="one_pro">

        <div class="con" style="width:32% ;"><span class="lab">Category</span><span class="inp">

          <select name="category[]" id="cat" onChange="getProduct(this.value,this);">

            <option value="">Select a category</option>

            <?php

                foreach($_subcategories as $_sub){

                $_sub=Mage::getModel('catalog/category')->setStoreId($_store_id)->load($_sub->getId());

                ?>

            <option value="<?php echo $_sub->getId(); ?>"><?php echo $_sub->getName(); ?></option>

            <?php  }   ?>

          </select>

          

          <img id="load_product" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/default/default/externalform/images/loading2.gif" style="width:30px; height:30px; display:none; float:left;" />

          

          </span></div>

        <div class="con proddiv"><span class="lab">Products</span><span class="inp">

          <select name="products[]" id="catproduct" class="prod">

            <option value="">Select a product</option>

          </select>

          

           <img id="load_image" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/default/default/externalform/images/loading2.gif" style="width:30px; height:30px; display:none; float:left;" />

          

          </span></div>

        <div class="im_con prodimgdiv"><span class="im" style="color:#fff;">Product Image</span>

          <div class="def_cl"></div>

        </div>

                <div class="pro_qty"><span class="lab">Quantity</span>

          <input type="text" name="quantity[]" class="quantity" value="1" />

          

          <span class="error_labels" id="quantity_lbl">Please enter quantity </span>

          

        </div>

        <div class="del_button"><a href="javascript:void(0);" class="del_it">Delete</a></div>

      </div>

    </div>

          <div class="add_more_con">

           <img id="new_product_add" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/default/default/externalform/images/loading2.gif" style="display: none; float: left; position: relative;left: -340px;top: 0px;" />

          <a href="javascript:void(0);" id="add_more" style="float:left;">Add Another Product</a>

          

          </div>

<!--    <div class="add_more_con"><a href="javascript:void(0);" onClick="addProductRow(this);" class="add_more_con" id="add_more"></a></div>-->

    

    <!--------------------------------------------------------------->

    

    <div class="desc-step3" style="margin-top:0px">

      <div class="all_bill" style="margin-top:0px">

        <div class="ship_add" style="display:none;">Billing Address</div>

        <div class="m_con" style="display:none;">

          <input type="checkbox" name="shipaddress" id="shipaddress" value="1" />

          <span class="fontBrick" style="padding-left:10px;">Click here if your shipping and billing address are different.</span></div>

       

       <?php 

	   		/*

	   ?>

        <div class="inv-head" ><!-- 30_01_2014 -->          

          <div class="nam1">Are you requesting for a quote/invoice<span class="fontRed">*</span></div>

        </div>

        <div class="inv-data" ><!-- 30_01_2014 -->          

          <select class="verd2" name="type">            

            <!--<option value="invoice">INVOICE</option>--><!-- 30_01_2014 -->            

            <option value="quote" selected="selected">QUOTE</option>

          </select>

        </div>

        <?php 

		*/

		?>

      </div>

      

      

      <!--section start for shipping--->

      

      <div id="ship_info" style="display:none;">

        <div class="ship_add">Shipping Address Information</div>

        <div class="comp-head">

          <div class="nam1">Company:</div>

        </div>

        <div class="comp-data">

          <input type="text" id="comp_val_ship" name="comp_val_ship" class="bil-nput" />

        </div>

        <div class="name-head">

          <div class="nam1">First Name:<span class="fontRed">*</span></div>

          <div class="nam1">Last Name:<span class="fontRed">*</span></div>

        </div>

        <div class="name-data"><span class="nput1">

          <input type="text" id="fnameship" name="fnameship" />

          </span><span class="nput2">

          <input type="text" id="lnameship" name="lnameship" />

          </span></div>

        <div class="bill-head">

          <div class="nam1">Shipping:<span class="fontRed">*</span></div>

        </div>

        <div class="bill-data">

          <input type="text" id="add1ship" name="add1ship" class="bil-nput" />

          <input type="text" id="add2ship" name="add2ship" class="bil-nput" />

        </div>

        <div class="loc-head">

          <div class="nam1">City:<span class="fontRed">*</span></div>

          <div class="nam2">State:<span class="fontRed">*</span></div>

        </div>

        <div class="loc-data">

        

        <span class="nput1">

          <input type="text" id="cityship" name="cityship" />

          </span><span class="nput2">

          <?php

						$store1 = Mage::getModel('core/store')->load($_store_id);

						Mage::app($store1->getCode());

						 

						$countrycode = Mage::getStoreConfig('general/country/default',$store1);

						

						$statearray = Mage::getModel('directory/region')->getResourceCollection() ->addCountryFilter(trim($countrycode,' '))->load();

						

						$vvl="";

						 foreach ($statearray as $_state) {

						    $vvl=trim($_state->getCode());

						    break;

						 }

						

						if($vvl!="")

						{

					    ?>

          <select name="stateship" id="stateship" class="contenta">

            <option value="" selected="">Choose State</option>

            <?php

							/***************** start 28_01_2014 **********************/

							 //$countrycode = 'AU';

							$countrycode = Mage::getStoreConfig('general/country/default',$store1);

							  

	

							  $statearray = Mage::getModel('directory/region')->getResourceCollection() ->addCountryFilter(trim($countrycode,' '))->load();

								 foreach ($statearray as $_state) {

								     echo "<option value='" . $_state->getCode() . "'>" .  $_state->getDefaultName() . "</option>";

								 }

							  /***************** end 28_01_2014 **********************/

							?>

          </select>

          <?php

						}

						else

						{

					    ?>

          <input type="text" id="stateship" name="stateship" value="" />

          <?php

						}

					    ?>

          </span></div>

        <div class="coun-head">

          <div class="nam1">Postcode:<span class="fontRed">*</span></div>

        </div>

        <div class="coun-data"><span class="nput1">

          <input type="text" id="zipship" name="zipship" />

          <input type="text" id="type" name="type" value="quote" />

          

          <span class="error_labels" id="fname_lbl">Please enter proper zip code </span>

          

          </span></div>

      </div>

    

    


    

           

      <!--section end for shipping-->

      

      

      <div class="pord-pic" style="width: 80%; margin-left: 35%;">

        <button class="btn_reset" name="btn_reset" type="reset" ></button>

        <input  class="btn_submit"  onClick="submitOrder(this);" name="sub_cusord" type="button" id="sub_cusord" value=" " >

        </button>

        

        <!-- <input type="button" name="sub_cusord" id="sub_cusord" value="" />-->

        

        <img id="loader_id" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/default/default/images/externalform/ajax-loader.gif" style="width:30px; height:30px; display:none;" /></div>

    </div>

    <input type="hidden" name="action" value="post_order">

    <input type="hidden" name="actionUrl" id="actionUrl" value="<?php echo Mage::getBaseUrl() ?>index.php/externalform/index/placeOrder/" />

    

    <!--------------------------------------------------------------->

    

    

  </form>

  

</div>


<script>

  //function reset input fields

  

  function resetField(cobj){

	  

	 	 jQuery('#'+cobj.id).css("border","1px solid #ccc");

		 jQuery('.error_labels').hide('slide');

		 

		// console.log(cobj.id);

	  

	  }

	 

	 ///update captcha code and refresh page// 

	 

	 function updateCaptcha(){

		 

		 var captchaurl = '<?php echo Mage::getBaseUrl() ?>index.php/externalform/index/refreshcpatcha';

		 var params={form_key:'<?php echo Mage::getSingleton('core/session')->getFormKey();?>',}

		 jQuery.ajax({

			 

			 url: captchaurl,

			type: "POST",

			dataType:"JSON",					

			data: params,

			beforeSend: function(){

				jQuery('#captcha_loader').show();

				},

			success: function(data){

				//console.log(data.newtext);

				

				document.getElementById('captcha_value').value=data.newtext;

				 document.getElementById('captcha').src='<?php echo Mage::getBaseUrl(); ?>externalform/captcha.php?ts=<?php echo time(); ?>&text='+data.newtext; 

				 document.getElementById('captcha-form').focus();

				 jQuery('#captcha_loader').hide();

				

				},			

			

			 });

		 

		 }

  

            

function submitOrder(){

             var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

        	 var address = document.getElementById("emailbill").value;

        		// if(jQuery("#creditcardtype").attr("value")=="0")

        		// {

        		//		  jQuery("#creditcardtype").css("border","1px solid #fd0402");

        		//		  jQuery("#creditcardtype").focus();

        		//		  return false;

        		// }

        		// else

        		// {

        		//		  jQuery("#creditcardtype").css("border","3px solid #2F2F2F");

        		// }

        		// 

        		// if(jQuery("#creditcardNum").attr("value")=="")

        		// {

        		//		  jQuery("#creditcardNum").css("border","1px solid #fd0402");

        		//		  jQuery("#creditcardNum").focus();

        		//		  return false;

        		// }

        		// else

        		// {

        		//		  jQuery("#creditcardNum").css("border","3px solid #2F2F2F");

        		// }

        		// 

        		// if(jQuery("#ccVerNum").attr("value")=="")

        		// {

        		//		  jQuery("#ccVerNum").css("border","1px solid #fd0402");

        		//		  jQuery("#ccVerNum").focus();

        		//		  return false;

        		// }

        		// else

        		// {

        		//		  jQuery("#ccVerNum").css("border","3px solid #2F2F2F");

        		// }

                

				var formElements = {

								 // comp_val:{comp_lbl:'Please fill company field properly'},

								   fnamebill:{fname_lbl:'Please fill First name field properly'}, 

								   lnamebill:{lname_lbl:'Please fill Lastname field properly'},

								   phonebill:{phone_lbl:'Please fill Phone filed propelry'},

								   emailbill:{email_lbl:'Please fill email field properly'},

								   conemailbill:{conemail_lbl:'Please enter properly confirm email field'},

								/*   del_date:{del_lbl:'Please Enter Valid Date '}, */

							//	   add1bill:{add1_lbl:'Please fill proper address for shipping order'},

							//   citybill:{country_lbl:'Please select proper country'},

							//	   citybill:{city_lbl:'Please fill proper city'},

							//	   statebill:{state_lbl:'Please Select a valid state'},

							//	   zipbill:{zip_lbl:'Please enter proper zip code'},

								   

								  // 'captcha-form':{captcha_lbl:'Please provide valid captcha code'},

				    }

				

				//console.log(formElements);

				

				var flag = 0;

				

				jQuery.each(formElements, function(key, val){

					// console.log('key='+key+'  val='+val);

					///check if input fields are empty	

					// console.log(jQuery('#'+key).val());

									

						if(jQuery('#'+key).val()==""){

							//alert(val.comp_lbl);

							jQuery.each(val, function(indx, msg){

								jQuery('#'+indx).show('slide');

								alert(msg);

								});							

							jQuery('#'+key).css("border","4px solid #fd0402");

							jQuery('#'+key).focus();

							jQuery('#'+key).select();

							//console.log(key);

							

							flag = 1;

						return false;

					}

						

					///check if phone number is not valid

					if(key=='phonebill' && isNaN(jQuery('#'+key).val())){

						alert('Please enter valid Phone number');						 

						jQuery('#'+'phone_lbl').show('slide');						

						jQuery('#'+key).css("border","3px solid #fd0402");

						jQuery('#'+key).focus();

						jQuery('#'+key).select();

						

						flag = 1;

						

						return false;						

						}	

						

					///check if email is  valid

					if((key=='emailbill' || key=='conemailbill') && (reg.test(jQuery('#'+key).val())==false )){

						 

						alert('Your email is not valid, Please enter valid email');						 

						if(key=='emailbill'){

						jQuery('#'+'email_lbl').show('slide');	

						}else{

							jQuery('#'+'conemail_lbl').show('slide');

							}

						jQuery('#'+key).css("border","3px solid #fd0402");

						jQuery('#'+key).focus();

						jQuery('#'+key).select();

						

						flag = 1;

						

						return false;						

						}

					//check both email address are same		

					  if(  key=='conemailbill' && jQuery('#'+'emailbill').val() != jQuery('#'+'conemailbill').val()){

						  alert('Entered email addresses are not same, please add same email addresses');

						   jQuery('#'+'conemail_lbl').show('slide');							 

							jQuery('#'+key).css("border","3px solid #fd0402");

							jQuery('#'+key).focus();

							jQuery('#'+key).select();

							

							flag = 1;

							

						  return false;

						  }

			

					

					}); ///end of function jquery each

				

	if(flag==1){

		

		return false;

		

		}

	

	/*if(jQuery('#del_date').val()==''){

		return false;

	}*/

	// cat		captcha-form			 prod

     if(jQuery('#captcha-form').val()==''){

		 

		 jQuery("#captcha_lbl").html("You have entered an incorrect captcha code. Try again");

		 jQuery("#captcha_lbl").show();

		 jQuery('#captcha-form').css("border","3px solid #fd0402");

		 jQuery('#captcha-form').focus();

		 jQuery('#captcha-form').select();		 

					     

		 return false;

		 

		 }

          var actionUrl=jQuery("#actionUrl").attr("value");

            //alert(actionUrl);

                         

               jQuery("#loader_id").show();

               jQuery("#sub_cusord").hide();

                         

          /////checking if captcha is ok ///

		  

		  jQuery.ajax({

			url: actionUrl,

			type: "POST",

			dataType:"JSON",					

			data: jQuery("#cus_ordfrm").serialize(),

			

			success: function(resp){

							 

		    if(resp.cap_error== 1)

                 {

                         jQuery("#captcha_lbl").html("You have entered an incorrect captcha code. Try again");

					     jQuery("#loader_id").hide();

                         jQuery("#sub_cusord").show();

						 jQuery("#captcha_lbl").show();

					     jQuery("#captcha-form").attr("value","");

						 jQuery("#captcha-form").css("border","4px solid #fd0402");

					     jQuery("#change-image").trigger("click");

						  

                   return false; 

                }

				

		          //   console.log(resp);

    			ord = resp.id;

	

		if(resp.type=="order")

                 {

                 //location.reload();

                //jQuery("#Success").html("Your order has been placed . Your order id is #"+ord+'. '+stock);

                jQuery("#cus_ordfrm").css("display","none");  

				jQuery("#thank_u").css("display","block");	

                jQuery("#thank_u").html("Thank you for your interest, We will get back to you shortly. Your Invoice number is "+ord);

				document.body.scrollTop = document.documentElement.scrollTop = 0;

				window.top.location.href='<?php echo Mage::getBaseUrl(); ?>index.php/externalform/index/thankyou';

               

		}else if(resp.type=="quote")

    			 {

           //location.reload();

           //jQuery("#Success").html("Your quote has been placed . Your quote id is #"+ord+'. '+stock);

		   jQuery("#cus_ordfrm").css("display","none");  

		   jQuery("#thank_u").css("display","block");

		   jQuery("#thank_u").html("Thank you for your interest, We will get back to you shortly. Your quote number is #"+ord);		

			document.body.scrollTop = document.documentElement.scrollTop = 0;

			window.top.location.href='<?php echo Mage::getBaseUrl(); ?>index.php/externalform/index/thankyou';

            //location.reload();

       		}else{

				  jQuery("#thank_u").html("Something has gone wrong. "+stock);

                  jQuery("#loader_id").hide();

                  jQuery("#sub_cusord").show();

				  jQuery("#thank_u").html(resp.msg);

                }				

				

				

				

				}

			   

          });  

                   

     }

				

				

  function addProductRow(){

                   // alert('Hello ');

				   console.log(<?php echo $_root_category;?>);

				   return false;

					//exit;

                    jQuery.ajax({

                         url: "<?php echo Mage::getBaseUrl();?>index.php/externalform/index/addMore/",

                         type: "POST",

                         data: "store_id=<?php echo $_store_id; ?>&root_cat=<?php echo $_root_category; ?>",

                         success: function(abc){

                                                                 

                                 jQuery("#all_pro_con").append(abc);

                                 

                                 jQuery(".del_it").unbind("click");

                                 jQuery(".del_it").bind("click",del_it);

                         }

                    });

                    

                    

                    

                    

                }		

				

				

            jQuery(document).ready(function(){

		

		

		//Store Previous data start

		

		var comment="comment";

		jQuery("#"+comment).blur(function(){

		    

		

		    setCookie(comment,jQuery("#"+comment).val(),3);   

		    

		    

		});

		if (getCookie(comment)!="")

		{

		   jQuery("#"+comment).val(getCookie(comment)); 

		}

		

		

		var del_date="del_date";

		jQuery("#"+del_date).blur(function(){

		    

		    

		    setCookie(del_date,jQuery("#"+del_date).val(),3);   

		    

		    

		});

		if (getCookie(del_date)!="")

		{

		   jQuery("#"+del_date).val(getCookie(del_date)); 

		}

		

		

	       var shipaddress="shipaddress";

	       

/*               jQuery("#shipaddress").click(function(e){

		

                    if(jQuery('#shipaddress').is(':checked')==true)

                    {

				    

		

		

				     setCookie(shipaddress,1,3);   

                                     

                                     jQuery('#ship_info').attr('style','display:block');

                    }

                    else

                    {

			 

                                     setCookie(shipaddress,"",3);   

                                     jQuery('#ship_info').attr('style','display:none');    

                    }

               });

                

                if (getCookie(shipaddress)!="")

		{

		   jQuery("#"+shipaddress).trigger("click");

		} */

		

		var fnamebill="fnamebill";

		jQuery("#"+fnamebill).blur(function(){

	    setCookie(fnamebill,jQuery("#"+fnamebill).val(),3);   

		});

		if (getCookie(fnamebill)!="")

		{

		   jQuery("#"+fnamebill).val(getCookie(fnamebill)); 

		}

		var lnamebill="lnamebill";

		jQuery("#"+lnamebill).blur(function(){

	    setCookie(lnamebill,jQuery("#"+lnamebill).val(),3);   

		});

		if (getCookie(lnamebill)!="")

		{

		   jQuery("#"+lnamebill).val(getCookie(lnamebill)); 

		}

		var comp_val="comp_val";

		jQuery("#"+comp_val).blur(function(){

	    setCookie(comp_val,jQuery("#"+comp_val).val(),3);   

		});

		if (getCookie(comp_val)!="")

		{

		   jQuery("#"+comp_val).val(getCookie(comp_val)); 

		}

		var add1bill="add1bill";

		jQuery("#"+add1bill).blur(function(){

	    setCookie(add1bill,jQuery("#"+add1bill).val(),3);   

		});

		if (getCookie(add1bill)!="")

		{

		   jQuery("#"+add1bill).val(getCookie(add1bill)); 

		}

/*		var add2bill="add2bill";

		jQuery("#"+add2bill).blur(function(){

	    setCookie(add2bill,jQuery("#"+add2bill).val(),3);   

		});

		if (getCookie(add2bill)!="")

		{

		   jQuery("#"+add2bill).val(getCookie(add2bill)); 

		}*/

		var citybill="citybill";

		jQuery("#"+citybill).blur(function(){

	    setCookie(citybill,jQuery("#"+citybill).val(),3);   

		});

		if (getCookie(citybill)!="")

		{

		   jQuery("#"+citybill).val(getCookie(citybill)); 

		}

		var statebill="statebill";

		jQuery("#"+statebill).blur(function(){

	    setCookie(statebill,jQuery("#"+statebill).val(),3);   

		});

		if (getCookie(statebill)!="")

		{

		   jQuery("#"+statebill).val(getCookie(statebill));

		   jQuery("#"+statebill+" [value='"+getCookie(statebill)+"']").attr("selected","selected"); 

		}

		var zipbill="zipbill";

		jQuery("#"+zipbill).blur(function(){

		    setCookie(zipbill,jQuery("#"+zipbill).val(),3);   

		});

		if (getCookie(zipbill)!="")

		{

		   jQuery("#"+zipbill).val(getCookie(zipbill));

		}

		var phonebill="phonebill";

		jQuery("#"+phonebill).blur(function(){

	    setCookie(phonebill,jQuery("#"+phonebill).val(),3);   

		});

		if (getCookie(phonebill)!="")

		{

		   jQuery("#"+phonebill).val(getCookie(phonebill));

		}

		var emailbill="emailbill";

		jQuery("#"+emailbill).blur(function(){

	    setCookie(emailbill,jQuery("#"+emailbill).val(),3);   

		});

		if (getCookie(emailbill)!="")

		{

		   jQuery("#"+emailbill).val(getCookie(emailbill));

		}

		var conemailbill="conemailbill";

		jQuery("#"+conemailbill).blur(function(){

	    setCookie(conemailbill,jQuery("#"+conemailbill).val(),3);   

		});

		if (getCookie(conemailbill)!="")

		{

		   jQuery("#"+conemailbill).val(getCookie(conemailbill));

		}

		

/*		var fnameship="fnameship";

		jQuery("#"+fnameship).blur(function(){

	    setCookie(fnameship,jQuery("#"+fnameship).val(),3);   

		});

		if (getCookie(fnameship)!="")

		{

    	   jQuery("#"+fnameship).val(getCookie(fnameship));

		}

		var lnameship="lnameship";

		jQuery("#"+lnameship).blur(function(){

	    setCookie(lnameship,jQuery("#"+lnameship).val(),3);   

		});

		if (getCookie(lnameship)!="")

		{

    	   jQuery("#"+lnameship).val(getCookie(lnameship));

		}

		var comp_val_ship="comp_val_ship";

		jQuery("#"+comp_val_ship).blur(function(){

	    setCookie(comp_val_ship,jQuery("#"+comp_val_ship).val(),3);   

		});

		if (getCookie(comp_val_ship)!="")

		{

		   jQuery("#"+comp_val_ship).val(getCookie(comp_val_ship));

		}

		var add1ship="add1ship";

		jQuery("#"+add1ship).blur(function(){

	    setCookie(add1ship,jQuery("#"+add1ship).val(),3);   

		});

		if (getCookie(add1ship)!="")

		{

		   jQuery("#"+add1ship).val(getCookie(add1ship));

		}

		var add2ship="add2ship";

		jQuery("#"+add2ship).blur(function(){

	    setCookie(add2ship,jQuery("#"+add2ship).val(),3);   

		});

		if (getCookie(add2ship)!="")

		{

		   jQuery("#"+add2ship).val(getCookie(add2ship));

		}

		var cityship="cityship";

		jQuery("#"+cityship).blur(function(){

	    setCookie(cityship,jQuery("#"+cityship).val(),3);   

		});

		if (getCookie(cityship)!="")

		{

		   jQuery("#"+cityship).val(getCookie(cityship));

		}

		var stateship="stateship";

		jQuery("#"+stateship).blur(function(){

	    setCookie(stateship,jQuery("#"+stateship).val(),3);   

		});

		if (getCookie(stateship)!="")

		{

		   jQuery("#"+stateship).val(getCookie(stateship));

		   jQuery("#"+stateship+" [value='"+getCookie(stateship)+"']").attr("selected","selected"); 

		}

		var zipship="zipship";

		jQuery("#"+zipship).blur(function(){

	    setCookie(zipship,jQuery("#"+zipship).val(),3);   

		});

		if (getCookie(zipship)!="")

		{

		   jQuery("#"+zipship).val(getCookie(zipship));

		}

		var phoneship="phoneship";

		jQuery("#"+phoneship).blur(function(){

	    setCookie(phoneship,jQuery("#"+phoneship).val(),3);   

		});

		if (getCookie(phoneship)!="")

		{

		   jQuery("#"+phoneship).val(getCookie(phoneship));

		} */

		

		//Store Previous data end

// add more product row code starts here.

		initLightbox();

                jQuery("#downloads_video_overlay").css("display","none");

               

			    jQuery("#add_more").click(function(){

                    

                    jQuery.ajax({

                         url: "<?php echo Mage::getBaseUrl();?>index.php/externalform/index/addMore/",

                         type: "POST",

                         data: "store_id=<?php echo $_store_id; ?>&root_cat=<?php echo $_root_category; ?>",

						 beforeSend: function(){

							 jQuery('#new_product_add').show();

							 },

                         success: function(abc){

                                                                 

                                 jQuery("#all_pro_con").append(abc);

                                 

                                 jQuery(".del_it").unbind("click");

                                 jQuery(".del_it").bind("click",del_it);

								 jQuery('#new_product_add').hide();

                         }

                    });

                    

                    

                    

                    

                });

                

                

// add more product code ends here.

                

// order submit button click code starts here.

              

				

				

// order submit button click code ends here.				

                jQuery(".del_it").unbind("click");

                jQuery(".del_it").bind("click",del_it);

            });

            

// get product ajax call funciton code starts here.

               function getProduct(catid,curr_ele){

                    

                    

                    var param="catid="+catid+"&storeid="+'<?php echo $_store_id?>';

					

					//console.log(param);

					

                    jQuery.ajax({

                           type:'POST',

                           url:'<?php echo Mage::getBaseUrl();?>index.php/externalform/index/getProduct/',

                           data:param,

						   beforeSend: function(){

							  

							   jQuery(curr_ele).parent().parent().parent().find("#load_product").show();

							   },

                          

                           success: function(ret){

                           

                           	//alert(ret);				

                              jQuery(curr_ele).parent().parent().parent().find(".proddiv").html(ret);             

                              jQuery(curr_ele).parent().parent().parent().find("#load_product").hide();

                            }

                            

              

                });

                }

                

// get product ajax call funciton code ends here.

// get product Image ajax call funciton code starts here.                   

                function getProdImage(prodid,curr_ele){

                    

                    var param="prodid="+prodid;

                    jQuery.ajax({

                           type:'POST',

                           url:'<?php echo Mage::getBaseUrl();?>index.php/externalform/index/getProductImage/',

                           data:param,

						   beforeSend: function(){

							     jQuery(curr_ele).parent().parent().parent().find("#load_image").show();

							   

							   },

                          

                           success: function(ret)

                           {

                             //alert(ret);                           

                              //jQuery('#prodimgdiv').html(ret);

                              jQuery(curr_ele).parent().parent().parent().find(".prodimgdiv").html(ret);

             		      

                              initLightbox();

							  jQuery(curr_ele).parent().parent().parent().find("#load_image").hide();

                            }

                            

              

                });

            }

// get product Image ajax call funciton code ends here.                               

// delete product row ajax call funciton code starts here.                   

            function del_it()

            {

                jQuery(this).parent().parent().remove();

            }

// get product Image ajax call funciton code ends here.                            

        </script>

<style type="text/css">

.ds_box {

	background-color: #FFF;

	border: 1px solid #000;

	position: absolute;

	z-index: 32767;

}

.ds_tbl {

	background-color: #FFF;

}

.ds_head {

	background-color: #333;

	color: #FFF;

	font-family: Arial, Helvetica, sans-serif;

	font-size: 13px;

	font-weight: bold;

	text-align: center;

	letter-spacing: 2px;

}

.ds_subhead {

	background-color: #CCC;

	color: #000;

	font-size: 12px;

	font-weight: bold;

	text-align: center;

	font-family: Arial, Helvetica, sans-serif;

	width: 32px;

}

.ds_cell {

	background-color: #EEE;

	color: #000;

	font-size: 13px;

	text-align: center;

	font-family: Arial, Helvetica, sans-serif;

	padding: 5px;

	cursor: pointer;

}

.ds_cell:hover {

	background-color: #F3F3F3;

} /* This hover code won't work for IE */

</style>

</head>

<body>

<table class="ds_box" cellpadding="0" cellspacing="0" id="ds_conclass" style="display: none;">

  <tr>

    <td id="ds_calclass"></td>

  </tr>

</table>

<script type="text/javascript">

// <!-- <![CDATA[

// Project: Dynamic Date Selector (DtTvB) - 2006-03-16

// Script featured on JavaScript Kit- http://www.javascriptkit.com

// Code begin...

// Set the initial date.

var ds_i_date = new Date();

ds_c_month = ds_i_date.getMonth() + 1;

ds_c_year = ds_i_date.getFullYear();

// Get Element By Id

function ds_getel(id) {

	return document.getElementById(id);

}

// Get the left and the top of the element.

function ds_getleft(el) {

	var tmp = el.offsetLeft;

	el = el.offsetParent

	while(el) {

		tmp += el.offsetLeft;

		el = el.offsetParent;

	}

	return tmp;

}

function ds_gettop(el) {

	var tmp = el.offsetTop;

	el = el.offsetParent

	while(el) {

		tmp += el.offsetTop;

		el = el.offsetParent;

	}

	return tmp;

}

// Output Element

var ds_oe = ds_getel('ds_calclass');

// Container

var ds_ce = ds_getel('ds_conclass');

// Output Buffering

var ds_ob = ''; 

function ds_ob_clean() {

	ds_ob = '';

}

function ds_ob_flush() {

	ds_oe.innerHTML = ds_ob;

	ds_ob_clean();

}

function ds_echo(t) {

	ds_ob += t;

}

var ds_element; // Text Element...

var ds_monthnames = [

'January', 'February', 'March', 'April', 'May', 'June',

'July', 'August', 'September', 'October', 'November', 'December'

]; // You can translate it for your language.

var ds_daynames = [

'Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'

]; // You can translate it for your language.

// Calendar template

function ds_template_main_above(t) {

	return '<table cellpadding="3" cellspacing="1" class="ds_tbl">'

	     + '<tr>'

		 + '<td class="ds_head" style="cursor: pointer" onclick="ds_py();"><<</td>'

		 + '<td class="ds_head" style="cursor: pointer" onclick="ds_pm();"><</td>'

		 + '<td class="ds_head" style="cursor: pointer" onclick="ds_hi();" colspan="3">[Close]</td>'

		 + '<td class="ds_head" style="cursor: pointer" onclick="ds_nm();">></td>'

		 + '<td class="ds_head" style="cursor: pointer" onclick="ds_ny();">>></td>'

		 + '</tr>'

	     + '<tr>'

		 + '<td colspan="7" class="ds_head">' + t + '</td>'

		 + '</tr>'

		 + '<tr>';

}

function ds_template_day_row(t) {

	return '<td class="ds_subhead">' + t + '</td>';

	// Define width in CSS, XHTML 1.0 Strict doesn't have width property for it.

}

function ds_template_new_week() {

	return '</tr><tr>';

}

function ds_template_blank_cell(colspan) {

	return '<td colspan="' + colspan + '"></td>'

}

function ds_template_day(d, m, y) {

	return '<td class="ds_cell" onclick="ds_onclick(' + d + ',' + m + ',' + y + ')">' + d + '</td>';

	// Define width the day row.

}

function ds_template_main_below() {

	return '</tr>'

	     + '</table>';

}

// This one draws calendar...

function ds_draw_calendar(m, y) {

	// First clean the output buffer.

	ds_ob_clean();

	// Here we go, do the header

	ds_echo (ds_template_main_above(ds_monthnames[m - 1] + ' ' + y));

	for (i = 0; i < 7; i ++) {

		ds_echo (ds_template_day_row(ds_daynames[i]));

	}

	// Make a date object.

	var ds_dc_date = new Date();

	ds_dc_date.setMonth(m - 1);

	ds_dc_date.setFullYear(y);

	ds_dc_date.setDate(1);

	if (m == 1 || m == 3 || m == 5 || m == 7 || m == 8 || m == 10 || m == 12) {

		days = 31;

	} else if (m == 4 || m == 6 || m == 9 || m == 11) {

		days = 30;

	} else {

		days = (y % 4 == 0) ? 29 : 28;

	}

	var first_day = ds_dc_date.getDay();

	var first_loop = 1;

	// Start the first week

	ds_echo (ds_template_new_week());

	// If sunday is not the first day of the month, make a blank cell...

	if (first_day != 0) {

		ds_echo (ds_template_blank_cell(first_day));

	}

	var j = first_day;



	for (i = 0; i < days; i ++) {

		// Today is sunday, make a new week.

		// If this sunday is the first day of the month,

		// we've made a new row for you already.

		if (j == 0 && !first_loop) {

			// New week!!

			ds_echo (ds_template_new_week());

		}

		// Make a row of that day!

		ds_echo (ds_template_day(i + 1, m, y));

		// This is not first loop anymore...

		first_loop = 0;

		// What is the next day?

		j ++;

		j %= 7;

	}

	// Do the footer

	ds_echo (ds_template_main_below());

	// And let's display..

	ds_ob_flush();

	// Scroll it into view.

	ds_ce.scrollIntoView();

}

// A function to show the calendar.

// When user click on the date, it will set the content of t.

function ds_sh(t) {

	// Set the element to set...

	ds_element = t;

	// Make a new date, and set the current month and year.

	var ds_sh_date = new Date();

	ds_c_month = ds_sh_date.getMonth() + 1;

	ds_c_year = ds_sh_date.getFullYear();

	// Draw the calendar

	ds_draw_calendar(ds_c_month, ds_c_year);

	// To change the position properly, we must show it first.

	ds_ce.style.display = '';

	// Move the calendar container!

	the_left = ds_getleft(t);

	the_top = ds_gettop(t) + t.offsetHeight;

	ds_ce.style.left = the_left+ 'px';

	ds_ce.style.top = the_top+ 'px';

	// Scroll it into view.

	//ds_ce.scrollIntoView();

}

// Hide the calendar.

function ds_hi() {

	ds_ce.style.display = 'none';

}

// Moves to the next month...

function ds_nm() {

	// Increase the current month.

	ds_c_month ++;

	// We have passed December, let's go to the next year.

	// Increase the current year, and set the current month to January.

	if (ds_c_month > 12) {

		ds_c_month = 1; 

		ds_c_year++;

	}

	// Redraw the calendar.

	ds_draw_calendar(ds_c_month, ds_c_year);

}

// Moves to the previous month...

function ds_pm() {

	ds_c_month = ds_c_month - 1; // Can't use dash-dash here, it will make the page invalid.

	// We have passed January, let's go back to the previous year.

	// Decrease the current year, and set the current month to December.

	if (ds_c_month < 1) {

		ds_c_month = 12; 

		ds_c_year = ds_c_year - 1; // Can't use dash-dash here, it will make the page invalid.

	}

	// Redraw the calendar.

	ds_draw_calendar(ds_c_month, ds_c_year);

}

// Moves to the next year...

function ds_ny() {

	// Increase the current year.

	ds_c_year++;

	// Redraw the calendar.

	ds_draw_calendar(ds_c_month, ds_c_year);

}

// Moves to the previous year...

function ds_py() {

	// Decrease the current year.

	ds_c_year = ds_c_year - 1; // Can't use dash-dash here, it will make the page invalid.

	// Redraw the calendar.

	ds_draw_calendar(ds_c_month, ds_c_year);

}

// Format the date to output.

function ds_format_date(d, m, y) {

	// 2 digits month.

	m2 = '00' + m;

	m2 = m2.substr(m2.length - 2);

	// 2 digits day.

	d2 = '00' + d;

	d2 = d2.substr(d2.length - 2);

	// YYYY-MM-DD

	return y + '-' + m2 + '-' + d2;

}

// When the user clicks the day.

function ds_onclick(d, m, y) {

	// Hide the calendar.

	ds_hi();

	// Set the value of it, if we can.

	if (typeof(ds_element.value) != 'undefined') {

		ds_element.value = ds_format_date(d, m, y);

	// Maybe we want to set the HTML in it.

	} else if (typeof(ds_element.innerHTML) != 'undefined') {

		ds_element.innerHTML = ds_format_date(d, m, y);

	// I don't know how should we display it, just alert it to user.

	} else {

		alert (ds_format_date(d, m, y));

	}

}

// And here is the end.

// ]]> -->

function setCookie(cname,cvalue,exdays)

{

    var d = new Date();

    d.setTime(d.getTime()+(exdays*24*60*60*1000));

    var expires = "expires="+d.toGMTString();

    document.cookie = cname + "=" + cvalue + "; " + expires;

}

function getCookie(cname)

{

    var name = cname + "=";

    var ca = document.cookie.split(';');

    for(var i=0; i<ca.length; i++) 

      {

      var c = ca[i].trim();

      if (c.indexOf(name)==0) return c.substring(name.length,c.length);

      }

    return "";

}

</script> 