<?php
$helper = Mage::helper('iwd_ordermanager');
$order = $this->getOrder();
$current_status = $order->getStatus();
$current_state = $order->getState();
$statuses = $this->getStatusList();
$states = $this->getStateList();
$website_store_view = Mage::getSingleton('adminhtml/system_store')->getStoreValuesForForm(false, false);
$allow_change_state = Mage::getModel('iwd_ordermanager/order')->isAllowChangeOrderState();
?>

<form id="order_information_form" method="post">
    <?php if ($allow_change_state): ?>
        <div>
            <ul class="messages">
                <li class="notice-msg">
                    <?php echo $helper->__('Do not change the "Order State", if you are unsure of this action.'); ?>
                    <?php echo $helper->__("Taxes will not be recalculated."); ?>
                </li>
            </ul>
        </div>
    <?php endif; ?>

    <table cellspacing="0" class="form-list form-edit-order">
        <tbody>
        <tr>
            <td class="label"><label for="status"><?php echo $helper->__("Order Status"); ?><span
                        class="required">*</span></label></td>
            <td class="value">
                <select name="status" class="required-entry required-entry select validation-passed">
                    <?php foreach ($statuses as $status): ?>
                        <option
                            value="<?php echo $status['status'] ?>"
                            <?php if ($status['status'] == $current_status) echo 'selected = "selected"'; ?>>
                            <?php echo $status['label']; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </td>
        </tr>
        <?php if ($allow_change_state): ?>
            <tr>
                <td class="label"><label for="state"><?php echo $helper->__("Order State"); ?><span
                            class="required">*</span></label></td>
                <td class="value">
                    <select name="state" class="required-entry required-entry select validation-passed">
                        <?php foreach ($states as $id => $label): ?>
                            <option
                                value="<?php echo $id ?>"
                                <?php if ($id == $current_state) echo 'selected = "selected"'; ?>>
                                <?php echo $label; ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
        <?php endif; ?>
        <tr>
            <td class="label">
                <label for="state"><?php echo $helper->__("Purchased From"); ?><span class="required">*</span></label>
            </td>
            <td class="value">
                <select name="store_id">
                    <?php foreach (Mage::app()->getWebsites() as $website): ?>
                        <optgroup label="<?php echo $website->getName(); ?>"></optgroup>
                        <?php foreach ($website->getGroups() as $group): ?>
                            <optgroup label="&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $group->getName(); ?>"></optgroup>
                            <?php foreach ($group->getStores() as $view): ?>
                                <option value="<?php echo $view->getId(); ?>"
                                        <?php if($view->getId() == $order->getStoreId()): ?>
                                            selected="selected"
                                        <?php endif; ?>
                                >
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $view->getName(); ?>
                                </option>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </select>
            </td>
        </tr>
        </tbody>
    </table>

    <div style="margin-top:20px">
        <input type="hidden" value="<?php echo $order->getEntityId(); ?>" name="order_id"
               id="order_id_<?php echo $order->getEntityId(); ?>">
        <button id="iwd_edit_order_form_cancel" class="scalable" type="button"
                onclick="IWD.OrderManager.OrderInfo.editOrderInformationCancel()"
                title="<?php echo $helper->__("Cancel"); ?>">
            <?php echo $helper->__("Cancel"); ?>
        </button>
        <button id="iwd_edit_order_form_submit" class="scalable right" type="button"
                onclick="IWD.OrderManager.OrderInfo.editOrderInformationSubmit()"
                title="<?php echo $helper->__("Update"); ?>">
            <?php echo $helper->__("Update"); ?>
        </button>
        <label style="float:right; margin-right:10px">
            <input type="checkbox" name="confirm_edit" <?php echo $helper->isConfirmEditChecked(); ?>/>
            <?php echo $helper->__('Confirm Update'); ?>
        </label>
        <!--<label style="float:right; margin-right:20px">
            <input type="checkbox" name="recalculate_amount" <?php echo $helper->isRecalculateOrderAmountChecked(); ?>/>
            <?php echo $helper->__('Recalculate order amount'); ?>
        </label>-->
    </div>
</form>
