<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/artworkupload.css');?>" media="all" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/popup.css');?>" media="all" />
<!--<script src="<?php echo $this->getJsUrl('upload/jquery-1.9.1.min.js');?>"></script>-->
<script src="<?php echo $this->getJsUrl('upload/jquery.js');?>"></script> 
<script src="<?php echo $this->getJsUrl('upload/jquery.form.js');?>"></script>

<?php  //main order
		  $_order =$order;
		 // print_r($_order);	
		 // exit;
  $_customer_name =$_order['customer_prefix'].' '. $_order['customer_firstname'].' '.$_order['customer_middlename'].' '.$_order['customer_lastname'];
  $_order_number = $_order['increment_id'];
  $_customer_email = $_order['customer_email'];
 /*get store info from the order object*/
  $_store_id = $_order['store_id'];
  $_store_info = Mage::getModel('core/store')->load( $_order['store_id']);
  $_c_store_name =$_store_info->getCode();
 
 
  $_short_order_id  =$_order['entity_id'];
 // $_customer = Mage::getModel('customer/customer')->load($_order_number);
  $_user_id  = 0;
  $_user_type='customer';
 
  /*customer id */
  $_customer_id = $_order['customer_id'];
  $_order_type='order';
 
   if(!$_customer_id){$_customer_id=0;}
  
 
  
 /*getting session variable either the customer 
 and admin/designers are live and logged in for for live chat */
  

  
?>
 
<script>
 function openFileOption(id)
{
  document.getElementById(id).click();
  
 }	


///opening after changeing the file conetns
function changeImg(id){	
  
	}
	
///main jQuery Function/////	 
	
	jQuery(function(){
			
	
	jQuery('.uploadFile').change(function(event){
		 
		 
		 //console.log(event.target.id);
		 var previewClass = event.target.id;
		 var idStart = previewClass.indexOf('[');
		 var idEnd = previewClass.indexOf(']');
		  var currentId =previewClass.substring(idStart+1,idEnd);		 
		
		 console.log(currentId);
		 
		//alert(currentId);
		
		//$rowCounter = document.getElementById('rowCounter_'+currentId);
		/*fetch value of the input box*/		
		//$counter = $rowCounter.value;
		//$rowCounter.value = parseInt($counter)+1;
		
		//$newCounter = parseInt($rowCounter.value);
		
		 jQuery('#current_sel_artwork_'+currentId).hide();
		 jQuery('#preview_'+currentId).show();
		 
		 var preview = jQuery('#preview_'+currentId+' img');
		 
		 
		 
		 var input = jQuery(event.currentTarget);
   		 var file = input[0].files[0];
   		 var reader = new FileReader();
   		
		 reader.onload = function(e){
       	 image_base64 = e.target.result;       	
		 
		 var fileType = file['type'];
			
			/*images loading for if not jpg or png*/
		 var file_icons = {
			              zip_icon:'<?php echo $this->getUrl();?>media/upload/fileicons/rar_icon.png',
						  xlxs_icon:'<?php echo $this->getUrl();?>media/upload/fileicons/xlxs_icon.png',
						  docx_icon:'<?php echo $this->getUrl();?>media/upload/fileicons/docx_icon.png',
						  pdf_icon:'<?php echo $this->getUrl();?>media/upload/fileicons/pdf_icon.png',
						  ttf_icon:'<?php echo $this->getUrl();?>media/upload/fileicons/ttf_icon.png',
						  psd_icon:'<?php echo $this->getUrl();?>media/upload/fileicons/psd_icon.png',
						  ai_icon:'<?php echo $this->getUrl();?>media/upload/fileicons/ai_icon.png',
						  fla_icon:'<?php echo $this->getUrl();?>media/upload/fileicons/fla_icon.png',
						  txt_icon:'<?php echo $this->getUrl();?>media/upload/fileicons/txt_icon.png',
						  
		 				   
						  }
		
			//console.log(file);
			if(fileType=='application/zip'){
			
			 preview.attr("src", file_icons['zip_icon']);
			//console.log(file_icons);
			
			}else if(fileType=='application/rar'){
			
			 preview.attr("src", file_icons['zip_icon']);
				//console.log(preview);
			}else if(fileType=='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'){
			
			 preview.attr("src", file_icons['xlxs_icon']);
				//console.log(preview);
			}else if(fileType=='application/vnd.openxmlformats-officedocument.wordprocessingml.document'){
				preview.attr("src", file_icons['docx_icon']);				
			}else if(fileType=='application/pdf'){
					preview.attr("src", file_icons['pdf_icon']);
					 
			}else if(fileType=='application/plain'){
					preview.attr("src", file_icons['txt_icon']);
			
			}else if(fileType==''){
					
					 file_name = file['name'];					
					 file_ext = file_name.split('.');					
					 total_ext=file_ext.length;
					 var file_extension = file_ext[total_ext-1];
					 					
					 // console.log(file_extension);
					  
					 if(file_extension == 'psd'){					
						preview.attr("src", file_icons['psd_icon']);
					 }
					 if(file_extension == 'ai'){					
						preview.attr("src", file_icons['ai_icon']);
					 }
					 if(file_extension == 'fla'){					
						preview.attr("src", file_icons['psd_icon']);
					 }
					 if(file_extension == 'rar'){					
						preview.attr("src", file_icons['rar_icon']);
					 }
					 if(file_extension == 'zip'){					
						preview.attr("src", file_icons['rar_icon']);
					 }
		}else{
				preview.attr("src", image_base64);
			} 
			console.log(file);
					
		 };
   		  reader.readAsDataURL(file);		
		 //console.log(currentId);
		
		cFileSize = parseInt(file['size']);
		kb = 1024;
		mb = 1024*kb;
		cFileSize = cFileSize/mb;
		
		//jQuery('#filename_'+currentId).html('<b>File:</b>'+file['name']);
		//jQuery('#fileSize_'+currentId).html('<b>File Size:</b>'+cFileSize.toFixed(2)+' MB');
		
		/*fileDataVars*/
		//cFile = jQuery('.cfile'+currentId);
		
		var items = currentId.split('_');
		var item_id = items[0];
		var file_id = items[1];
		
		//console.log(file);
		
		var fileDataVars = {
							
							fileid:file_id,
							filename:file['name'],
							file_type:file['type'],
							file_size:file['size'],
							fullPath:file['mozFullPath'],
							short_order_id:<?php echo $_short_order_id;?>,	
							order_id:<?php echo $_order_number;?>,
							store_id:<?php echo $_store_id;?>,
							proof_type:'customer',
							user_id:<?php echo $_user_id;?>,
							user_type:'<?php echo $_user_type;?>',
							item_id:item_id,					
							
						}
							
		/*writing chat data to file via ajax*/
			  
			  
			  jQuery.ajax(
			     { 
				  url:'<?php echo Mage::getUrl('upload/index/uploadfile')?>', 
				  type:'POST',
				  data: fileDataVars,
				  dataType:"HTML",
                  beforeSend: function(xhr) { 
   						 //console.log(xhr);
						},
				  success: function(data){
					  	console.log(data);
					  },
					  
				 }
			  );
		  
		  // console.log(jQuery('submit_form_1011_10'));
		 	////uplaoding files////
			
			jQuery('#submit_form_'+item_id+'_'+file_id).ajaxSubmit(
			{
				beforeSend:function(){
					//console.log('uploading');
					var pWidth=0;
					jQuery('#file_info_'+item_id+'_'+file_id).show();
					jQuery('#file_info_progress_bar_'+item_id+'_'+file_id).show();
					var image = '<div style="width:100%;text-align:center;"><img src="<?php echo $this->getUrl();?>media/loading6.gif" /></div>';
					 //setTimeout(pr,10);
					//pWidth++;
					jQuery('#file_info_progress_bar_'+item_id+'_'+file_id).html(image);
					jQuery('#file_info_download_'+item_id+'_'+file_id).hide();
					
					//jQuery('#file_info_progress_bar_'+item_id+'_'+file_id).width(''+pWidth+'%');
					
					
					},
				uploadProgress: function(event, position, total, percentComplete) {
					 pWidth = percentComplete + '%';
					//bar.width(percentVal)
					//percent.html(percentVal);
					// console.log(percentVal, position, total);
					jQuery('#file_info_progress_bar_'+item_id+'_'+file_id).width('100%');
					var image = '<div style="width:100%;text-align:center;"><img src="<?php echo $this->getUrl();?>media/loading6.gif" /></div>';
					 //setTimeout(pr,10);
					//pWidth++;
					jQuery('#file_info_progress_bar_'+item_id+'_'+file_id).html(image);
					
					//console.log('total='+total+' percent'+percentComplete);
				},	
				complete:function(e){
					jQuery('#file_info_progress_bar_'+item_id+'_'+file_id).width('100%');
					jQuery('#file_info_progress_bar_'+item_id+'_'+file_id).html('<div class="progress_txt">Uploaded 100%</div>');
					//jQuery('#file_info_download_'+item_id+'_'+file_id).show('fade');
				 //console.log(e);
				}}
			);
			
		/*file_info_  updating the information for uploading file*/	
		
		var cDate ='<?php echo date('dM-Y h:i:s');?>';
		var fSize = Math.round(cFileSize*1024);
		
		jQuery('#file_info_name_'+item_id+'_'+file_id).html('<b>File Name:</b>'+file['name']);
		jQuery('#file_info_size_'+item_id+'_'+file_id).html('<b>Size:</b>'+cFileSize.toFixed(2)+'MB');
	 	jQuery('#file_info_date_'+item_id+'_'+file_id).html('<b>Date:</b>'+cDate);
			
		//jQuery('#submit_'+item_id+'_'+file_id).submit(); 
		
		 
		 /*showing progress bar and file info*/
		 
		 jQuery('#file_info_'+item_id+'_'+file_id).removeClass('not_uploaded');
		 jQuery('#file_info_'+item_id+'_'+file_id).addClass('uploaded');
		 
		//console.log( item_id+'_'+file_id );
		 
		 
		 ///update chat auto /// when chatting////
		 var event_id = event.target.parentNode.parentNode.parentNode.id;
		 event_id = event_id.substring(13);
		 var chat_text = '<b>Client has uploaded File(s) </b>';
		 chat_text+='<br/>&nbsp;&nbsp;<b>File Name:</b> '+file['name'];
		 chat_text+='<br/>&nbsp;&nbsp;<b>Size:</b> '+cFileSize.toFixed(2)+'MB';
		 chat_text+='<br/>&nbsp;&nbsp;<b>Upload Date:</b> '+cDate;
		 
		 /*chat add automatically text*/
		 chatNow(event_id, chat_text);
		 /*send email*/
		 
		 var is_send_email = jQuery('#send_email_'+event_id).val();
					
					if(is_send_email==1){					
					sendEmail(event_id, 'client_artwork_uploaded',chat_text);
					}
		
		 });
		 
	/*send email*/
	jQuery('.send_email input').click(function(event){		
			
			var  send_email_chk = jQuery('#'+event.target.id);	
			if(send_email_chk.val()==0){ send_email_chk.val(1);}else{
				send_email_chk.val(0);
			}
				//alert(send_email_chk.val());
	//alert(send_email_chk.val());	
			 
		});			 
	
	/*adding a clone*/			 
	 jQuery('.upload_artwork_files').click(function(event){
		 
		 /*cloning object*/		 
		/*getting new value*/		
		current_obj = event.target.parentNode.id; 
		current_id = jQuery('.files_thumbnails_'+current_obj+' li:last').attr('id');
		console.log(current_id);	
		fileIds = current_id.split('_');
		pCounter = fileIds[0];
		cCounter=fileIds[1];		
		nCounter = parseInt(cCounter)+1;
		
		////prepare clone for thumbnails///
		$clonRow = jQuery('.files_thumbnails_'+current_obj+' li:last')
		             .clone(true)
				   .attr({class:'clone_row_'+pCounter+'_'+nCounter,
				          id:pCounter+'_'+nCounter,
						  });
		
		//fileUpload[12_7]			
		$clonRow.find('.uploadFile').attr(
		 							{id:'fileUpload['+pCounter+'_'+nCounter+']',
									 name:'fileUpload['+pCounter+'_'+nCounter+']',
									 onclick:'openFileOption("fileUpload['+pCounter+'_'+nCounter+']")',
									});
		$clonRow.find('.submit_form').attr(
		 							{ id:'submit_form_'+pCounter+'_'+nCounter,
									});
									
		
		$clonRow.find('.thumbnail_box').attr(
		 							{ onclick:'openFileOption("fileUpload['+pCounter+'_'+nCounter+']")',
									});	
		$clonRow.find('.preview_thumb').attr(
		 							{ id:'preview_'+pCounter+'_'+nCounter,
									});
		$clonRow.find('.preview_image_thumb').attr(
		 							{ id:'preview_image_'+pCounter+'_'+nCounter,
									  src:'<?php echo $this->getUrl();?>media/upload_artwork_icon.png',
									});								
		$clonRow.find('.artwork_not_uploaded').attr(
		 							{ id:'current_sel_artwork_'+pCounter+'_'+nCounter,
									});	
		$clonRow.find('.file_info').attr(
		 							{ id:'file_info_'+pCounter+'_'+nCounter,
									});
		
		$clonRow.find('.file_info_name').attr(
		 							{ id:'file_info_name_'+pCounter+'_'+nCounter,
									});
		$clonRow.find('.file_info_size').attr(
		 							{ id:'file_info_size_'+pCounter+'_'+nCounter,
									});
		$clonRow.find('.file_info_date').attr(
		 							{ id:'file_info_date_'+pCounter+'_'+nCounter,
									});
		$clonRow.find('.file_info_download').attr(
		 							{ id:'file_info_download_'+pCounter+'_'+nCounter,
									});
		$clonRow.find('.file_info_progress_bar').attr(
		 							{ id:'file_info_progress_bar_'+pCounter+'_'+nCounter,
									});	
																																																																			
									
		// jQuery('#clone_listing_'+currentId).append($clonRow);		 
		// document.getElementById('uploadArt['+currentId+']['+$newcounter+']').style.display='none';
		 jQuery('#uploadedFiles'+current_obj).append($clonRow);
		 jQuery('#file_info_'+pCounter+'_'+nCounter).hide();		 
		  // console.log('#uploadedFiles'+current_obj);//$clonRow.html());	
	 /*add new customer file*/
	 
	 
	
	 
	 });
	
	
	/*saving order with new additions*/
	jQuery('#saveOrder').click(function(event){			 
			 jQuery('#breadCrumbs').html('<span>Your oder has saved successfully! </span>')
			                  .show();			 			 
			 });
	jQuery('textarea').keypress(function(event){
			jQuery('#breadCrumbs').hide();
			}); 
		 
	/*starting chatting with the client designer*/	
	jQuery('.sendButton').click(function(event){
			
			var event_id = event.target.id;
			var chat_text = '';
			chatNow(event_id,chat_text);
			/*send email*/
		 
		 var is_send_email = jQuery('#send_email_'+event_id).val();
					
		 if(is_send_email==1){					
			sendEmail(event_id, 'client_message',chat_text);
			}
			
			});
	jQuery('.input_text').keypress(function(event){
				
				if(event.keyCode==13){
					
					var event_id = event.target.id.substr(10);
					var chat_text = '';
					chatNow(event_id,chat_text);
					//console.log(event_id.substr(10));
					var is_send_email = jQuery('#send_email_'+event_id).val();
					
		 if(is_send_email==1){					
			sendEmail(event_id, 'client_message',chat_text);
			}
					
					}
			
			});	
		
		/*function for chatting window*/
		
	function chatNow(event, chat_text){
			
			//console.log('chatmessage '+chat_text);
			///starting chat///
		   $current_id = event;
		  //  console.log('current id : '+$current_id);
		  
		  $curr_ids =$current_id.split('_'); 
		  $item_id = $curr_ids[0];
		  
		  if(chat_text !=''){
		   $curr_msg = 'chat_text';
		  }else{
			$curr_msg = jQuery('#msg_input_'+$current_id).val();  
			  }
		   
		  // console.log($curr_msg);
		   
		    var oldscrollHeight = jQuery('#chat_container_'+$current_id).prop('scrollHeight');			
			//console.log('old height='+oldscrollHeight);		   
		   if($curr_msg !=''){			   
			   jQuery('#msg_input_'+$current_id).val('');
			   //console.log($curr_msg);
			   /* sending message to chat log upon the update*/
			   if(chat_text !=''){
			   
			   $client_message = '<div class="client_text"><div class="chat_heading_client">You:(<?php echo date('dM,Y h:i a');?>)</div><div class="c_text_client"> '+chat_text+' </div></div>'; 
			   
			   }else{
				   
				 $client_message = '<div class="client_text"><div class="chat_heading_client">You:(<?php echo date('dM,Y h:i a');?>)</div><div class="c_text_client"> '+$curr_msg+' </div></div>';  
				   }
			 //  console.log($client_message);
			  // console.log($current_id);
			   
			   jQuery('#chat_container_'+$current_id).append($client_message);
			  /*saving the chat to file*/
			   
			  $chat_file = jQuery('#chat_file_path_'+$current_id).val();
			  
			 	
			  			  
			  /*get variables */ 
			   $postVars = { file_path:$chat_file,
			                 chat_data:$client_message,
							 short_order_id:<?php echo $_short_order_id;?>,	
							 order_id:<?php echo $_order_number;?>,
							 store_id:<?php echo $_store_id;?>,
							 proof_type:'customer',
							 user_id:<?php echo $_user_id;?>,
							 user_type:'<?php echo $_user_type;?>',
							 item_id:$item_id,
							 customer_id:<?php echo $_customer_id;?>,
						   }
			   
			  /*writing chat data to file via ajax*/
			  $.ajax(
			     { 
				  url:'<?php echo Mage::getUrl('upload/index/savechat')?>', 
				  type:'POST',
				  data: $postVars,
				  dataType:'HTML',
				  success: function(data){
					  console.log(data);
					  },
					  
				 }
			  );
			  			   
			   
			//Auto-scroll   
			var newscrollHeight = jQuery('#chat_container_'+$current_id).prop("scrollHeight")-70;
			
			//Scroll height after the request 
			if(newscrollHeight > oldscrollHeight){  
				jQuery('#chat_container_'+$current_id).animate({ scrollTop: newscrollHeight }, 'normal'); 
				//Autoscroll to bottom of div  
            } 
			   
		}else{
				   alert('Please enter some text to resume chat...');
				   jQuery('#msg_input_'+$current_id).focus();
				   jQuery('#'+$current_id).prop('disabled',true);
			}
	} //end of chat now function ///
				
	/*------------------------------------------------------------------*/
	/*function  sendEmail(event,page_type,chat_detail)  */
	
	function sendEmail(event, page_type,chat_detail){
		
				//console.log('chatmessage '+chat_text);
			///starting chat///
		   $current_id = event;
		  //  console.log('current id : '+$current_id);
		  chat_text = chat_detail;
		  $curr_ids =$current_id.split('_'); 
		  $item_id = $curr_ids[0];
		  
		  if(chat_text !=''){
		   $curr_msg = 'chat_text';
		  }else{
			$curr_msg = jQuery('#msg_input_'+$current_id).val();  
			  }
		
		   
		  	  
			  /*get variables */ 
			   $postVars = { 
			                 chat_data:$client_message,
							 short_order_id:<?php echo $_short_order_id;?>,	
							 order_id:<?php echo $_order_number;?>,
							 store_id:<?php echo $_store_id;?>,
							 proof_type:'customer',
							 user_id:<?php echo $_user_id;?>,
							 user_type:'<?php echo $_user_type;?>',
							 item_id:$item_id,
							 customer_id:<?php echo $_customer_id;?>,
							 message_type:page_type,
						   }
			   
			  /*writing chat data to file via ajax*/
			  $.ajax(
			     { 
				  url:'<?php echo Mage::getUrl('upload/index/sendTemplateEmail')?>', 
				  type:'POST',
				  data: $postVars,
				  dataType:'HTML',
				  success: function(data){
					  console.log(data);
					  },
					  
				 }
			  );
			  			 
		
		
		return true;
		
		}
	
	/*------------------------------------------------------------------*/
	
	
	/*expand chat button and extract as well*/
	jQuery('.expand_btn').click(function(event){
		
		var chatBoxId = event.target.id;
		var chatBoxWidth = jQuery('#expand_btn_'+chatBoxId).width();
		console.log(chatBoxId);
		
		if(chatBoxWidth == 293){
		jQuery('#expand_btn_'+chatBoxId).attr({style:'width:310%;right:213%; position:relative;'});
		}else{
			jQuery('#expand_btn_'+chatBoxId).attr({style:'width:293px;right:0px; position:relative;'});
			}
		
		});	
		
		
   		
	/*uploading selected files*/	
	function uploadFiles(upload_id){		
		console.log(upload_id);		
		}
	
	///approving the design sent from the designer///
	
jQuery('.approve_dropdown').change(function(event){
			
			
			
			current_id = event.target.id;
			 console.log(current_id);
			$selectedVal = jQuery('#'+current_id).val(); 
			
			
			if($selectedVal==0){
				alert('Please approve or dis-approve from the list...');
				return false;
				}else{
				/*if value is 1 then design is not approved*/
				
			/*
			if($selectedVal==1){
				confirmed = confirm('You are about dis-approve the design');
					
					if(confirmed){					
						
						var file_obj = {file_name:  jQuery('#cfileName_'+ids[2]+'_'+ids[3]).val(),
								file_size:  jQuery('#cfileSize_'+ids[2]+'_'+ids[3]).val(),
								file_id: 	curr_event,
								file_path:	jQuery('#currFilePath').val(),
								
								};
						
						approve_it(file_obj,event.target.id,1);
					}
				return false;
				}
				*/	
			
			/*if value is 2 then the design is approved*/
			
			
				
				var current_selected_val = $selectedVal;				
								
				/*setting the values for the popup*/
				
				c_current_id = event.target.id;
				ids = c_current_id.split('_');
				item_id = ids[2];
				
				pName = jQuery('#itemName_'+item_id).val();
				pModel = jQuery('#modelNo_'+item_id).val();
				
				productName = '<h2>'+pName+'</h2><div>( Model No. '+pModel+' )</div>';
				//console.log(productName);
			
			jQuery('#product_heading').html(productName);
			cFileName= jQuery('#cfileName_'+ids[2]+'_'+ids[3]).val();
			cFileSize = jQuery('#cfileSize_'+ids[2]+'_'+ids[3]).val();
			cPath = jQuery('#currFilePath').val();
			
			imgHtml ='<img width="135" height="93" alt="'+cFileName+'" src="'+cPath+cFileName+'" />';
			
			/* assigning the images sources*/
			jQuery('#img_uploaded').html(imgHtml);
			
			var download_file = '<a href ="'+cPath+cFileName+'" target="_blank" >Download</a>';
			
			jQuery('.download_file_path').html(download_file);
			
			jQuery('#uploadedfileSize').html('File size: '+cFileSize);				
			
			jQuery('#input_quantity').attr({id:'input_quantity_'+ids[2]+'_'+ids[3],});			
			
			//update input quantity///			
			var ordered_qty = jQuery('#ordered_qty_'+ids[2]+'_'+ids[3]).val();
			//console.log(ordered_qty);
			
			
			//changing or updating the quantity
			
			jQuery('#input_quantity_'+ids[2]+'_'+ids[3]).change(function(event){				
				
				
				var new_quantity =event.target.value;				
				
				if(new_quantity > ordered_qty){
					alert('Oops you entered the quantity more than the ordered quantity, that is ('+Math.round(ordered_qty)+')');
					jQuery('#input_quantity_'+ids[2]+'_'+ids[3]).val(1).focus().select();
					
					return false;
					
				}else{
					
					jQuery('#quantity_'+ids[2]+'_'+ids[3]).val(event.target.value);
				  //console.log(event.target.value);				
				}//end of quantity box
				});
			////update signature////
			jQuery('#cSignature').attr({id:'cSignature_'+ids[2]+'_'+ids[3],});
			
			//reseting the value of signatures
			jQuery('.cSignature').val('');
			jQuery('#cSignature_'+ids[2]+'_'+ids[3]).val('');
			
			jQuery('#signature_'+ids[2]+'_'+ids[3]).val(jQuery('#cSignature_'+ids[2]+'_'+ids[3]).val());
			
			
			
			jQuery('#cSignature_'+ids[2]+'_'+ids[3]).change(function(event){
				
				jQuery('#signature_'+ids[2]+'_'+ids[3]).val(event.target.value);
				 //console.log(event.target.value);
				
				});	
				
		/*checking if the client has disapproved the design*/	
		jQuery('.approval-text').attr({id:'approval_text_'+ids[2]+'_'+ids[3],
									 }									
									);
		
		/*if we are going to disapprove */
		
		if(current_selected_val==1){
			
			jQuery('#overlayPopup').show();
			
				console.log('disapproved');
			
			jQuery('#Print_Quantity').hide();
			jQuery('.agreePrintBtn').hide();
			jQuery('.disAgreeBtn').show();
			
			var text_area = '<textarea id="reason_txt_'+ids[2]+'_'+ids[3]+'" style="width:640px; height:168px; border:0px;font-size:14px;" ></textarea>';
			
			jQuery('#Disclaimer h2').html('Reason to disapprove');
			jQuery('#approval_text_'+ids[2]+'_'+ids[3]).html(text_area);
			jQuery('#disAgreeBtn').attr({id:'disAgreeBtn_'+ids[2]+'_'+ids[3]});;
			
			///clicking on agree button ///
			
			pre_id=0;
			
			if(pre_id < 1){	
			jQuery('#disAgreeBtn_'+ids[2]+'_'+ids[3]).click(function(){
				
				c_current_id = event.target.id;
				var curr_event = event.target.parentNode.parentNode.className;
				
				ids = c_current_id.split('_');
				item_id = ids[2];
				//call approve it if client click on approve button from the popup///
				qty = jQuery('#quantity_'+ids[2]+'_'+ids[3]).val();
				sign = jQuery('#cSignature_'+ids[2]+'_'+ids[3]).val();
				reason = jQuery('#reason_txt_'+ids[2]+'_'+ids[3]).val();
				 
				if(reason==''){
					alert('Please enter valid resaon for disapproval...');
					jQuery('#reason_txt_'+ids[2]+'_'+ids[3]).focus();
					return false;
					}
				
				
				if(sign==''){
					alert('Please enter your signatures properly...');
					jQuery('#cSignature_'+ids[2]+'_'+ids[3]).focus();
					return false;
					}
				
				//finally approve
				//console.log(curr_event);
				
				var file_obj = { file_name: cFileName,
								 file_size: jQuery('#cfileSize_'+ids[2]+'_'+ids[3]).val(),
								   file_id: curr_event,
								 file_path:	jQuery('#currFilePath').val(),
						  		reason_txt: jQuery('#reason_txt_'+ids[2]+'_'+ids[3]).val(),
							 signature_txt: sign,
							 quantity	  :	0,
								
								};
				
				
				pre_id++;
				
				//console.log('console'+pre_id);
			if(pre_id==1){				
				approve_it(file_obj,event.target.id,1);
				//console.log('file_'+ids[2]+'_'+ids[3]);
				
				}
					jQuery('#overlayPopup').hide();
				
				});
			}
			return false;
			
			
			}	
				
		 
		if(current_selected_val == 2){
			
			jQuery('#overlayPopup').show();
			pre_id=0;
			
			if(pre_id < 1){
				
			
			jQuery('#Print_Quantity').show();
			jQuery('.agreePrintBtn').show();
			jQuery('.disAgreeBtn').hide();
			
			var text_html ="<p>Artwork Approval</p><p>It is the customer's responsibility to ensure that the proof is correct in all areas. Please be sure to double-check spelling, grammar, layout and design before approving artwork.</p><p>If a proof containing errors is approved by the customer, customer is responsible for payment of all original costs of printing (screens, setup charges, any substrates), including corrections and reprints.</p><p>The customer is 100% responsible for approvals of Copyright, Trademark and Licensing Agreements of artwork.</p><p>Customer's signature on artwork approval is contractually binding for payment of all services rendered.</p><p>All artwork must be approved by the customer with an authorised signature before a job can be entered into production.</p>";

		jQuery('#Disclaimer h2').html('Disclaimer');
		jQuery('#approval_text_'+ids[2]+'_'+ids[3]).html(text_html);
		jQuery('#agreePrintBtn').attr({id:'agreePrintBtn_'+ids[2]+'_'+ids[3]});;
		
		
		jQuery('#agreePrintBtn_'+ids[2]+'_'+ids[3]).click(function(){
				
				c_current_id = event.target.id;
				var curr_event = event.target.parentNode.parentNode.className;
				
				ids = c_current_id.split('_');
				item_id = ids[2];
				//call approve it if client click on approve button from the popup///
				qty = jQuery('#quantity_'+ids[2]+'_'+ids[3]).val();
				sign = jQuery('#cSignature_'+ids[2]+'_'+ids[3]).val();
				total_qty = jQuery().val('#total_quantity_'+ids[2]+'_'+ids[3]).val();
				 
				 if(qty<1){
					 alert('Please enter at least 1 Quantity.');
					 jQuery('#quantity_'+ids[2]+'_'+ids[3]).focus();
					 jQuery('#quantity_'+ids[2]+'_'+ids[3]).select();
					 return false;
					 }
					 
				if(qty>total_qty){
					 alert('Please enter Quantity lesss than total quantity'+total_qty);
					 jQuery('#quantity_'+ids[2]+'_'+ids[3]).focus();
					 jQuery('#quantity_'+ids[2]+'_'+ids[3]).select();
					 return false;
					 }	 
				
				
				if(sign==''){
					alert('Please enter your signatures properly...');
					jQuery('#cSignature_'+ids[2]+'_'+ids[3]).focus();
					return false;
					}
				
				//finally approve
				//console.log(curr_event);
				
				var file_obj = {file_name:  cFileName,
								file_size:  jQuery('#cfileSize_'+ids[2]+'_'+ids[3]).val(),
								file_id: 	curr_event,
								file_path:	jQuery('#currFilePath').val(),
								signature_txt: sign,
								total_quantity:total_qty,
								
								};
				
				pre_id ++;
				
				if(pre_id==1){				
				approve_it(file_obj,event.target.id,2);
				//console.log('file_'+ids[2]+'_'+ids[3]);
				
				}
					jQuery('#overlayPopup').hide();
				
				});
		
			return false;
	
			
		}
	}		
			 	
			return false;
						
				}
			});
			
		jQuery('#closeBtn').click(function(){
			jQuery('#overlayPopup').hide();
			});	
		
	
	///function final approve the proof/////
		
	function approve_it(file_obj,$current_id,cVal){
			
			$idInfo =  current_id.split('_');
			$item_id =$idInfo[2];
			$entity_id = $idInfo[3];
			
			$approved_status = jQuery('#'+$current_id).val();
			$quantity = jQuery('#quantity_'+$item_id+'_'+$entity_id).val();
			$signature = jQuery('#signature_'+$item_id+'_'+$entity_id).val();
			$order_quote_id = <?php echo $_short_order_id;?>;
			$total_qty = jQuery('#total_quantity_'+$item_id+'_'+$entity_id).val();
			$reason_txt = file_obj['reason_txt'];
			$customer_id = <?php echo $_customer_id?>;			
			$store_id = '<?php echo $_store_id?>';
			$file = file_obj['file_name'];
			$status='Approved';			
			
			//console.log($total_qty);	
			//console.log(file_obj['file_id']);	
		
		///update chat auto /// when chatting////
		 var event_id = file_obj['file_id'];
			 
		 event_id = event_id.substring(12);
		 //console.log(event_id);
		
		if(cVal==1){
			
		$quantity = 0;	
	var chat_text = '<h2>DISAPPROVED:</h2> <b style="color:#f00;">Client has disapproved the file</b>';
	var reason_text ='<br/>&nbsp;&nbsp;<b><u>Reason: </u></b>'+file_obj['reason_txt'];
	var qty =''; 
	var approval_date ='<br/>&nbsp;&nbsp;<b><u>Disapproval Date:</u></b> '+'<?php echo date('dM-Y h:i:s'); ?>';
	var signs='<br/>&nbsp;&nbsp;<b><u>Disapproved By: </u></b>'+file_obj['signature_txt'];
		$status='Disapproved';  
		}
		if(cVal==2){
			var chat_text = '<h2>APPROVED:</h2><b>Client has approved the file</b>';
			var reason_text='';
			var qty = '<br/>&nbsp;&nbsp;<b><u>Print Qty:</u></b> <u>'+$quantity+'</u>';
			var approval_date ='<br/>&nbsp;&nbsp;<b><u>Approved Date:</u></b> '+'<?php echo date('dM-Y h:i:s'); ?>';
			var signs='<br/>&nbsp;&nbsp;<b><u>Approved By: </u></b>'+file_obj['signature_txt'];
			$status='Approved'; 
			}
		  
		  chat_text+='<br/>&nbsp;&nbsp;<b><u>File Name:</u></b> <br/>&nbsp;&nbsp;<a href="'+file_obj['file_path']+file_obj['file_name']+'" target="_blank" style="color:#fff;" title="'+file_obj['file_name']+'"><u>'+file_obj['file_name']+'</u></a>';
		 // chat_text+='<br/>&nbsp;&nbsp;<b>Size:</b> '+file_obj['file_size']+'MB';
		  chat_text+=approval_date;
		  chat_text+=qty;
		  chat_text+=signs;
		  chat_text+=reason_text;
		  
		 
		 /*chat add automatically text*/
		 chatNow(event_id, chat_text);
			
			console.log(event_id);
			
			var fileDataVars = {
							approved_status	:$approved_status,
							quantity		:$quantity,
							signature		:$signature,
							order_id		:$order_quote_id,
							item_id			:$item_id,
							entity_id 		:$entity_id,
				total_ordered_quantity 		:$total_qty,
							reason_txt		:$reason_txt,
							store_id		:$store_id,
							customer_id		:$customer_id,
							file			:$file,
							status			:$status,
							
							proof_type		:'order',								
						}
			console.log(fileDataVars);			
							
		/*writing chat data to file via ajax*/
			  
			  
			  jQuery.ajax(
			     { 
				  url:'<?php echo Mage::getUrl('upload/index/approvedesign')?>', 
				  type:'POST',
				  data: fileDataVars,
				  dataType:"HTML",
                  beforeSend: function(xhr) { 
   						 //console.log(xhr);
						 jQuery('#loadingGif').show();
						},
				  success: function(data){
					  		
							jQuery('#not_approved_'+$item_id+'_'+$entity_id).hide();
							jQuery('#approved_'+$item_id+'_'+$entity_id).hide();
							jQuery('#loadingGif').hide();
						if(cVal==1){
							
						jQuery('#not_approved_'+$item_id+'_'+$entity_id).show();
						jQuery('#approved_'+$item_id+'_'+$entity_id).hide();
						jQuery('#pending_'+$item_id+'_'+$entity_id).hide();
						
						/*hidding button on off*/
						jQuery('#approve_dropdown_'+$item_id+'_'+$entity_id).hide();
						
						/*send email*/
						/*send email*/
						var is_send_email = jQuery('#send_email_'+event_id).val();
									
						 if(is_send_email==1){					
							sendEmail(event_id, 'client_rejected_proof',chat_text);
							}
		 				
						
						//jQuery('#loadingGif').hide();
						//console.log(data);
						}
						
						if(cVal==2){
						jQuery('#approved_'+$item_id+'_'+$entity_id).show();
						jQuery('#not_approved_'+$item_id+'_'+$entity_id).hide();
						jQuery('#pending_'+$item_id+'_'+$entity_id).hide();
						///update approved quantity
						
						jQuery('#approved_quantity_'+$item_id+'_'+$entity_id).html('Qty: '+$quantity);
						
						/*assiginging the file name with print qty to the summary*/
						
						var newEntry = jQuery('#approved_files_label_'+$item_id+'_'+$entity_id+' li:first').clone();
						newEntry.attr({style:'display:block'});
						console.log(newEntry);
						
				newHtml = '<div class="file_name_label" id="file_name_lable_'+$item_id+'_'+$entity_id+'">'+file_obj['file_name']+'</div><div class="qty_label" id="qty_label_'+$item_id+'_'+$entity_id+'">x&nbsp;&nbsp;'+$quantity+'</div>';
						newEntry.html(newHtml);
						
						
						jQuery('#approved_files_label_'+$item_id+'_'+$entity_id).append(newEntry);
						
						
		/*send email*/
		var is_send_email = jQuery('#send_email_'+event_id).val();
					
		 if(is_send_email==1){					
			sendEmail(event_id, 'client_approved_proof',chat_text);
			}
		 
						
						/*hidding button on off*/
						jQuery('#approve_dropdown_'+$item_id+'_'+$entity_id).hide();
						
							//jQuery('#loadingGif').hide();
							//console.log(data);
							}
						
						
						
					  },
					  
				 }
			  );	
			
			}	
	
	}); //end of main jQuery function
			
</script>
  
<div class="col-main">
<div class="my-account"><div class="page-title">
    <h1>My Artwork(s) / Proof(s)</h1>
</div>
   
    <!--<p>You have not uploaded any artwork yet.</p>-->
    
<div class="buttons-set">
    <p class="back-link"><a href="javascript:history.go(-1);"><small>« </small>Back</a></p>
</div>

<div class="orderGrid">
         <ul id="productGrid">
      <?php
			
		/*creating folders for chat, files, proofs etc*/
		$_media_url = Mage::getBaseDir('media');
	//	$_current_store =  Mage::app()->getStore()->getGroup()->getName();;
	    $_current_store = $_c_store_name;
		$_current_year=date('Y');
		$_current_month= strtolower(date('M-y'));
		$_current_order_id = $_order_number;
		
		/*create directory if not exists*/
		
		
		$_path = $_media_url;
		
		/*if media/stores directory exists either create*/
		if(!is_dir($_path.'/stores')){			
				if(@mkdir($_path.'/stores',0777)){
				$_stores = '/stores';
				}
			}else{	
			$_stores = '/stores';	
		}
		/*stores path created */
		$_path.=$_stores;
		
		/*if media/stores/current storename directory exists either create*/
		if(!is_dir($_path.'/'.$_current_store)){
			 /*if directory is created*/
			 if(@mkdir($_path.'/'.$_current_store,0777)){
			$_store_name = '/'.$_current_store;
			 }
		  }else{	
			$_store_name = '/'.$_current_store;	
		}
		
		/*current store directory created*/
		$_path.= $_store_name;
		
		
		/*if media/stores/storename/year directory exists either create*/
		if(!is_dir($_path.'/'.$_current_year)){
			if(@mkdir($_path.'/'.$_current_year,0777)){
				$_year = '/'.$_current_year;
			}
		 }else{	
			$_year = '/'.$_current_year;	
		}		
		/*current year directory created*/
		$_path.= $_year;
		
		/*if media/stores/storename/year/month directory exists either create*/
		if(!is_dir($_path.'/'.$_current_month)){
			if(@mkdir($_path.'/'.$_current_month,0777)){
				$_month = '/'.$_current_month;
			}
		 }else{	
			$_month = '/'.$_current_month;	
		}		
		/*current year directory created*/
		$_path.= $_month;
		
		/*if media/stores/storename/year/month/ordernumber directory exists either create*/
		if(!is_dir($_path.'/'.$_current_order_id)){
			if(@mkdir($_path.'/'.$_current_order_id,0777)){
				$_order_number = '/'.$_current_order_id;
			}
		 }else{	
			$_order_number = '/'.$_current_order_id;	
		}		
		/*current year directory created*/
		$_path.= $_order_number;
			 		  
		  /*fetching items in order */
		  $_total_items = count($items);	
		  $i=0;
		  $counter = 0;
	
	
	
	
	/*start listing of rows*/	  
	 foreach($items as $_item ){			  
	 
	 /*further create folder contaiing item sku name*/
	  $_current_sku = $_item->getSku();
	  
	  /*if media/stores/storename/year/month/ordernumber/sku directory exists either create*/
		if(!is_dir($_path.'/'.$_current_sku)){
			if(@mkdir($_path.'/'.$_current_sku,0777)){
				$_sku = '/'.$_current_sku;
			}
		 }else{	
			$_sku = '/'.$_current_sku;	
		}		
	  /*if media/stores/storename/year/month/ordernumber/sku/chat directory exists either create*/
		if(!is_dir($_path.$_sku.'/chat')){
			if(@mkdir($_path.$_sku.'/chat',0777)){
				$_chat = '/chat';
			}
		 }else{	
			$_chat = '/chat';	
		}
	/*if media/stores/storename/year/month/ordernumber/sku/chat directory exists either create*/
		if(!is_dir($_path.$_sku.'/chat')){
			if(@mkdir($_path.$_sku.'/chat',0777)){
				$_chat = '/chat';
			}
		 }else{	
			$_chat = '/chat';	
		}
	/*if media/stores/storename/year/month/ordernumber/sku/draft_files directory exists either create*/
		if(!is_dir($_path.$_sku.'/draft_files')){
			if(@mkdir($_path.$_sku.'/draft_files',0777)){
				$_draft_files = '/draft_files';
			}
		 }else{	
			$_draft_files = '/draft_files';	
		}			
	/*if media/stores/storename/year/month/ordernumber/sku/client_sent_files directory exists either create*/
		if(!is_dir($_path.$_sku.'/client_sent_files')){
			if(@mkdir($_path.$_sku.'/client_sent_files',0777)){
				$_sent_files = '/client_sent_files';
			}
		 }else{	
			$_sent_files = '/client_sent_files';	
		}
		
	/*if media/stores/storename/year/month/ordernumber/sku/print_ready_approved_files directory exists either create*/
		if(!is_dir($_path.$_sku.'/print_ready_approved_files')){
			if(@mkdir($_path.$_sku.'/print_ready_approved_files',0777)){
				$_approved_files = '/print_ready_approved_files';
			}
		 }else{	
			$_approved_files = '/print_ready_approved_files';	
		}	
	 	
	/*opening file first time only if not created*/
	
		if(!is_file($_path.$_sku.$_chat.'/chat.txt')){
			$_chat_file = @fopen($_path.$_sku.$_chat.'/chat.txt','w');
			/*write to file*/
		   $_data ='<div class="curr_date">'.date('d F Y').'</div>
		   <div class="defaultText" > 
			   Use this section to chat with your dedicated designer regarding your graphic design or digitals proofs for your printed goods.If you have any other questions related to this project leave a message on this chat screen below. We respond to all questions regularly. </div>
               <div class="designer_text">
          <div class="chat_heading_designer">Us:('.date('dM,Y h:i a').')</div>
               <div class="c_text_designer"> How may I help you today! </div></div>';
		   $_chat_text = fwrite($_chat_file,$_data);
		   $_chat_text = fclose($_chat_file);
	} //end of file writing
	   
	/*open chat file and reading data */
	 
	  $_cr_chat_file = $_path.$_sku.$_chat.'/chat.txt';
	  $_chat_file = @fopen($_cr_chat_file,'r')or die('counl not open the file');
	  
	  /* fetching current chat data */
	  $_chat_data = fread($_chat_file,filesize($_cr_chat_file));
	 
	
	/*further get products detail*/ 
	
	
	 $_product = Mage::getModel('catalog/product')->load($_item->getProduct_id());
	 $i++;
	  $counter++;
	  
	  $_is_printable = $_product->getIs_printable();
	  //echo $_product->getSku();
	 // exit;
	  if($_is_printable==165){
	 ?>
     
            <li class="listingRow" >
               <?php
			   
			   
			   
			    
		 		$_heading_title = 'Design detail for ';
				$_heading_title .= '" <span style="color:#4db6b2;">'.$_item->getName().' </span> " Only ';
				$_heading_title .= '<span style="font-size:17px; color:#ff6606;"> <br/>( Model No: ';
			     $_heading_title .= $_order['store_id'].'-'.$_item->getSku().')</span>';
		 ?>
         <input type="hidden" id="itemName_<?php echo $_item->getId();?>" value="<?php echo $_item->getName();?>" />
           <input type="hidden" id="modelNo_<?php echo $_item->getId();?>" value="<?php echo $_item->getSku();?>" />
         
               <div class="orderedItemHeadings">
			<?php echo __('Ordered Item #'.$counter);?> 
               </div>
               <h1 class="itemHeadings"> <?php echo $_heading_title; ?> </h1>
               <!--thumbnail listing box start here-->
               <div class="thumbListing" style="background-color:#FF6600; height:160px; margin-top:5px; padding:5px;">
                  <div class="thumbListingInner" style="height:160px; background-color:#FF6600;">
                     <div class="smallThumb"> 
                     <a  href="<?php echo $this->getUrl($_product->getUrlPath());?>"  target="_blank" title="<?php echo 'Click to open detail of "'.$_item->getName().' "';?>" > 
              			<img class="smallThumb_image" align="left" style="padding:10px;"  src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(111, 134);?>"  alt="<?php echo $_item->getName();?>" /> </a> 
                         </div>
                     <div class="orderedLabel"> <?php echo __('Your Ordered Item requiring graphics');?> </div>
                     <div class="forwardArrow"> </div>
                     <div class="infoStepBox">
                        <h3 class="stepsHeadings"><?php echo __('Using your own designer (Steps)');?></h3>
                        <div class="stepsText">
                        <ul>
                           <li><?php echo __('Download Template')?></li>
                           <li><?php echo __('Upload Print Ready Files')?></li>
                           <li><?php echo __('Approve Proof(s)')?></li>
                           <li><?php echo __('Update Print Quantity')?></li>
                        </ul>
                     </div>
                     </div>                     
                    <div class="infoStepBox">
                        <h3 class="stepsHeadings"><?php echo __(' Let us Design for You (Steps)');?></h3>
                        <div class="stepsText">
                        <ul>
                           <li><?php echo __('Upload your high resolution')?></li>
                           <li><?php echo __('Type instructions for our designer(s) below')?></li>
                           <li><?php echo __('Keep communicating with designer(s) until design gets approved')?></li>
                           <li><?php echo __('Update Print Quantity')?></li>
                        </ul>
                     </div>
                     </div>
                     
                  </div>
                  
            </div>      
                  <div class="clr"></div>
                  <!--upload files box start here-->
                  <div class="uploadFilesPanel">
                     <div class="uploadFilesBox">
                     <!--thumbnailbox-->
    <ul class="uploaded_thumbnails files_thumbnails_<?php echo $_item->getId();?>_<?php echo $counter;?>" id="uploadedFiles<?php echo $_item->getId();?>_<?php echo $counter;?>">                            
<?php 
	/*first some 9 items*/
	$_order_id = $_order['entity_id'];
	$_item_id = $_item->getId();
										
	/*getting already uplaoded proof files from the designer side */	
	$_customer_files = Mage::helper('upload')->getCustomer_files($_order_id, $_item_id);
		
	if(count($_customer_files)>0){
		foreach($_customer_files as $_customer_file){
			
			$_id=$_customer_file['entity_id'];
		?>
        <li style="height:220px;" class="clone_row_<?php echo $_item->getId();?>_<?php echo $_id;?> alreadyUploaded" id="<?php echo $_item->getId();?>_<?php echo $_id;?>">
     
     
    <form class="submit_form" id="submit_form_<?php echo $_item->getId();?>_<?php echo $_id;?>" action="<?php echo $this->getUrl('upload/index/uploadImages');?>" onsubmit="return false"  method="post" enctype="multipart/form-data">  
    
     <input type="hidden" id="client_files" name="client_files" value="<?php echo $_path.$_sku.'/client_sent_files';?>" />
     
     <input class="uploadFile" type="file" id="fileUpload[<?php echo $_item->getId();?>_<?php echo $_id;?>]" name="fileUpload[<?php echo $_item->getId();?>_<?php echo $_id;?>]"  style="display:none;"  />
                              
   <?php  /* on click open the filebox*/		  ?>
        <div class="thumbnail_box" onClick="openFileOption('fileUpload[<?php echo $_item->getId();?>_<?php echo $_id;?>]')"> 
         <div id="preview_<?php echo $_item->getId();?>_<?php echo $_id;?>" class="preview_thumb">
           <img id="preview_image_<?php echo $_item->getId();?>_<?php echo $_id;?>" class="preview_image_thumb" src="#"  alt="imagesource" width="140" height="95"/>
        </div>
         <div class="artwork_not_uploaded" id="current_sel_artwork_<?php echo $_item->getId();?>_<?php echo $_id;?>" >                    
                    <div class="upload_artwork_icon" style="background:none;">                          
                        
           <?php
		   	//$base_path = $_SERVER['DOCUMENT_URI'].'/tablethrows/media/' ;
			$base_path = $_SERVER['DOCUMENT_URI'].'/media/' ;
            $file_path = $_path.$_sku;
			$abs_target = strpos($file_path, 'stores');
		 	$target_path = $base_path.substr($file_path,$abs_target).'/';
			
			//$n_file_path = str_replace('\\','/',$file_path);
			
			/*finding file extension*/
			$_file_src = $target_path.'/client_sent_files/'.$_customer_file['file'];
			$_file = explode('.',$_customer_file['file']);
			$_file_ext = $_file[count($_file)-1];
			
			$_known_file_icons=array('rar'=>$this->getUrl().'media/upload/fileicons/rar_icon.png',
									 'zip'=>$this->getUrl().'media/upload/fileicons/rar_icon.png',
									 'txt'=>$this->getUrl().'media/upload/fileicons/txt_icon.png',
									 'docx'=>$this->getUrl().'media/upload/fileicons/docx_icon.png',
									 'doc'=>$this->getUrl().'media/upload/fileicons/docx_icon.png',
									 'xlsx'=>$this->getUrl().'media/upload/fileicons/xlxs_icon.png',
									 'xls'=>$this->getUrl().'media/upload/fileicons/xlxs_icon.png',
									 'pdf'=>$this->getUrl().'media/upload/fileicons/pdf_icon.png',
									 'ai'=>$this->getUrl().'media/upload/fileicons/ai_icon.png',
									 'psd'=>$this->getUrl().'media/upload/fileicons/psd_icon.png',
									 'fla'=>$this->getUrl().'media/upload/fileicons/fla_icon.png',
									 
									);
				
			foreach($_known_file_icons as $_key=>$_val){	
				if($_file_ext==$_key){
					$_file_src = $_val;
					}
			}
			//echo $_file_ext;
			
						
			?>
                             
                            <img src="<?php echo $_file_src;?>" alt="<?php echo $_customer_file['file'];?>" id="preview_image_<?php echo $_item->getId();?>_<?php echo $_id;?>" class="preview_image_thumb"  alt="imagesource" width="140" height="100"/>       
                               </div>
                               </div>
                               </div> 
     <div class="file_info" style="display:block;" id="file_info_<?php echo $_item->getId();?>_<?php echo $_id;?>">
     <div class="file_info_progress_bar" id="file_info_progress_bar_<?php echo $_item->getId();?>_<?php echo $_id;?>">
     
     </div>   
                               
                               <div  style="display:block;" class="file_info_name" id="file_info_name_<?php echo $_item->getId();?>_<?php echo $_id;?>" ><b>File Name: </b> <?php echo $_customer_file['file'];?></div>
                               <div class="file_info_size" id="file_info_size_<?php echo $_item->getId();?>_<?php echo $_id;?>"><b>Size: </b><?php 
							   $_fSize =  $_customer_file['file_size'];
							   $_mb =1024*1024;
							   $_fSize = round($_fSize/$_mb,2);
							   echo $_fSize;?>MB</div>
         
         <div class="file_info_date" id="file_info_date_<?php echo $_item->getId();?>_<?php echo $_id;?>"><b>Date: </b><?php echo date('dM-Y h:i:s',strtotime($_customer_file['postdate']));?></div>
         
         <?php 
		 		$_file_source = $target_path.'/client_sent_files/'.$_customer_file['file'];
		 ?>
         
         <div ><a class="file_info_download" id="file_info_download_<?php echo $_item->getId();?>_<?php echo $_id;?>"  target="_blank" href="<?php echo $_file_source;?>">&dArr;  DOWNLOAD FILE</a>
                               </div>
                  
                                                           
                              </div>
    </form>
    
     </li>
        
		<?php
		}//end of first foreach
	 }//end of else
		
		$m=count($_customer_files);
		$m=$m+1;
		$nCounter=$m+1;
		
		for($j=$nCounter; $j<$nCounter+3; $j++){
					   ?>
                     
                       
    <li style="height:220px;" class="clone_row_<?php echo $_item->getId();?>_<?php echo $j;?> <?php if($j==$nCounter){echo 'firstRow';}?>" id="<?php echo $_item->getId();?>_<?php echo $j;?>">
    
    <form class="submit_form" id="submit_form_<?php echo $_item->getId();?>_<?php echo $j;?>" action="<?php echo $this->getUrl('upload/index/uploadImages');?>" onsubmit="return false"  method="post" enctype="multipart/form-data">  
    
    
    
     <input class="uploadFile" type="file" id="fileUpload[<?php echo $_item->getId();?>_<?php echo $j;?>]" name="fileUpload[<?php echo $_item->getId();?>_<?php echo $j;?>]"  style="display:none;"  />
      
     
     <input type="hidden" id="client_files" name="client_files" value="<?php echo $_path.$_sku.'/client_sent_files';?>" />
                              
   <?php  /* on click open the filebox*/		  ?>
        <div class="thumbnail_box" onClick="openFileOption('fileUpload[<?php echo $_item->getId();?>_<?php echo $j;?>]')"> 
         <div id="preview_<?php echo $_item->getId();?>_<?php echo $j;?>" class="preview_thumb">
           <img src="#" id="preview_image_<?php echo $_item->getId();?>_<?php echo $j;?>" class="preview_image_thumb"  alt="imagesource" width="130" height="95"/>
        </div>
         <div class="artwork_not_uploaded" id="current_sel_artwork_<?php echo $_item->getId();?>_<?php echo $j;?>" >                    
                    <div class="upload_artwork_icon">                             
                             <div class="upload_artwork_icon_label" >
                       <?php 
							echo __('Browse to upload your
                                   Print Ready file(s)
                                   OR
                                   Browse to upload your
                                   high resolution design files
                                   for us to design');?>
                        </div>
                                   
                               </div>
                              </div>
                               </div>
                              <div class="file_info not_uploaded" id="file_info_<?php echo $_item->getId();?>_<?php echo $j;?>">
                              <div style="display:block;" class="file_info_progress_bar" id="file_info_progress_bar_<?php echo $_item->getId();?>_<?php echo $j;?>">
                              
                              </div>
                              
                               <div class="file_info_name" id="file_info_name_<?php echo $_item->getId();?>_<?php echo $j;?>" ><b>File Name: </b> <?php echo $_customer_file['file'];?></div>
                               <div class="file_info_size" id="file_info_size_<?php echo $_item->getId();?>_<?php echo $j;?>"><b>Size: </b><?php 
							   $_fSize =  $_customer_file['file_size'];
							   $_mb =1024*1024;
							   $_fSize = round($_fSize/$_mb,2);
							   echo $_fSize;?>MB</div>
         
         <div class="file_info_date" id="file_info_date_<?php echo $_item->getId();?>_<?php echo $j;?>"><b>Date: </b><?php echo date('dM-Y h:i:s',strtotime($_customer_file['postdate']));?></div>
         <div>
          
         <a class="file_info_download" id="file_info_download_<?php echo $_item->getId();?>_<?php echo $j;?>"  target="_blank" href="<?php echo $_path.$_sku.$_client_files_path.'/'.$_customer_file['file'];?>">&dArr; DOWNLOAD FILE</a>
                               </div>
                   
                              
                             
                              </div>
                              
                               </form>
     </li>
    
     <?php 
	}//end of thumbnail
							
	  ?>
     </ul>
  <!--end of thumbnailbox-->
   <div class="buttons_panel">
   <div class="artwork_buttons upload_artwork_files" id="<?php echo $_item->getId();?>_<?php echo $counter;?>">
      <input   type="button"  value="<?php echo __('Add Another File');?>"  class="artworkBtn" />
    </div>
     <!--<div class="artwork_buttons" id="send_files_<?php echo $_item->getId();?>_<?php echo $counter;?>">
        <input   type="button" id="upload_files_<?php echo $_item->getId();?>_<?php echo $counter;?>"  value="<?php echo __('Send Files');?>" name="upload_files_<?php echo $_item->getId();?>_<?php echo $counter;?>"  value="<?php echo __('Send Files');?>" onclick="uploadFiles('<?php echo $_item->getId();?>_<?php echo $counter;?>');"  class="artworkBtn " />
       </div>-->
            </div>
              </div>
                     
                     
                      <!--auto loading chat after some interval-->
 <script>
	<!--
	// console.log('f');
	 jQuery(function(){
		 
		 
			  
	chat_file = document.getElementById('chat_file_path_<?php echo $_item->getId();?>_<?php echo $counter;?>').value;
	jQuery.ajax();
	
	   // setInterval(updateChat,8000);
				 
/*function chat auto update */
	
function updateChat(){
					
					
					$chat_file = document.getElementById('chat_file_path_<?php echo $_item->getId();?>_<?php echo $counter;?>').value;
					
					var oldscrollHeight = jQuery('#chat_container_<?php echo $_item->getId();?>_<?php echo $counter;?>').prop('scrollHeight');
					
					 /*writing chat data to file via ajax*/
			  /*get variables */ 
			   $postVars = { file_path:$chat_file,
			                 order_id:<?php echo $_short_order_id;?>,	
							 store_id:<?php echo $_store_id;?>,
							 proof_type:'customer',
							 user_id:<?php echo $_user_id;?>,
							 user_type:'<?php echo $_user_type;?>',
							 item_id:<?php echo $_item->getId();?>,
			               }
			  var newscrollHeight = jQuery('#chat_container_<?php echo $_item->getId();?>_<?php echo $counter;?>').prop("scrollHeight")-70;			
			//Scroll height after the request  
			if(newscrollHeight > oldscrollHeight){ 
                
				jQuery('#chat_container_<?php echo $_item->getId();?>_<?php echo $counter;?>').animate({ scrollTop: newscrollHeight }, 'normal'); 
				
				//Autoscroll to bottom of div  
            }
			  
			  $.ajax(
			     { 
				  url:'<?php echo Mage::getUrl('upload/index/getChatStatus')?>', 
				  type:'POST',
				  data: $postVars,
				  dataType:'HTML',
				  success: function(data){
						// console.log(data);
						if(data!=0){
						
						jQuery('#chat_container_<?php echo $_item->getId();?>_<?php echo $counter;?>').html(data);
						  
						  
						  var newscrollHeight = jQuery('#chat_container_<?php echo $_item->getId();?>_<?php echo $counter;?>').prop("scrollHeight")-70;
			
			//Scroll height after the request  
             
			
			if(newscrollHeight > oldscrollHeight){  
                
				jQuery('#chat_container_<?php echo $_item->getId();?>_<?php echo $counter;?>').animate({ scrollTop: newscrollHeight }, 'normal'); 
				
				//Autoscroll to bottom of div  
            } 
						}//end of data
						  
						  
						  },						  
					 }
				  );
				
					}///end of updatefunction
				
			    });
			-->
			</script>
      <!--auto loading chat end-->   
                     
                     <!--chat box start here-->
                     <div class="chatBoxPanel">
                         <input type="hidden" id="chat_file_path_<?php echo $_item->getId();?>_<?php echo $counter;?>" name="chat_file_path_<?php echo $_item->getId();?>_<?php echo $counter;?>" value="<?php echo $_path.$_sku.$_chat.'/chat.txt';?>" />
                         <div class="chatBox" id="expand_btn_<?php echo $_item->getId();?>_<?php echo $counter;?>">
                         <div class="chat_panel_heading" ><?php echo __('Items\'s Message Box');?> <div id="<?php echo $_item->getId();?>_<?php echo $counter;?>" title="Click to expand or contract chatbox..." class="expand_btn"></div></div>
                         
                         <!--chat container-->
                         <div class="chat_container" id="chat_container_<?php echo $_item->getId();?>_<?php echo $counter;?>" >                            
                     <?php /*loading first time chat from the chat file*/
						echo $_chat_data;
					  ?>
                         
  <?php /*
    <div class="chatWindow">	
 			 <div class="Chattophead"><div class="chat_heading">You:(<?php echo date('h:i a');?>)</div></div><!--Chattophead-->
    		<div class="ChatbgImage">If we are doing your design project please enter complete graphics design specs.</div><!--bgImage-->    
			</div><!--chatWindow--> 
         
         <div class="designer_text">
            <div class="chat_heading">Us:(<?php echo date('h:i a');?>)</div>
               <div class="cText"> If we are doing your design project please enter complete graphics design specs. </div>
           </div>
        <?php 
		*/
		?>              
          </div> 
                        <!--end of chat container-->
                        
      <div class="input_box">
      
      <input class="input_text" id="msg_input_<?php echo $_item->getId();?>_<?php echo $counter;?>" name="msg_input_<?php echo $_item->getId();?>_<?php echo $counter;?>" type="text" placeholder="<?php echo __('Your message here...')?>" />
      <input class="sendButton" type="button"  id="<?php echo $_item->getId();?>_<?php echo $counter;?>" name="<?php echo $_item->getId();?>_<?php echo $counter;?>"  value="Send" title="Type your message and hit send button"  />
       </div> 
       <div class="send_email" id="<?php echo $_item->getId();?>_<?php echo $counter;?>"><label>
       <input type="checkbox" name="send_email_<?php echo $_item->getId();?>_<?php echo $counter;?>" id="send_email_<?php echo $_item->getId();?>_<?php echo $counter;?>" value="1" checked /> 
       <?php echo __('I want to send Email');?></label> </div>         
           </div>
                     </div>
                     <!--end of chatbox here-->
                  </div>
                  <!--Uplod box files ends here-->
                 
                 
                 <div class="clr"></div>
                  <!--upload files box start here-->
                  <div class="artworkProofPanel">
                  
        <?php 
		 		/*proof tilte*/
				$_proof_title = 'Artwork Proof approval for ';
				$_proof_title .= '" <span style="color:#4db6b2;">'.$_item->getName().' </span> " ';
				$_proof_title .= '<br/><span style="font-size:17px; color:#ff6606;"> ( Model No: ';
			    $_proof_title .= $_order['store_id'].'-'.$_item->getSku().')</span>';
		 ?>
                  
                   <h1 class="itemProofHeadings"> <?php echo $_proof_title; ?> </h1>
                     <div class="proofPanel">
                     <!--thumbnailbox-->
                        <ul class="uploaded_thumbnails">
                            <?php 
							
							/*fetching the proof files*/
					$_order_id = $_order['entity_id'];
					$_item_id = $_item->getId();
										
					/*getting already uplaoded proof files from the designer side */	
					$_proof_files = Mage::helper('upload')->getProof_files($_order_id, $_item_id);
					
					if(count($_proof_files) >0){
					
					foreach($_proof_files as $_proof_file){
						
						$_id =$_proof_file['entity_id'];
						
					   ?>
                            <li class="proof_panel_<?php echo $_item->getId();?>_<?php echo $counter;?>" >
                            
                            
                             <?php
		   	//$base_path = $_SERVER['DOCUMENT_URI'].'/tablethrows/media/' ;
			$base_path = $_SERVER['DOCUMENT_URI'].'/media/' ;
            $file_path = $_path.$_sku;
			$abs_target = strpos($file_path, 'stores');
		 	$target_path = $base_path.substr($file_path,$abs_target).'/';
			
			//$n_file_path = str_replace('\\','/',$file_path);
			
			/*finding file extension*/
			$_file_src = $target_path.'/print_ready_approved_files/'.$_proof_file['file'];
			$_file = explode('.',$_proof_file['file']);
			$_file_ext = $_file[count($_file)-1];
			
			$_known_file_icons=array('rar'=>$this->getUrl().'media/upload/fileicons/rar_icon.png',
									 'zip'=>$this->getUrl().'media/upload/fileicons/rar_icon.png',
									 'txt'=>$this->getUrl().'media/upload/fileicons/txt_icon.png',
									 'docx'=>$this->getUrl().'media/upload/fileicons/docx_icon.png',
									 'doc'=>$this->getUrl().'media/upload/fileicons/docx_icon.png',
									 'xlsx'=>$this->getUrl().'media/upload/fileicons/xlxs_icon.png',
									 'xls'=>$this->getUrl().'media/upload/fileicons/xlxs_icon.png',
									 'pdf'=>$this->getUrl().'media/upload/fileicons/pdf_icon.png',
									 'ai'=>$this->getUrl().'media/upload/fileicons/ai_icon.png',
									 'psd'=>$this->getUrl().'media/upload/fileicons/psd_icon.png',
									 'fla'=>$this->getUrl().'media/upload/fileicons/fla_icon.png',
									 
									);
				
			foreach($_known_file_icons as $_key=>$_val){	
				if($_file_ext==$_key){
					$_file_src = $_val;
					}
			}
			//echo $_file_ext;
			
			$download_src = $target_path.'/print_ready_approved_files/'.$_proof_file['file'];
			$download_path = $target_path.'/print_ready_approved_files/';				
			?>
                            
  <?php
  
  $_approved_status = 0; 
   	/*approved status is 0 then not approved will be showed*/
		if($_proof_file['approved_status']==1){	  
		 	  $_approved_status = 1;
		 }elseif($_proof_file['approved_status']==2){	
		     $_approved_status = 1;
		 }else{
		    $_visibility = 'style="display:block;"';
			$_approved_status = 0;
			 }
		 ?> 
              
       <div <?php if($_proof_file['approved_status']==1){echo 'style="display:block"';}else{ echo 'style="display:none"';}	?> class="not_approved" id="not_approved_<?php echo $_item->getId();?>_<?php echo $_id;?>"> <?php echo __('Not Approved'); ?> </div>
              
       <div <?php if($_proof_file['approved_status']==2){echo 'style="display:block"';}else{ echo 'style="display:none"';}	?> class="approved" id="approved_<?php echo $_item->getId();?>_<?php echo $_id;?>"> <?php echo __('Approved'); ?><div class="approved_qunatity" id="approved_quantity_<?php echo $_item->getId();?>_<?php echo $_id;?>"><?php echo 'Qty: '.$_proof_file['quantity']; ?></div> 
        </div>    
    
 <div <?php if($_visibility){echo $_visibility;}else{echo 'style="display:none;"';};?> class="pending" id="pending_<?php echo $_item->getId();?>_<?php echo $_id;?>">  </div>  
           
       
                              <div class="thumbnail_box"> 
                              <div class="upload_proof_icon" style="background:none;">
                               	<a href="<?php echo $download_src; ?>" target="_blank">
                                <img style="border:0;" width="140" height="100" src="<?php echo $_file_src;?>" alt="<?php echo $_proof_file['file'];?>"/></a>
                               </div>
                              </div>
                              
                              <div  class="upload_progress_info" id="upload_progress_info_<?php echo $_item->getId();?>_<?php echo $i;?>" style="width:150px; text-align:left;">
             <div class="progress_bar" id="progress_bar_<?php echo $_item->getId();?>_<?php echo $_id;?>" style="width:150px; height:10px; background-color:#069"></div>
                 <div class="filename" id="filename_<?php echo $_item->getId();?>_<?php echo $_id;?>"><b>File: </b><span style="font-size:9px; color:#999;"> <?php echo $_proof_file['file'];?> </span></div>
                 <input type="hidden" id="cfileName_<?php echo $_item->getId();?>_<?php echo $_id;?>" value="<?php echo $_proof_file['file'];?>" />    
                
                         
                 <input type="hidden" id="ordered_qty_<?php echo $_item->getId();?>_<?php echo $_id;?>" value="<?php echo $_item->getQty_ordered();?>" />
                     
 <div class="updated" id="updated_<?php echo $_item->getId();?>_<?php echo $_id;?>">
 <b>Updated:</b> <?php echo date('dM-Y h:i:s',strtotime($_proof_file['postdate']));?></div>
                         
 
 <div class="fileSize" id="fileSize_<?php echo $_item->getId();?>_<?php echo $_id;?>"><b>Size: </b><?php 
							   $_fSize =  $_proof_file['file_size'];
							   $_mb =1024*1024;
							   $_fSize = round($_fSize/$_mb,2);
							   echo $_fSize;?>MB</div> 
                               <input type="hidden" id="cfileSize_<?php echo $_item->getId();?>_<?php echo $_id;?>" value="<?php echo $_fSize;?>" />                             
                   </div>
                             
                             
           <?php 
				if($_approved_status==0){				
			?>  
                              <div>
<select id="approve_dropdown_<?php echo $_item->getId();?>_<?php echo $_id;?>" name="approve" id="approval" class="approve_dropdown">
  
  
   <option value="0" <?php if($_proof_file['approved_status']==0)echo 'selected';?>><?php echo __('Please Approve');?></option>
   <option value="2" <?php if($_proof_file['approved_status']==2)echo 'selected';?>><?php echo __('I approve to get the above design printed');?></option>
   <option value="1" <?php if($_proof_file['approved_status']==1)echo 'selected';?>><?php echo __('I disapprove (Type your comments in the chatbox)');?></option>
  
  
  </select>
  <input type="hidden" value="1" id="quantity_<?php echo $_item->getId();?>_<?php echo $_id;?>" />
  <input type="hidden" value="<?php echo round($_item->getQty_ordered());?>" id="total_quantity_<?php echo $_item->getId();?>_<?php echo $_id;?>" />
  <input type="hidden" value="none" id="signature_<?php echo $_item->getId();?>_<?php echo $_id;?>" />
  <input type="hidden" value="<?php echo $download_path;?>"  id="currFilePath" class="currFilePath" />                            
                              
                              </div>
                              
             <?php 
				}
			 ?>        
                           </li>
                           <?php 
							}//end of thumbnail
							
							}else{
	echo '<li><div class="notuploadedMsg" style="margin-left:-52px;"><h1>Designer(s) have not uplaoded any files for approval yet.</h1></div></li>';
			
		}
					  ?>
                       </ul>
                     <!--end of thumbnailbox-->
                     </div>
                 
                  </div>
                  
      <!--start final approval summary --> 
      <?php 
	  
	  		/*getting approved files from the client side */	
					$_approved_files = Mage::helper('upload')->getApproved_files($_order_id, $_item_id);
					//print_r($_approved_files);
	  ?>                        
          <div class="proof_summary" id="proof_summary_<?php echo $_item->getId();?>_<?php echo $_id;?>">
          	<div class="proof_summary_heading">Proof Summary </div>
            
            <div class="proof_summary_model_title" ><b>Model: </b>
            <?php echo $_order['store_id'].'-'.$_item->getSku();?>
            </div>
            
            <div class="proof_summary_title" ><b>Total Ordered Qty: </b>
            
            
            <div class="total_ordered_qty" id="total_ordered_qty_<?php echo $_item->getId();?>_<?php echo $_id;?>" style="float:right;"><?php echo round($_item->getQty_ordered());?></div></div> 
            <div class="approved_files">
            
            <div class="proof_summary_title" style="margin-top:10px;"><b>Approved files are as follow... </div>  
            <div class="proof_summary_approved_files_title" ><b>File Name: </b><div class="qty_heading" >Qty</div></div>  
            <!--files label for apprval files-->
             <ul class="approved_files_label" id="approved_files_label_<?php echo $_item->getId();?>_<?php echo $_id;?>" >
             <?php 
			 		if(count($_approved_files) >0){
						
						foreach($_approved_files as $_f_approved_file){
							
							if($_f_approved_file['approved_status']==2){
			 ?>
             <li>
             <div class="file_name_label" id="file_name_label_<?php echo $_item->getId();?>_<?php echo $_id;?>"><?php echo $_f_approved_file['file'];?></div>
             <div class="qty_label" id="qty_label_<?php echo $_item->getId();?>_<?php echo $_id;?>">x&nbsp;&nbsp; <?php echo $_f_approved_file['quantity'];?></div>
             </li>
             
             
            <?php 
							}
					}
				}
			?> 
             
             <li style="display:none;" id="approved_files_label_li_<?php echo $_item->getId();?>_<?php echo $_id;?>">
             <div class="file_name_label" id="file_name_label_<?php echo $_item->getId();?>_<?php echo $_id;?>">File Name</div>
             <div class="qty_label" id="qty_label_<?php echo $_item->getId();?>_<?php echo $_id;?>">x&nbsp;&nbsp; 01</div></li>
             </ul> 
                          
          </div> 
          </div>
                  <!--Uplod box files ends here-->
                 <div class="clr"></div>
                 
                <?php // print_r($_item->getData()); exit;?> 
               <!--thumbnail listing box ends here--> 
            </li>
            
		
        
        	<?php 
		 }
	 }
	  ?>
         </ul>
         <!--end of Item Listings--> 
      </div>



</div>                

</div>

<?php /*popup to show for dispaly*/ ?>

<div id="loadingGif" >
<div id="imgloading">
<img src="<?php echo $this->getUrl('media');?>/loading11.gif" alt="Loading..."/>
</div>
</div>
 <div id="overlayPopup" class="overlayPopup">
 <div id="approval_popup" >
 <link rel="stylesheet" type="text/css" href=<?php echo $this->getSkinUrl('css/popup.css');?> media="all" />
<!--Popup shows here-->
 
<div id="Overlay">
    	<div id="Popup">
       	  <div id="Popupinner">
            	<div id="overlay_top">
                <h1>Artwork Approval & Print Quantity</h1>
                <div class="close" id="closeBtn"><img src="<?php echo $this->getSkinUrl();?>images/close.jpg" width="43" height="46"  alt=""/></div>
            </div>
            <div id="images_wrapper">
            	<div class="products-img">
                	<div class="img_uploaded" id="img_uploaded">
                    
                    <img id="" src="<?php echo $this->getSkinUrl();?>images/toyota.jpg" width="135" height="93"  alt=""/>
                    </div>
                  <div class="uploaded_text" >
                  <div class="download_file_path"> Download </div> 
                  Print Ready Proof
						<span id="uploadedfileSize" style="color:#aea8a8;clear:both;">File size: 00MB </span>
                        
                  </div>
              </div>
              	<div id="Quantity">
                	<div id="product_heading"><h1>Mesh Custom <span>( Model No. 0000 )</span></h1></div>
                    <div id="Print_Quantity">
                   	  <label>Print Quantity</label>
                        <input type="text" id="input_quantity" class="input-qty" value="1" />
                        
                    </div>
                </div>
                
            </div>
           	<div id="Disclaimer">
                <h2>Disclaimer:</h2>
                <div class="approval-text">
                  <p>Artwork Approval</p>
                  <p>It is the customer's responsibility to ensure that the proof is correct in all areas. Please be sure to double-check spelling, grammar, layout and design before approving artwork.</p>
                  <p>If a proof containing errors is approved by the customer, customer is responsible for payment of all original costs of printing (screens, setup charges, any substrates), including corrections and reprints.</p>
                  <p>The customer is 100% responsible for approvals of Copyright, Trademark and Licensing Agreements of artwork.</p>
                  <p>Customer's signature on artwork approval is contractually binding for payment of all services rendered.</p>
                  <p>All artwork must be approved by the customer with an authorised signature before a job can be entered into production.</p></div>
              <div class="approve-terms">
               	<div class="squaredThree">
					  	<input type="checkbox" value="None" id="squaredThree" name="check" checked="" />
						  <label for="squaredThree"></label>
					  		</div>	
        			<div class="read_terms">
                    I confirm I wish to proceed with the printing of the above file and I confirm I have read the disclaimer
                      <br>
                I have updated the print quantity (  Please consider all approved proofs as printed ). </div>
        
           	  </div>
              <div id="Signature">
              	<div class="Signature">Digital Signature:</div>
                <div class="upload_signature">
                <input class="cSignature" type="text" value=""  placeholder="e.g John Doe" id="cSignature"  />
                </div>
               	</div>
                 <div id="Agreement">
                 <h1 id="current_date_time">Time Stamp:  <?php echo date('dM-Y h:i:s');?></h1>
                <div class="print_agreement agreePrintBtn" id="agreePrintBtn">
                <img src="<?php echo $this->getSkinUrl();?>images/agree_print.jpg" width="212" height="64"  alt=""/></div>
                <div class="print_agreement disAgreeBtn" id="disAgreeBtn" style="display:none;">
                <img src="<?php echo $this->getSkinUrl();?>images/dis_agree_disapprove.png" width="318" height="64"  alt=""/></div>
              </div>
            </div>
       	  </div>
        	</div>
    </div>
</div>
</div>
