<div class="display-list">
<div class="display-list-top">
    <div class="find-item">
                       <img src="<?php echo $this->getSkinUrl();?>images/icon-magnifier.png" alt=""/><span class="find-heading">Find Your Perfect Display</span> Rollover the categories for a quick description of our products.
    </div>
</div>
<div class="display-list-content">
    <table cellspacing="0" cellpadding="0" border="0" width="100%">
        <tbody>
            
            <tr>
            
            
            <?php
            
            $store = Mage::app()->getStore()->getId();
                
                $rootId     = Mage::app()->getStore($store)->getRootCategoryId();
                
                $collection = Mage::getModel('catalog/category')->getCollection()
                ->addFieldToFilter('path', array('like'=> "1/$rootId/%"))
                ->addAttributeToSelect('name')
                ->addAttributeToSelect('is_active')
                ->addAttributeToSelect('thumbnail')
                ->addAttributeToSelect('url')
                ->addAttributeToSelect('description')
                ->addAttributeToFilter('is_active', 1)
                ->addAttributeToFilter('is_featured', 148)
                ->setPage(0, 15)
                ->load();
                //echo "Count :".$collection->count();
                $counteri = 0;
				$counter = 0;
                foreach ($collection as $_childCategory){
                    $counteri++;
					$counter++;
                    
					$_img= $_childCategory->getThumbnail();
                    $catName=$_childCategory->getName();
                    $getCatUrl=$_childCategory->getUrl();
                    $cur_category=Mage::getModel('catalog/category')->load($_childCategory->getId());
                    // echo $getCatUrl;
					// exit;
            ?>
            
            <td class="<?php if($counteri==6){ echo 'last'; }?>">
            <div class="display-list-category-img"> 
            <a onmousemove="onHover(this);" title="<?php echo $catName; ?>" href="<?php echo $getCatUrl; ?>">
                <img width="153" height="136" onmousemove="onHover(this);" src="<?php echo Mage::getBaseUrl('media').'catalog/category/'.$cur_category->getThumbnail()  ?>" alt="<?php echo $catName; ?>">
                
                <span class="display-list-category-details" style="display:none;">
                    <span class="display-list-category-details-top"></span>
                      <span class="display-list-category-details-content">
                        <table cellspacing="0" cellpadding="0" border="0" width="100%">
                            <tbody>
                                <tr>
                                    <td width="210">
                                        <img width="210" height="187" src="<?php echo Mage::getBaseUrl('media').'catalog/category/'.$cur_category->getThumbnail()  ?>" alt="<?php echo $catName; ?>"></td>
                                    <td width="5">
                                    </td>
                                    <td class="description-td">
                                        <p><strong><?php echo $catName; ?></strong></p>
                                        <p></p><p style="font-size:14px; padding-top:8px; line-height:22px;">
                                        <?php //echo $cur_category->getShortDescription(); ?>
                                        <?php echo $cur_category->getDescription(); ?>
                                        </p><p></p>	
                                        <p><button class="browse" onclick="setLocation('<?php echo $getCatUrl; ?>');" title="Browse"><span>Browse</span></button></p>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </span>
                      <span class="display-list-category-details-bottom"></span>
                </span>
                
            </a>
            </div>
            <div class="display-list-category-button">
                <span class="forfetcatname" onclick="setLocation('<?php echo $getCatUrl; ?>');"><?php echo $catName; ?></span><span class="forcartimg"></span>
            </div>
            &nbsp;
            </td>
            <?php
			if($counter==5){
				
				$counter=0;
				echo '</tr>';
				
				}
			
			} ?>
            
            
            
            
        </tbody>
    </table>
</div>
<!--<div class="display-list-bottom"></div>-->
</div>
<div class="display-list-top" style="display:none;">
    <div class="find-item">
                       <span class="find-heading">Our Products</span>     </div>
</div>
                        <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('allproducts_13expo')->toHtml() ?>
