<?php
/**
 * MD_Vividslider.
 * Company: Vivid Ads Inc Australia
 * Author: AShfaq Ahmed
 * 
 *
 * NOTICE OF LICENSE
 *
 *
 * It is also available through the world-wide-web at this URL:
 * http://www.vividads.com.au
 *
 * @category   MD
 * @package    Vividslider
 * @copyright  Copyright (c) 2014 Vivid Ads Ashfaq Ahmed (http://www.vividads.com.au)
 
 * @see MD_Vividslider_Adminhtml_Block_Vividslider
 */
 
  
?>
<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;">
        <h3 class="icon-head head-products"><?php echo Mage::helper('vividslider')->__('Manage Slider') ?></h3></td>
        <td class="a-right">
            <?php echo $this->getButtonsHtml() ?>
        </td>
    </tr>
</table>
</div>
<?php  if( !$this->isSingleStoreMode() ): ?>
<?php echo $this->getChildHtml('store_switcher');?>
<?php  endif;?>
<div>
    <?php echo $this->getGridHtml() ?>
</div>
