<?php
/**
 * Checkout success template
 *
 * Replaces: app/design/frontend/base/default/template/checkout/multishipping/success.phtml
 *
 * @author Aptoplex
 * @copyright 2015 Aptoplex
 *
 * @var $this Mage_Checkout_Block_Multishipping_Success
 */

$uploadButtonTitle = Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_CHECKOUT_SUCCESS_UPLOAD_BTN_TITLE);
if (!isset($uploadButtonTitle)) $uploadButtonTitle = 'Upload Your Files';

$uploadButtonClassName = Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_CHECKOUT_SUCCESS_UPLOAD_BTN_CSS_CLASS_NAME);
if (!isset($uploadButtonClassName)) $uploadButtonClassName = 'btn-upload';

$targetUrl = $this->getUrl() . Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_UPLOADER_URL, null);

?>

<style>
    #artwork-upload-section { margin-top: 40px; }
    #uploader-buttons { margin-top: 20px; }
</style>

<div class="multiple-checkout">
    <div class="page-title">
        <h1><?php echo $this->__('Order Success') ?></h1>
    </div>
    <h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h2>
    <p><?php echo $this->__('We are processing your order and you will soon receive an email with details of the order. Once the order has shipped you will receive another email with a link to track its progress.') ?></p>
    <?php if($_orderIds = $this->getOrderIds()): ?>
        <p>
            <?php $flag = false ?>
            <?php echo $this->__('Your order number is ') ?>
            <?php foreach ($_orderIds as $orderId=>$incrementId): ?>
                <?php if ($flag): ?>
                    <?php echo ', ' ?>
                <?php endif; ?>
                <?php $flag = true ?>
                <a href="<?php echo $this->getViewOrderUrl($orderId) ?>"><?php echo $incrementId ?></a>
            <?php endforeach; ?>
        </p>
    <?php endif; ?>
    <?php echo $this->getChildHtml() ?>

    <div id="artwork-upload-section">
        <?php echo Mage::getStoreConfig(Aptoplex_EasyUploader_Helper_Data::XML_PATH_CHECKOUT_SUCCESS_MAIN_HTML); ?>
        <div id="uploader-buttons">
            <button class="<?php echo $uploadButtonClassName ?>" onclick="window.location='<?php echo $targetUrl ?>'" title="<?php echo $uploadButtonTitle ?>" type="button"><span><?php echo $uploadButtonTitle ?></span></button>
        </div>
    </div>

    <div class="buttons-set">
        <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button" onclick="setLocation('<?php echo $this->getContinueUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
    </div>
</div>