<html xmlns="http://www.w3.org/1999/xhtml" xmlns:svg="http://www.w3.org/2000/svg">
<style type="text/css">
.product-view .product-img-box .more-views li {
	/*  border: 1px solid #DDDDDD;*/
	border-radius: 5px;
	float: left;
	margin: 0 0 0 27px !important;
}
.product-view .product-img-box .more-views h2 {
	border-bottom: none 0px !important;
	font-size: 11px;
	margin: 0 0 8px;
	text-transform: uppercase;
}
   
   
/*.product-img-box .more-views {
    border: 1px solid #ddd;
    border-radius: 5px;

    padding: 10px 0 4px;
    width: 580px;
    float: left;
    margin-top: 15px;

}*/
.product-img-box .more-views {
	/* border: 1px solid #ddd;
    border-radius: 5px;*/
	padding: 10px 0 4px;
	width: 100%;
	float: left;
	margin-top: -65px;
}
.list_carousel {
	width: 98% !important;
	float: left;
	padding: 0px !important;
	margin: 0px !important
}
#wrapper {
/*border:1px solid #dddddd !important;*/
}
.caroufredsel_wrapper {
	width: 98% !important;
	margin: 0px !important;
	padding: 0px !important;
}
#carouselGallery {
	left: 2px !important;
}
#prevGallery {
	left: 0 !important;
	z-index: 10000 !important;
}
#nextGallery {
	left: 98% !important;
}
.fancybox {
	width: 100% !important;
	padding: 0 !important;
}
#mainImage {
	height: 481px !important;
	max-height: 481px !important;
	width: auto !important;
	max-width: 1200px;
}
</style>
<?php

/**

* @author Amasty Team

* @copyright Copyright (c) 2010-2013 Amasty (http://www.amasty.com)

* @package Amasty_Zoom

*/

?>
<?php
     $_product = $this->getProduct();

	//var_dump(count($_product->getMediaGalleryImages()));

	 $imageUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'catalog/product' . $_product->getImage(); ?>
<?php 

    $_helper  = $this->helper('catalog/output');

    $_preloadText    = $this->__('Loading');

    $_thumbSize      = Mage::getStoreConfig('amzoom/size/thumb');

    $_previewWidth   = intval(Mage::getStoreConfig('amzoom/size/preview_width'));

    $_previewHeight  = intval(Mage::getStoreConfig('amzoom/size/preview_height'));

    $_zoomerEnable   = Mage::getStoreConfig('amzoom/zoom/enable');

    $_lightboxEnable = Mage::getStoreConfig('amzoom/lightbox/enable');

    $_carouselEnable = Mage::getStoreConfig('amzoom/carousel/enable');

    $_carouselDirection = Mage::getStoreConfig('amzoom/carousel/carousel_direction');

//    $_carouselCountOfItems = intval(Mage::getStoreConfig('amzoom/carousel/visible_items'));

    $_carouselCountOfItems = 14;

    $_carouselWidth  = $_thumbSize * $_carouselCountOfItems + 4 * 5 + 20;

    $_carouselHeight = 50 + ($_carouselCountOfItems - 1) * 65;

    if ($_carouselWidth > intval(Mage::getStoreConfig('amzoom/size/preview_width'))) {

        $_thumbSize = 50;
        $_carouselWidth = 500;

    }

    $vlink = $_product->getData('introvideo');
	//echo $vlink;

	$mainlink = $vlink;
    $mainlinkarr = explode("/",$mainlink);
    $vedioid= end($mainlinkarr);

?>

<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<?php if ($_zoomerEnable): ?>

<div style="position: relative;">
  <?php if ('true' == (string) Mage::getConfig()->getNode('modules/Amasty_Label/active')): ?>
  <div class="amlabel-div"> <?php echo Mage::helper('amlabel')->getLabels($_product, 'product') ?>
    <?php endif; ?>
    <p class="product-image">
      <?php

                    $_img = '';

                    if (count($this->getGalleryImages()) > 0 && $_carouselDirection == 'left' && $_carouselEnable) {

                        $_img .= '<div id="gallery" style="position: relative; top:0px; left:0px; float: left;">'.

                                    '<div style="position: relative;">';

                                    if ($_carouselEnable){

                                        $_img .= '<div id="prevGallery" style="position: absolute; clear: both; float: none; top: -10px; left: 24px;" class="MagicScrollArrowsUpDown MagicScrollArrowUp"></div>';

                                        $_img .= '<div class="list_carousel" style="padding-top:'. ($_previewHeight - $_carouselHeight)/2 .'px">';

                                        $_img .= '<ul id="carouselGallery">';

                                    } else {

                                        $_img .= '<div><ul>';

                                    }

                                    foreach ($this->getGalleryImages() as $_image){

                                        if ($_zoomerEnable){

                                            if ($_carouselEnable){

                                                $_img .= '<li style="margin:0">';

                                            } else {

                                                $_img .= '<li>';

                                            }

                                            $_img .= '<a class="fancybox" onclick="return false;" href="'.$this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" rel="lightbox['.$_product->getId() .']" title="'.$this->htmlEscape($_image->getLabel()) .'" style="width: '.$_thumbSize.'px; height: '.$_thumbSize.'px; border: 1px solid #DDDDDD;">'.

                                                        '<img src="'.$this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_thumbSize).'" width="'.$_thumbSize.'" height="'.$_thumbSize.'" alt="'.$this->htmlEscape($_image->getLabel()).'"/>'.

                                                        '<img style="display: none; z-index: 100; position: absolute; margin-left:' . (-$_thumbSize/2 - 15).'px; margin-top: '.($_thumbSize/2 - 14).'px; width: 30px; height: 28px" src="'.Mage::getBaseUrl('js') . 'amasty/amzoom/images/preloaderSmall.gif'.'" alt="Preloader"/>'.

                                                    '</a>'.

                                                '</li>';

                                        } else {

                                            $_img .= '<li>'.

                                                        '<a href="#" onclick="popWin(\''.$this->getGalleryUrl($_image).'\', \'gallery\', \'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes\'); return false;"><img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_thumbSize) . '" width="' .$_thumbSize . '" height="' . $_thumbSize.'" alt="' . $this->htmlEscape($_image->getLabel()) . '" /></a>'.

                                                    '</li>';

                                        }

                                    }

                                    $_img .= '</ul>'.

                                        '</div>';

                                    if ($_carouselEnable){

                                        $_img .= '<div id="nextGallery" style="position:absolute; clear: both; float: none; top:'. (intval(Mage::getStoreConfig('amzoom/size/preview_height')) - 13) .'px; left: 24px" class="MagicScrollArrowsUpDown"></div>';

                                    }

                        $_img .=   '</div>'.

                                '</div>';

                    }

                    $_preloaderMargin = ($_previewWidth - 110)/2 + 5;

                    if (Mage::getStoreConfig('amzoom/carousel/carousel_direction') == 'left' && $_carouselEnable) {

                        $_preloaderMargin = ($_previewWidth + $_thumbSize + 10 - 110/2)/2 + 5;

                    }

                    $_img .= '

                        <div id="wrapper" style="position: relative; float: left; min-width: '.($_previewWidth+2).'px; min-height: ' . ($_previewHeight + 2) . 'px; width: '.($_previewWidth+2).'px; height: ' . ($_previewHeight + 2) . 'px;">

                            <a class="fancybox" href="'.$this->helper('catalog/image')->init($_product, 'image').'" rel="zoomer" onclick="return false;" style="display: block; background-color: white; position: relative;">

                                <img itemprop="image" id="mainImage" style="border: 1px solid inset #fff; z-index: 100; opacity: 1; filter: alpha(opacity = 100); max-height: ' . $_previewHeight . 'px" src="'.$imageUrl. '" alt="' . $this->htmlEscape($_product->getName()) . '" title="'.$this->htmlEscape($this->getImageLabel()).'"/>

                            </a>

                        </div>

                        <div id="preloader" style="display: none; position: absolute; top: ' . ($_previewHeight/2 - 45/2) . 'px; left:' . $_preloaderMargin . 'px; background: white; width: 110px; opacity: 0.7; filter: alpha(opacity = 70);">

                            <div style="float:left;"><img style="" src="' . Mage::getBaseUrl('js') . 'amasty/amzoom/images/preloader.gif" alt="Preloader"/></div>

                            <div style="position: absolute; left: 50px; margin-right: 2px; margin-top: 12px; font-weight: bold"> ' . $_preloadText . '... </div> 

                        </div>

                    ';

                    echo $_helper->productAttribute($_product, $_img, 'image');

                ?>
    </p>
    <?php if ('true' == (string)Mage::getConfig()->getNode('modules/Amasty_Label/active')): ?>
  </div>
  <?php endif; ?>
</div>
<?php else: ?>
<?php if ('true' == (string)Mage::getConfig()->getNode('modules/Amasty_Label/active')): ?>
<div class="amlabel-div"> <?php echo Mage::helper('amlabel')->getLabels($_product, 'product') ?>
  <?php endif; ?>
  <p class="product-image product-image-zoom">
    <?php

             $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';

             echo $_helper->productAttribute($_product, $_img, 'image');

            ?>
  </p>
  <?php if('true' == (string)Mage::getConfig()->getNode('modules/Amasty_Label/active')): ?>
</div>
<?php endif; ?>
<?php endif; ?>
<?php if (!$_zoomerEnable): ?>
<p class="zoom-notice" id="track_hint"><?php echo $this->__('Double click on above image to view full picture') ?></p>
<div class="zoom"> <img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
  <div id="track">
    <div id="handle"></div>
  </div>
  <img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" /> </div>
<script>

        //<![CDATA[

            <?php if (!Mage::app()->getRequest()->isAjax()): ?>

            Event.observe(window, 'load', function() {

                product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');

            });

            <?php else: ?>

            setTimeout("product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');", 1000);

            <?php endif; ?>

        //]]>

        </script>
<?php endif; ?>
<?php else: ?>
<p class="product-image">
  <?php

           // if base image wasn't selected

           $_img = '<div style="position: relative;">

                        <div id="wrapper" style="position: relative; float: left; min-width: '.($_previewWidth+2).'px; min-height: ' . ($_previewHeight + 2) . 'px; width: '.($_previewWidth+2).'px; height: ' . ($_previewHeight + 2) . 'px;">

                            <a class="fancybox ijaz" href="'.$this->helper('catalog/image')->init($_product, 'image').'" rel="zoomer" onclick="return false;" style="display: block; background-color: white; position: relative;">

                                <img id="mainImage"  style="border: 1px solid #fff; z-index: 100; opacity: 1; filter: alpha(opacity = 100); max-width: '.$_previewWidth.'px; max-height: ' . $_previewHeight . 'px" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($_previewWidth, $_previewHeight) . '" alt="' . $this->htmlEscape($_product->getName()) . '" title="'.$this->htmlEscape($this->getImageLabel()).'"/>

                            </a>

                        </div>

                        <div id="preloader" style="display: none; position: absolute; top: ' . ($_previewHeight/2 - 45/2) . 'px; left:' . $_preloaderMargin . 'px; background: white; width: 110px; opacity: 0.7; filter: alpha(opacity = 70);">

                            <div style="float:left;"><img style="" src="' . Mage::getBaseUrl('js') . 'amasty/amzoom/images/preloader.gif" alt="Preloader"/></div>

                            <div style="position: absolute; left: 50px; margin-right: 2px; margin-top: 12px; font-weight: bold"> ' . $_preloadText . '... </div> 

                        </div>

                    </div>

                    ';

            echo $_helper->productAttribute($_product, $_img, 'image');

        ?>
</p>
<?php endif; ?>
<script>

    <?php if ($_zoomerEnable): ?>

        <?php if (!Mage::app()->getRequest()->isAjax()): ?>

            Event.observe(window, 'load', function(){

        <?php endif; ?>

        new AmZoomer();

        <?php if (!Mage::app()->getRequest()->isAjax()): ?>

            });

        <?php endif; ?>

    <?php endif; ?>

</script>
<?php //echo $_carouselEnable; ?>
<?php if (count($this->getGalleryImages()) > 0 && ($_carouselDirection != 'left' || !$_carouselEnable)): ?>
<!--<div class="more-views" >
  <div style="position: relative;">
    <?php if ($_carouselEnable): ?>
    <div id="prevGallery" style="position: absolute; clear: both; float: none; top: 20px; left: -10px;" class="MagicScrollArrows MagicScrollArrowPrev"></div>
    <?php endif; ?>
    <div class="<?php echo ($_carouselEnable)? 'list_carousel' : '' ?>" style="<?php echo ($_carouselEnable)? 'padding-left: '. ((intval(Mage::getStoreConfig('amzoom/size/preview_width')) - ($_carouselWidth - 5*2))/2 + 5) .'px;' : ''?>">
      <ul <?php echo ($_carouselEnable)? 'id = "carouselGallery"' : '' ?> class="shabbir">
        <?php /*  for($i=0; $i<= count($_product['media_gallery']['images'])-1; $i++){ */ ?>
        <?php 
				/* temp fixation later it will be diverted */
		?>
         <?php  for($i=0; $i< 1; $i++){  
		 		//var_dump($_product['media_gallery']);
		  ?>
        <?php  if($_product['media_gallery']['images'][$i]['position'] <99){?>
        <?php  if($_product['media_gallery']['images'][$i]['disabled']==0){ ?>
        <?php //foreach ($this->getGalleryImages() as $_image): ?>
       
        <?php if ($_lightboxEnable): ?>
        <li style="margin:0" class="<?php echo $_product['media_gallery']['images'][$i]['position'] ?>">
          <?php    $url =Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/product'.$_product['media_gallery']['images'][$i]['file'];?>
          <a class="myHover fancybox" onClick="return false;" href="<?php echo $url; ?>" rel="lightbox[<?php echo $_product->getId(); ?>]" title="<?php echo $_product->getName()?>" style="width: <?php echo $_thumbSize; ?>px; height: <?php echo $_thumbSize; ?>px; border: 1px solid #DDDDDD;"> <img width="<?php echo $_thumbSize; ?>" height="<?php echo $_thumbSize; ?>" src="<?php echo $url;?>" alt="<?php echo $_product->getName()?>" /> <img style="display: none; z-index: 100; position: absolute; margin-left:<?php echo (-$_thumbSize/2 - 15)?>px; margin-top: <?php echo ($_thumbSize/2 - 14)?>px" src="<?php echo Mage::getBaseUrl('js') . 'amasty/amzoom/images/preloaderSmall.gif' ?>" alt="Preloader"/> </a> </li>
        <?php else: ?>
        <li> <a href="#" onClick="popWin('<?php echo $this->getGalleryUrl($_image) ?>', 'gallery', 'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;"> 
          
          <!--<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_thumbSize); ?>" width="<?php echo $_thumbSize; ?>" height="<?php echo $_thumbSize; ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />-->
          
          <?php                               $url =Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/product'.$_product['media_gallery']['images'][$i]['file'];?>
          <img width="<?php echo $_thumbSize; ?>"  height="<?php echo $_thumbSize; ?>" src="<?php echo $url;?>" alt="<?php echo $_product->getName()?>" /> </a> </li>
        <?php endif; ?>
        <?php } } } // endforeach; ?>
      </ul>
    </div>
    <?php if ($_carouselEnable): ?>
    <div id="nextGallery" style="position:absolute; top:20px; left: <?php echo (intval(Mage::getStoreConfig('amzoom/size/preview_width')) - 11) . 'px'?>" class="MagicScrollArrows"></div>
    <?php endif; ?>
  </div>
</div>-->
<?php endif; ?>

<!--       new icons adjusted here.--> 
<!--<div  style=" float:left;position: relative;left:10px;top:-542px;width:545px;">
<ul style="float:left; width:545px;padding:5px; margin-top:5px; text-align:center;  font-family:Arial;">
        <?php
		    //  $productId = $_product->getId();
//              $product = Mage::getModel('catalog/product')->load($productId);//product id here
//              foreach ($product->getMediaGalleryImages() as $image) {
//              if($image->getPosition()>300 && $image->getPosition()<400)  {
//              echo '<li><img src="'.$image->getUrl().'" alt =""/></li>';
//              //echo $image->getPosition();
//              //	var_dump($image);
//                }   }     ?>
        </ul>
     </div>--> 

<!--  new icons ends here.--> 

<!-- Testimonial starts-->



<!-- Testimonials ends-->

<?php 
 
//echo  $_product['media_gallery']['images'][58]['position'];

 //var_dump($_product['media_gallery']['images']);?>
<script type="application/javascript">
 
//jQuery( ".myHover" ).mouseleave(function() {
//var elements = jQuery('#mainImage');
//var id = '<?php echo $imageUrl; ?>';
//	 console.log(id);
//setTimeout(function(){ jQuery(elements).attr("src", id); }, 30000);
//
////console.log(elements);
//	});


</script>
<div class="order_process">
<img src="<?php echo $this->getSkinUrl('images/order_process.png')?>" />
<img src="<?php echo $this->getSkinUrl('images/numbers.png');?>" width="1200" alt="Vivid Contact Info" />
</div>