<?php
/**
 * Manufacturers extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   FME
 * @package    Manufacturers
 * @author     Kamran Rafiq Malik <kamran.malik@unitedsol.net>
 * @copyright  Copyright 2010 © free-magentoextensions.com All right reserved
 */
?>
<link type="text/css" href="<?php echo $this->getSkinUrl(); ?>css/faqs/accordion.css" rel="stylesheet">
<div class="intro">
<p>
Head Office<br> 

<span>Vivid Ads Pty. Ltd. (ABN  49210655341)</span><br>
<span>1/2 Phillip Court,  Port Melbourne</span><br>
<span>Victoria 3207 Australia</span><br>
<span>Tel:     1300 72 16 14 (Australia wide)</span><br>
<span>Fax:    03 8456 6234</span><br> </p>
</div>
<?php 
$topics = $this->getTopics();
?>
<div class="faq_wrapper">
<div class="faq-title">
   <h1><?php echo Mage::helper('faqs')->__("FAQ's Categories") ?></h1>
</div>
<?php if ( count($topics) == 0 ) : ?>    
		<p class="empty"><?php echo Mage::helper('faqs')->__('No Category find yet!') ?></p>
<?php else : ?>
	<div class="accordion4"> 
		 <?php foreach ($topics as $_topic): ?>
				<h3><a href="<?php echo Mage::helper('faqs')->getUrl($_topic['identifier']); ?>"><?php echo $_topic["title"]; ?></a></h3>
		 <?php endforeach; ?>
	</div>
<?php endif; ?>

<div class="faq-image"><img src="<?php echo $this->getSkinUrl()?>images/faq.png" alt="Faq" title="Ask a Question" width="270"/></div>
</div>
