<div class="c-centers">
    <div class="thumbs-category">
      <ul>
        <li>
          <div class="mesh-add"><a href="<?php echo $this->getUrl('mesh-ad-banners-a.html')?>"><img src="<?php echo $this->getSkinUrl()?>images/event_add_banner.jpg" style="border:none 0px;" /></a>
            <div class="right-headings">
              <h1>Mesh Ad Banners ™</h1>
              <p>Mesh Banners are widely used as outdoor 
                signs to advertise. They are printed in 1400dpi 
                full color.</p>
              <div class="browse-btns">
              <a href="<?php echo $this->getUrl('mesh-ad-banners-a.html')?>">Click To Browse</a>
              </div>
            </div>
          </div>
        </li>
        <li>
          <div class="constructions-add"><a href="<?php echo $this->getUrl('construction-fence-signs.html')?>"><img src="<?php echo $this->getSkinUrl()?>images/construction_banner.jpg" style="border:none 0px;" /></a>
            <div class="right-headings">
              <h1>Construction Ad Mesh ™<br>
              </h1>
              <p>Our construction mesh banners are widely used on <br>
              construction sites as tools for advertising</p>
              <div class="browse-btns">
              <a href="<?php echo $this->getUrl('construction-fence-signs.html')?>">Click To Browse</a>
              </div>
            </div>
          </div>
        </li>
        <li>
          <div class="builder-add"><a href="<?php echo $this->getUrl('builders-fence-signs.html')?>"><img src="<?php echo $this->getSkinUrl()?>images/add-banner.jpg" style="border:none 0px;" /></a>
            <div class="right-headings">
              <h1>Builders Ad Mesh ™<br>
              </h1>
              <p>Builder mesh is used by hundreds of builders to <br>
              advertise their brand on display sites </p>
              <div class="browse-btns">
              <a href="<?php echo $this->getUrl('builders-fence-signs.html')?>">Click To Browse</a>
              </div>
            </div>
          </div>
        </li>
        <li>
          <div class="fence-add"><a href="<?php echo $this->getUrl('fence-ad-signs.html')?>"><img src="<?php echo $this->getSkinUrl()?>images/fence_add.jpg" style="border:none 0px;" /></a>
            <div class="right-headings">
              <h1>Fence Ad Mesh ™<br>
              </h1>
              <p>Fence mesh banner are used at outdoor events to advertise of fences and barricades</p>
              <div class="browse-btns">
              <a href="<?php echo $this->getUrl('fence-ad-signs.html')?>">Click To Browse</a>
              </div>
            </div>
          </div>
        </li>
        
        
      </ul>
    </div>
  </div>
<div class="display-list-top" style="display:none;">
    <div class="find-item">
                       <span class="find-heading">Our Products</span>     </div>
</div>
                        <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('allproducts_13expo')->toHtml() ?>