<style type="text/css">

.clnews-newsitem-view .products-grid li.item {

    display: block;

    float: left;

    margin-right: 20px;

    overflow: hidden;

    padding: 0;

    position: relative;

    width: 226px;

}

.clnews-newsitem-view 

.products-grid .product-image {



    border: none 0px;

    display: block;

    height: 127px;

    margin: 0 auto;

    padding: 0;

    text-align: center;

    width: 226px;

}

.news-item-content .social{

	display:none;

	}

.clnews-newsitem-view.products-grid{

    margin: 0 auto 20px;

    width: 1100px !important;

}

	

</style>

<div>



<?php echo $this->getPagerHtml(); ?>

    <ul class="products-grid first odd" style="width:1100px; margin:0px 30px 0px 30px;">

        <?php

        $Media = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);

        $objLogos = new Mconnect_Brandlogo_Model_Brandlogo();

        $logos = $objLogos->getAllLogos();

        $i = 1;
//echo count($logos);
        foreach ($logos as $logo) {

            ?>    

            <li class='item <?php if ($i == 1) echo "first";if($i%4 == 0)echo "last"; ?> fadeIn animated' style="min-height: 100px;padding:0;margin:0px 30px 30px 0px;">

                <span class="product-image"><img src='<?php echo $Media ?>brandlogo<?php echo $logo['filename'] ?>' title='<?php echo $logo['title'] ?>' alt='<?php echo $logo['title'] ?>' /></span>

            </li>    

         

            <?php

            $i++;

        }

        ?>

    </ul>    
 <?php echo $this->getPagerHtml(); ?>
</div>   

