<?php 
		 /*
		 removing cart items
		 $cart = Mage::getSingleton('checkout/cart'); 
$quoteItems = Mage::getSingleton('checkout/session')
                  ->getQuote()
                  ->getItemsCollection(); 
 
foreach( $quoteItems as $item ){
    $cart->removeItem( $item->getId() );       
}
$cart->save();   
		 */
		 $cart = Mage::getSingleton('checkout/session')->getQuote();
   		 $cartItems = $cart->getAllVisibleItems();
   
    if(Mage::Registry('current_product')){
   	  $c_product = Mage::Registry('current_product')->getProduct_id();    
		   foreach($_items as $_item){ 
				$_product = Mage::getModel('catalog/product')->load($_item->getProduct_id());
					/*
					if($c_product == $_product->getProduct_id()){
					 	echo '<script language="javascript"> window.location.href="'.Mage::getUrl('checkout/cart/').'"; </script>';
				}
				*/
		   }
	}
?>
<script type="text/javascript">
//<![CDATA[
document.oncontextmenu =new Function("return false");
var message="<?php echo __('All pictures and contents are Copyright © Vividads.com.au aggressively enforces copyright infringments!.');?>";
document.oncontextmenu=new Function("alert(message);return false")
//]]>

  function showminicart(){	  	  
	   if(jQuery('#shopping_cart_top').is(":visible")==true){
			  jQuery('#shopping_cart_top').hide();
			 }else{
		  	   jQuery('#shopping_cart_top').show();
			  }			
	  }
</script>
<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
 $currentUrl = "";
if (!in_array(Mage::app()->getFrontController()->getAction()->getFullActionName(), array('cms_index_noRoute', 'cms_index_defaultNoRoute'))) {
    $currentUrl = Mage::helper('core/url')->getCurrentUrl();
    $currentUrl = basename($currentUrl);
	$customer_pages = 0;
}
//echo $currentUrl;
 $curUrl = Mage::helper('core/url')->getCurrentUrl();
$needle = 'sales';
$imgcheck = 1;
if (strpos($curUrl,$needle) !== false) {
     $imgcheck = 0;
}
$needle = 'customer/';
if (strpos($curUrl,$needle) !== false) {
     $imgcheck = 0;
}
$needle = 'CrmTicket';
if (strpos($curUrl,$needle) !== false) {
     $imgcheck = 0;
}
$needle = 'Quotation';
if (strpos($curUrl,$needle) !== false) {
     $imgcheck = 0;
}
$needle = 'fetchOrder';
if (strpos($curUrl,$needle) !== false) {
     $imgcheck = 0;
}
if ($currentUrl=='account' || $currentUrl=='List' || $currentUrl=='history' || $currentUrl=='invhistory'  || $currentUrl=='address' || $currentUrl=='1' || $currentUrl=='2' || $currentUrl=='MyTickets'|| $currentUrl=='NewTickets' || $currentUrl=='List' || $currentUrl=='NewRequestSelectOrder' || $currentUrl=='edit'
|| $currentUrl=='wishlist' || $currentUrl=='products' || $imgcheck==0){
	$customer_pages = 1;
	}
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<div class="header-container">
  <div class="header" style="margin:0px;">
    <div style="float: left; width: 100%; background:#E5E5E5; height: 45px;" class="header_top">
      <div class="top_left" style="width:33%; float:left;padding-top: 5px; text-align:left;">
        <h1 style="margin-top: 0px ! important; margin-right: 0px ! important; margin-bottom: 0px ! important; padding: 0px ! important; color:#565656; float: left; margin-left: 130px;line-height:12px; font-size:10px;">
          <?php if ($this->getIsHomePage()):?>
          <?php 
		$curent_metaTitle = Mage::getSingleton('cms/page')->getMeta_title();
		$current_metaDescription =  Mage::getSingleton('cms/page')->getMeta_description();
		if(strlen($curent_metaTitle)>230){ echo substr($curent_metaTitle,0,230).".." ;	  
		  } else{		 
		   echo $curent_metaTitle;	  
	   	}
     ?>
          <?php else:?>
          <?php 
		$current_product = Mage::registry('current_product');
		$curent_metaTitle = '';
		$current_metaDescription='';
		if($current_product != null)
		{	
			$curent_metaTitle = $current_product->getMeta_title();			 
			$current_metaDescription =  $current_product->getMeta_description();
		}else{
			$current_category = Mage::getModel('catalog/layer')->getCurrentCategory();
			//echo $current_category->getMeta_title();
			$curent_metaTitle = $current_category->getMeta_title();			 
			$current_metaDescription =  $current_category->getMeta_description();
	 }
		if(strlen($curent_metaTitle)>230){ echo substr($curent_metaTitle,0,230).".." ;	  
		  } else{		 
		   echo $curent_metaTitle;	  
	   	}
	?>
          <?php endif?>
        </h1>
      </div>
      <div class="top_center" style="width:35%; float:left;padding-top: 5px;"> <img style="float:left; margin-right:12px;" src="<?php echo $this->getSkinUrl('images/phoneInfo.png');?>" alt="Mon To Fri (9:30-4:30) Our Working Hours" /> <?php echo $this->getLayout()->createBlock('sharingtool/share')->setBlockId('addthis_sharetool')->toHtml(); ?> 
        <!--<ul style=" float:left;padding-left:25px;">
  <li style=" float:left;margin-right: 10px;">
  <a href=" https://www.facebook.com/Vividads
" class="fbicon"><img src="<?php echo $this->getSkinUrl('images/fbsocialicon.png');?>" alt="icon" />
  </a></li>
  <li style=" float:left;margin-right: 10px;"><a href="" class="gplusicon"><img src="<?php echo $this->getSkinUrl('images/gplusicon.png');?>" alt="icon" /> </a></li>
  <li style=" float:left;margin-right: 10px;"><a href="" class="tweeticon"><img src="<?php echo $this->getSkinUrl('images/twittericon.png');?>" alt="icon" /> </a></li>
  <li style=" float:left;margin-right: 10px;"><a href="" class="youtubeicon"><img src="<?php echo $this->getSkinUrl('images/youtubeicon.png');?>" alt="icon" /> </a></li>
  <li style=" float:left;"><a href="" class="vimeoicon"><img src="<?php echo $this->getSkinUrl('images/vimeoicon.png');?>" alt="icon" /> </a></li>
  </ul>--> 
      </div>
      <div class="top_right" style="width:32%; float:left; text-align:right; font-family:"Raleway",sans-serif;">
        <?php 
	  		//if custome is logged in then show this
			$current_customer = Mage::getSingleton('customer/session')->getCustomer();
			$session = Mage::getSingleton('customer/session', array('name'=>'frontend')); 
		if( $session->isLoggedIn() ){	
	  ?>
        <div class="customerinfo" style="color:#666;float:left;position:relative;text-align: center;top: 13px;width:200px; font-family:'Raleway',sans-serif"> Hello, <span style="color:#2290cd"><b><?php echo $current_customer->getName();?>!</b></span> </div>
        <?php 
		}
	  ?>
        <div class="account_links" style="margin:0px; ">
          <ul style="width:218px;">
            <li><a href="<?php echo $this->getUrl(); ?>customer/account/"> <img src="<?php echo $this->getSkinUrl()?>images/my_accont.jpg" title="<?php echo $this->__('My Account')?>" alt="<?php echo $this->__('My Account')?>"  /> </a> </li>
            <?php if (! Mage::getSingleton('customer/session')->isLoggedIn()): ?>
            <li> <a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"> <img src="<?php echo $this->getSkinUrl()?>images/login.jpg" title="<?php echo $this->__('Login')?>" alt="<?php echo $this->__('Login')?>"  /> </a> </li>
            <?php else:?>
            <li><a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>"> <img src="<?php echo $this->getSkinUrl()?>images/logout.jpg" title="<?php echo $this->__('Logout')?>" alt="<?php echo $this->__('Logout')?>"  /> </a></li>
            <?php endif ;?>
            <li>
              <?php 
		  		$cart = Mage::getSingleton('checkout/session')->getQuote();
				$cartItems = $cart->getAllVisibleItems();
				$carQty = $cart->getItems_qty();
		  ?>
              <a href="javascript:void(0)" onClick="showminicart()" style="float:right;"> <img src="<?php echo $this->getSkinUrl('images/minishoppingcart.png');?>" height="27" /> <?php echo round($carQty);?></a> </li>
          </ul>
          <!--mini-shopping cart -->
          <div id="shopping_cart_top" class="top-dropdowns" style="display:none; position: absolute; right: 0%; top: 37px; width: 300px; background-color: #fff; border: 1px solid #a4a4a4; padding: 5px; z-index:99999;"> <?php echo $this->getChildHtml('cartTop') ?> </div>
          <!--end of mini-shopping cart --> 
        </div>
      </div>
    </div>
    <!-- <div class="header_content">
      <?php 
		$current_product = Mage::registry('current_product');
		$curent_metaTitle = '';
		$current_metaDescription='';
	if($current_product != null)
		{	
			$curent_metaTitle = $current_product->getMeta_title();
			$current_metaDescription =  $current_product->getMeta_description();
		}else{
			$current_category = Mage::getModel('catalog/layer')->getCurrentCategory();
			//echo $current_category->getMeta_title();
			$curent_metaTitle = $current_category->getMeta_title();	
			$current_metaDescription =  $current_category->getMeta_description();
	 }
?>
      <h1 style="margin:0 !important;font-size:14px !important; font-weight:normal !important; color:#000; padding:0 !important;">
        <?php // $headBlock = $this->getLayout()->getBlock('head'); echo $title=$headBlock->getTitle(); ?>
        <?php 
      if(strlen($curent_metaTitle)>230){ echo substr($curent_metaTitle,0,230).".." ;	  
	  } else{		 
	   echo $curent_metaTitle;	  
	   }
?>
      </h1>
      <p style="font-size:12px; color:#000;">
        <?php
	//echo $current_category->getMeta_description();
    // $headBlock = $this->getLayout()->getBlock('head'); echo $description=$headBlock->getDescription();
      if(strlen($current_metaDescription)>380){ 
	  	echo substr($current_metaDescription,0,380).".." ;	  
	  }else{		  
	  	echo $current_metaDescription;	 
	  }
  ?>
      </p>
      <h1>
        <?php //echo Mage::getSingleton(‘cms/page’)->getTitle(); ?>
      </h1>
      <?php 
	  		//if custome is logged in then show this
			$current_customer = Mage::getSingleton('customer/session')->getCustomer();
			$session = Mage::getSingleton('customer/session', array('name'=>'frontend')); 
		if( $session->isLoggedIn() ){	
	  ?>
      <div class="customerinfo" style="width:400px; float:right; text-align:right; position:relative; top:-8px; right:-10px; color:#666"> Hello, <span style="color:#2290cd"><b><?php echo $current_customer->getName();?>!</b></span> </div>
      <?php 
		}
	  ?>
    </div>--> 
    <!--<div class="quick-access">
      <div class="top-promo1">
        <p title="Free Shipping on orders over 50$" class="f-right"></p>
      </div>
      <?php //echo $this->getChildHtml('store_language') ?>
      <div  class="clear"></div>
      <?php  //echo $this->getChildHtml('currency') ?>
      <?php //echo $this->getChildHtml('topSearch') ?>
      <div class="clear"></div>
      <?php echo $this->getChildHtml('topLinks') ?> </div>-->
    <div class="clear"></div>
    <?php // echo $this->getChildHtml('topMenu') ?>
  </div>
  <?php //echo $this->getChildHtml('topBar') ?>
  <?php //echo $this->getChildHtml('topContainer'); ?>
  <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('top_menu_slider')->toHtml();
		?>
</div>
<?php
	$curCatId = Mage::getSingleton('catalog/layer')->getCurrentCategory()->getId();
	/*load category */
	$_category = Mage::getSingleton('catalog/category')->load($curCatId);
	$_cat_video = $_category->getCat_video();
?>
<?php //	if($customer_pages == 0){ ?>
<?php /*?><div class="top_menu">
  <ul>
    <li><a class="green" href="<?php echo $this->getUrl('');?>">Home</a></li>
    <li><a href="<?php echo $this->getUrl('contacts_us');?>">Contact Us</a></li>
    <li><a href="<?php echo $this->getUrl('artwork');?>">Artwork Guide </a></li>
    <li><a href="https://picasaweb.google.com/107954288426326953438?noredirect=1" target="_blank">Gallery</a></li>
    <li><a href="<?php echo $this->getUrl('customer-service');?>">Customer Service</a></li>
    <li><a href="<?php echo $this->getUrl('portable-trade-show-booth-displays.html');?>">Portable Expo Booth</a><br>
    </li>
    <li><a href="<?php echo $this->getUrl('our-clients');?>">Our Clients</a></li>
    <li><a href="<?php echo $this->getUrl('uploadart');?>">Upload Artwork </a></li>
    <li><a href="<?php echo $this->getUrl('about_us');?>">Who We Are</a></li>
    <li><a href="<?php echo $this->getUrl('testimonial');?>">Testimonial</a></li>
    <li><a href="<?php echo $this->getUrl('faqs');?>">FAQ </a></li>
    <li><a href="<?php echo $this->getUrl('get_a_quote');?>">Get A Free Quote in 2 Minutes</a></li>
  </ul>
</div><?php */?>
<div style="margin-top: -30px;" class="top_menu">
  <div style="height:121px;" id="menuBall1" class="menuBall"> <a style="background:none;" href="<?php echo $this->getUrl('')?>" class="nav home_btn"> <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /> </a> </div>
  <div id="menuBall2" class="menuBall"> <a href="<?php echo $this->getUrl('about_us')?>" class="nav contact_btn">
    <div class="menuText"> <?php echo('About Us')?> </div>
    <br />
    <span class="navi-description"> <?php echo('Who we are')?> </span> </a> </div>
  <div id="menuBall3" class="menuBall"> 
  <?php $galleryurl = 'https://plus.google.com/photos/+VividAdsAutradeshowsaustralia/albums/6124406101444221089?banner=pwa'; ?>
    <a href="<?php echo $galleryurl; ?>" target="_blank" class="nav artwork_btn" >
   <!-- <a href="<?php echo $this->getUrl('gallery')?>" class="nav artwork_btn" >-->
    <div class="menuText"> <?php echo('Gallery')?> </div>
    <br />
    <span class="navi-description"> <?php echo('Work we pride')?> </span> </a> </div>
  <div id="menuBall4" class="menuBall"> <a href="<?php echo $this->getUrl('our-clients')?>" class="nav gallery_btn" >
    <div class="menuText"> <?php echo('Clients')?> </div>
    <br />
    <span class="navi-description"> <?php echo('Who we pride')?> </span> </a> </div>
  <?php /*?><div id="menuBall5" class="menuBall"> <a href="<?php echo $this->getUrl('')?>blog/?cat=6" class="nav clients_btn" >
    <div class="menuText"> <?php echo('Case Studies')?> </div>
    <br />
        <span class="navi-description"> <?php echo('What they say')?> </span>
    </a> </div><?php */?>
  <div id="menuBall5" class="menuBall"> <a href="<?php echo $this->getUrl('artwork-design')?>" class="nav clients_btn" >
    <div class="menuText"> <?php echo('Artwork Design')?> </div>
    <br />
    <span class="navi-description"> <?php echo('The Creative Guys')?> </span> </a> </div>
  <div id="menuBall6" class="menuBall"> <a href="<?php echo $this->getUrl('')?>blog/?cat=3" class="nav testimonial_btn" >
    <div class="menuText"> <?php echo('Video')?> </div>
    <br />
    <span class="navi-description"> <?php echo('How it Works')?> </span> </a> </div>
  <div id="menuBall7" class="menuBall"> <a href="<?php echo $this->getUrl('warranties')?>" class="nav portable_btn" >
    <div class="menuText"> <?php echo('Warranties')?> </div>
    <br />
    <span class="navi-description"> <?php echo('Our Confidence')?> </span> </a> </div>
  <div id="menuBall8" class="menuBall"> <a href="<?php echo $this->getUrl('')?>blog/?cat=1" class="nav who_we_are_btn" >
    <div class="menuText"> <?php echo('Education')?> </div>
    <br />
    <span class="navi-description"> <?php echo('We Guide')?> </span> </a> </div>
  <div id="menuBall9" class="menuBall"> <a href="<?php echo $this->getUrl('get_a_quote')?>" class="nav customer_btn" >
    <div class="menuText"> <?php echo('Free Quote')?> </div>
    <br />
    <span class="navi-description"> <?php echo('Its Free')?> </span> </a> </div>
  <div id="menuBall10" class="menuBall"> <a href="<?php echo $this->getUrl('contact-us')?>" class="nav upload_btn" >
    <div class="menuText"> <?php echo('Contact Us')?> </div>
    <br />
    <span class="navi-description"> <?php echo('Get In Touch')?> </span> </a> </div>
</div>
<?php 	//} ?>
<?php //if ($this->getIsHomePage()):?>
<?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('top_menu_slider')->toHtml() ?>
<?php //endif; ?>
<!--<div class="youama-slider-block" style="margin-top:0px;">
<img src="<?php //echo $this->getSkinUrl()?>images/slider0_1.jpg" width="937" />
</div>-->
<?php 
if($customer_pages==1)
{
?>
<div class="factory"><img alt="Factory Direct" src="<?php echo $this->getSkinUrl('images/factory_direct.png')?>"></div>
<?php } ?>
<?php   if($current_product != null) { ?>
<div class="view_slider"> </div>
<?php			}else { 		
		if($customer_pages == 0){
 	 		/*
			echo $this->getLayout()
					  ->createBlock('cms/block')
					  ->setBlockId('top_menu_slider')
					  ->toHtml();
			*/
			echo $this->getChildHtml('youamaslider');	
			 
			?>  
			
  
<div class="order_process">
<img src="<?php echo $this->getSkinUrl('images/order_process.png')?>" />
</div>

<div class="counters" style="float:left; width:100%;text-align:center;"> <img src="<?php echo $this->getSkinUrl('images/numbers.png');?>" width="1200" alt="Vivid Contact Info" />
  <div class="project" style="float:left;width:25%;">
    <h3 id="counter" ></h3>
    <h4>Happy Customers</h4>
  </div>
  <!--<div class="project" style="float:left;width:20%;">
    <h3 id="counter1"  ></h3>
    <h4>Awesome Projects</h4>
  </div>-->
  <div class="project" style="float:left;width:25%;">
    <h3 id="counter2" ></h3>
    <h4>Items Sold</h4>
  </div>
  <div class="project" style="float:left;width:25%;">
    <h3 id="counter3" ></h3>
    <h4>Facebook Likes</h4>
  </div>
  <div class="project" style="float:left;width:25%;">
    <h3 id="counter5" ></h3>
    <h4>Social Followers</h4>
  </div>
  <div class="project" style="float:left;width:16.66%; display:none;">
    <h3 id="counter4" >
      <?php //echo rand(1,20);
	    /*$visitor_collection = Mage::getResourceModel('log/visitor_collection')->useOnlineFilter();
        $visitor_count = count($visitor_collection);    
        if(!empty($visitor_count) && $visitor_count > 0)
        {
            $cnt =  $visitor_count;             
                echo 'Visitors online :'.$cnt;
        }*/  
		$visitor_count = Mage::getModel('log/visitor_online')
            ->prepare()
            ->getCollection()->count();
        if(!empty($visitor_count) && $visitor_count > 0)
        {
            $cnt =  $visitor_count;             
                echo $cnt;
        }  
	?>
    </h3>
    <h4>Visitors Today</h4>
  </div>
</div>
<?php			}
		}
  	$curl = $this->getUrl();
?>
<?php 
		$_front_session = Mage::getModel('core/session', array('name'=>'frontend'));
		$quote_qty = 0;
		if(count($_front_session->getProducts())>0){			
			$quote_qty = $_front_session->getQuoteqty();
			}
?>
<div style="top: 180px;display:block; z-index:1000;" onclick="document.location.href='<?php echo $curl;?>get_a_quote/';" class="contacts_button" id="contacts_button"></div>
<div class="uploader_artwork" style="display:block;">
  <?php /*?><div  id="quote_items_qty" class="quote_items_qty">(<?php echo $quote_qty;?>)</div><?php */?>
  <a title="Upload Artwork" href="<?php echo $curl;?>upload/" class="upload_icon artwork_upload"><span></span></a> <a  id="getqute" title="Quick Quote" href="javascript:void(0)" class="upload_icon get_quote"><span></span></a> <a title="Design Templates" href="<?php echo $curl;?>artwork/" class="upload_icon design-templates"><span></span></a> </div>



<?php   
		if($current_product == null) {
	 ?>
 <script>
			 
			jQuery(document).ready(function(){
				 
				function sdf_FTS(_number,_decimal,_separator)
				{
				var decimal=(typeof(_decimal)!='undefined')?_decimal:2;
				var separator=(typeof(_separator)!='undefined')?_separator:'';
				var r=parseFloat(_number)
				var exp10=Math.pow(10,decimal);
				r=Math.round(r*exp10)/exp10;
				rr=Number(r).toFixed(decimal).toString().split('.');				
				b=rr[0].replace(/(\d{1,3}(?=(\d{3})+(?:\.\d|\b)))/g,"\$1"+separator);
				
				r=(rr[1]?b+'.'+rr[1]:b);
				
				return r;
				}
				 
				window.onload  = setTimeout(function(){
					jQuery('#counter').text('0');
					//jQuery('#counter1').text('0');
					jQuery('#counter2').text('0');
					jQuery('#counter3').text('0');					
					jQuery('#counter5').text('0');					
//					$('#counter4').text('0');										
					
					 setInterval(function(){
						var curval=parseInt(jQuery('#counter').text().replace(' ',''));
						//var curval1=parseInt(jQuery('#counter1').text().replace(' ',''));
						var curval2=parseInt(jQuery('#counter2').text().replace(' ',''));
						var curval3=parseInt(jQuery('#counter3').text().replace(' ',''));
						var curval5=parseInt(jQuery('#counter5').text().replace(' ',''));
					//	var curval4=parseInt($('#counter4').text().replace(' ',''));
						if(curval<=26000){
							jQuery('#counter').text(sdf_FTS((curval+500),0,' '));
						//	$('#counter4').text(Math.floor((Math.random() * (20 - 5)) + 5));							
						}
						/*
						if(curval1<=66500){
							jQuery('#counter1').text(sdf_FTS((curval1+500),0,' '));
						}
						*/
						if(curval2<=924024){
							jQuery('#counter2').text(sdf_FTS((curval2+2500),0,' '));
						}
						if(curval2>=924024){
							jQuery('#counter2').text('Over 1 Million +');
						}
						if(curval3<=10000){
							jQuery('#counter3').text(sdf_FTS((curval3+500),0,' '));
						}
						 
						if(curval5<=50000){
							jQuery('#counter5').text(sdf_FTS((curval5+500),0,' '));
						}
						 
						/*if(curval3>=954024){
							$('#counter3').text('Over 1 Million +');
						}*/
					}, 400); 
				}, 2000);
			});
	</script>
<?php } ?>
